### ISSUE TITLE
Day 3 Hack Camp schedule + curriculum

### ISSUE THREAD

**Issue by maxwofford** [hackedu/hack-camp#101]
Create modules for day 3 curriculum of Hack Camp. This includes schedule + curriculum + metrics.
- [x] Pencil code lesson
- [x] Day 3 schedule
- [ ] Metrics and data collection
- [ ] Daily checklist for Hack Camp
- [ ] Add to Github
- [ ] Creat Metrics

**Comment by zachlatta** [comment]
Should we go ahead and close this now that day 3 is upon us?

**Comment by zachlatta** [comment]
Was this completed? Or did we just close it because day 3 passed?
