### ISSUE TITLE
Make Agar and Breakout for day 4.

### ISSUE THREAD

**Issue by jonleung** [hackedu/hack-camp#108]
1. See whether it is viable to build game in Pencilcode.
2. If not, build it in Scratch.

**Comment by zachlatta** [comment]
What's the deliverable for this issue?

**Comment by maxwofford** [comment]
Agar and breakout are not viable for Pencilcode.

If someone is at the level they can build agar in scratch, they should probably be doing agar/breakout in canvas. Can we close this?

**Comment by jonleung** [comment]
Yes @MaxWofford
