### ISSUE TITLE
Acquire CodeHS accounts for each student at hack camp's cohorts 1, 2, 3, and 4

### ISSUE THREAD

**Issue by jonleung** [hackedu/hack-camp#115]
Total ~== 35 accounts.

Can we also give us teacher accounts as well to view their progress?

Thanks!

**Comment by zachlatta** [comment]
Just sent them an email requesting this, waiting on response.

**Comment by zachlatta** [comment]
Boom, and we're good. Sign up links:
- Cohort 1: https://codehs.com/go/F57E
- Cohort 2: https://codehs.com/go/82F8
- Cohort 3: https://codehs.com/go/AFC0
- Cohort 4: https://codehs.com/go/DCF1

Ping me on IRC when you have a chance and I can add you to the courses as a teacher.

**Comment by jonleung** [comment]
Thanks!

On Monday, June 29, 2015, Zach Latta <notifications@github.com> wrote:

> Boom, and we're good. Sign up links:
>
>    - Cohort 1: https://codehs.com/go/F57E
>    - Cohort 2: https://codehs.com/go/82F8
>    - Cohort 3: https://codehs.com/go/AFC0
>    - Cohort 4: https://codehs.com/go/DCF1
>
> Ping me on IRC when you have a chance and I can add you to the courses as
> a teacher.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackedu/hack-camp/issues/115#issuecomment-116884144>.
>


-- 

—
Sent from my mobile–apologies for brevity and any typos!

hackedu.us | 610-761-0083
