### ISSUE TITLE
Write up something that helps us make and use modules +@jonleung +@maxwofford

### ISSUE THREAD

**Issue by jonleung** [hackedu/hack-camp#116]
We're not entirely sure how we might do this so we deliberately kept it vague.

**Comment by zachlatta** [comment]
Instead of putting +@jonleung and +@MaxWofford, it may make more sense to just put `/cc @jonleung @MaxWofford` in the issue body. See https://guides.github.com/features/issues/ for more info.

**Comment by zachlatta** [comment]
Closing due to using a different format for this upcoming cohort. See 0bc45c5a215fdd23a2d2e6933be20f54422577d5 for our notes from the planning session this morning.
