### ISSUE TITLE
Potential Improvements to Metrics

### ISSUE THREAD

**Issue by jonleung** [hackedu/hack-camp#119]
Review camp satisfaction scale in daily metrics form
@MaxWofford potentially suggests changing the legend
@jonleung potentially suggests changing the the legend and the scale

For Submission of Work, it would be great if we could include a self assessment which could contain something like this (the below is a really rough idea and seems a bit long...) @jonleung
- What are some things that you thought you did well in this project?
- What are some things that you thought you could improve on?
- What problems did you have / what are things that are confusing you?
- What do you think you are able to demonstrate mastery of in this assessment

**Comment by zachlatta** [comment]
This is nitpicky, but you've mentioned you'd like me to call you out on grammar things.

> @MaxWofford potentially suggests changing the legend

Do you mean to say "@MaxWofford suggests potentially changing the legend"?

**Comment by andreadeng** [comment]
in google drive
https://docs.google.com/a/berkeley.edu/forms/d/1luRx0021o0Hhnlp6FP3WwpyNjR7SIIF5GPtsBJPisNM/edit
