### ISSUE TITLE
Create a do's and don'ts list for facillitators

### ISSUE THREAD

**Issue by jonleung** [hackedu/hack-camp#120]
- Don't
  - Hover
- Do
  - Encourage students, google, to ask each other for help
  - Partnering on Projects
  - Projects
  - Walk people through baby projects before larger ones

**Comment by zachlatta** [comment]
Does it make sense to do this right now, given that we're not focused on documentation (yet)?

**Comment by zachlatta** [comment]
Closing due to cohort 2 being over.
