### ISSUE TITLE
Acquire TreeHouse accounts for each student at hack camp's cohorts 1, 2, 3, and 4 

### ISSUE THREAD

**Issue by jonleung** [hackedu/hack-camp#121]

**Comment by zachlatta** [comment]
How many accounts do we need?

**Comment by zachlatta** [comment]
Ping?

**Comment by jonleung** [comment]
@zachlatta, As discussed in standups, we need 34 accounts, one for each hack camp student.

**Comment by maxwofford** [comment]
Closed because we've decided against doing this in standups 7/27/2015
