### ISSUE TITLE
Rescheduling Deep Feedback + Kudos to Thursday?

### ISSUE THREAD

**Issue by jonleung** [hackedu/hack-camp#122]
Jonathan will be gone Friday the 3rd, @zachlatta, can you take lead on rescheduling them, perhaps to Thursday the 2nd?

**Comment by zachlatta** [comment]
@andreadeng has to leave early on Thursday. So it's either you or her that miss it. Thoughts?

**Comment by jonleung** [comment]
@andreadeng @zachlatta we can do it Wed?

**Comment by zachlatta** [comment]
Wednesday seems pretty early in the week for this sort of reflection and
both you and I already have stuff scheduled ~5PM on Wednesday. What if
we just do it on Friday (and unfortunately won't have you in it)?

**Comment by jonleung** [comment]
@zachlatta that's fine

**Comment by zachlatta** [comment]
As discussed in person with @jonleung last night, we won't be rescheduling these to Thursday and they'll happen on Friday as planned.

**Comment by zachlatta** [comment]
Whoops, accidentally closed! Will review this during standups today.
