### ISSUE TITLE
Write draft MVP objectives for Hack Camp + Cohorts 2, 3, 4

### ISSUE THREAD

**Issue by jonleung** [hackedu/hack-camp#123]
Submit a PR to https://github.com/hackedu/hack-camp/tree/hack-camp-objectives

Also as a note for Jonathan, think about how the team may work while you are gone for preparation of cohort 3.
# Consider the the below notes as personal to Jonathan (not for public consumption)

The atmosphere and attitude we take to learning how to do things is critically important
- [ ] Openness to feedback => Iteration
- [ ] Constantly asking and getting feedback from learners

**Comment by jonleung** [comment]
@zachlatta I unfortunately didn't have time to get to this this weekend. I have failed! I apologize for that.

**Comment by jonleung** [comment]
I'll try to finish it tomorrow.

**Comment by zachlatta** [comment]
Can we shoot to get this by tonight? Happy to work together on it. I
think it's really critical to have these clarified ASAP.

**Comment by jonleung** [comment]
@zachlatta I think that it may not be high leverage for me to put this in an official written form (i.e. a PR) until we have the rough draft validated. Here is the rough draft:
https://workflowy.com/s/lVKtQ1Lkcr

**Comment by jonleung** [comment]
Updating: https://workflowy.com/s/lVKtQ1Lkcr#/c86cc2fa5a8f

**Comment by jonleung** [comment]
@zachlatta Here is an updated version: https://gist.github.com/jonleung/495577313853034e0d4f

**Comment by maxwofford** [comment]
As discussed during standups today, @zachlatta will iterate on this and incorporate it into #105.

**Comment by zachlatta** [comment]
Alright – went ahead and incorporated your changes into #105 :-).

As discussed, we'll iterate on the objectives as needed.
