### ISSUE TITLE
Ask Galvanize for more space

### ISSUE THREAD

**Issue by jonleung** [hackedu/hack-camp#124]
Cohort 3 is 10ppl + 3facillitators (_13_)
Cohort 4 is 14ppl + 3facillitators (_17_)

Our classroom fits 10 maximum.

I should have saw this coming initially, I didn't think we'd try to attempt getting such large cohort sizes + accounting for facilitator seats. I HAVE FAILED!

So, we need to talk to Ryan about getting a larger classroom in the basement. They have one that they rent out (occasionally I think) that they may be able to give us.

@zachlatta, can you take lead on this? Would love to sync up on how we may resolve the issue.

**Comment by zachlatta** [comment]
Yup, let's find a time today or tomorrow to chat about this. We should tackle this ASAP.

**Comment by zachlatta** [comment]
Alright, per our in-person discussion, we'll be asking Ryan for the "Mission Bay" room in the basement from July 13th to July 23rd (cohort 3) and for two weeks in August (we haven't confirmed the dates yet for cohort 4).

**Comment by jonleung** [comment]
@zachlatta just to keep you updated, Ryan was busy today and rescheduled tomorrow so I'll be asking him tomorrow.

**Comment by jonleung** [comment]
Woops, accidently closed it ^

**Comment by jonleung** [comment]
Ryan isn't responding : /
Going to ping him again for a time to meetup today

**Comment by jonleung** [comment]
Just messaged him

**Comment by zachlatta** [comment]
Just sent Ryan an email – hopefully he'll get back soon.

**Comment by zachlatta** [comment]
Alright, he got back and looped a few others into the discussion. Will correspond with them and keep ya'll updated.

**Comment by zachlatta** [comment]
I'm pinging him trying to get a response.

**Comment by zachlatta** [comment]
Pinged him again.

**Comment by zachlatta** [comment]
Aaaand we're confirmed for the Mission Bay room next week.

**Comment by maxwofford** [comment]
cohort 3: ![](https://a248.e.akamai.net/f/50/31/6/static.gamespot.com/uploads/original/391/3912151/2441702-0720251747-origi.gif)
