### ISSUE TITLE
Obtain more Twilio credits for Maestro

### ISSUE THREAD

**Issue by jonleung** [hackedu/hack-camp#125]
EDIT:
Changed Edit => Obtain

**Comment by zachlatta** [comment]
Can you take lead on this? I believe you're the only person who knows Eva.

**Comment by maxwofford** [comment]
@jonleung It would also be great if we could get auto-recharging accounts. It seems like we use twilio for quite a few projects we host.

**Comment by jonleung** [comment]
@zachlatta @MaxWofford just an update that I just emailed Eva

**Comment by zachlatta** [comment]
Any updates on this?

**Comment by zachlatta** [comment]
Also, heads up, you don't need to worry about specifying your edits to the title. GitHub automatically keeps and shows a changelog.

**Comment by jonleung** [comment]
Just emailed again

On Sunday, July 5, 2015, Zach Latta notifications@github.com wrote:

> Also, heads up, you don't need to worry about specifying your edits to the
> title. GitHub automatically keeps and shows a changelog.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/hackedu/hack-camp/issues/125#issuecomment-118736027.

## 

—
Sent from my mobile–apologies for brevity and any typos!

hackedu.us | 610-761-0083

**Comment by jonleung** [comment]
They said they can give us $100 for now, waiting on promocode

**Comment by zachlatta** [comment]
Updates on this?

**Comment by jonleung** [comment]
@zachlatta Just followed up again!

**Comment by zachlatta** [comment]
:+1:

## 

Zach Latta
Executive Director of hackEDU https://hackedu.us/
http://zachlatta.com
https://github.com/zachlatta
https://twitter.com/zachlatta

**Comment by jonleung** [comment]
We got the promotion code, I need to link it to a secure file in Dropbox

**Comment by jonleung** [comment]
@MaxWofford @zachlatta, I added the promo code to secrets.txt in the Dropbox under "Twilio"

**Comment by jonleung** [comment]
@MaxWofford do you want to try adding this promo code to your Twilio account?

**Comment by maxwofford** [comment]
@jonleung This promo-code is only for trial accounts.

**Comment by zachlatta** [comment]
I just created https://github.com/hackedu/gifts that you can add it to.
