### ISSUE TITLE
Print tshirts for campers

### ISSUE THREAD

**Issue by andreadeng** [hackedu/hack-camp#137]

**Comment by zachlatta** [comment]
Went ahead and assigned you to this because I'm feeling backlogged.

Happy to work with you to get this done – I know someone who can print t-shirts for cheap, just ping me on IRC.

**Comment by maxwofford** [comment]
Happy to complete this @zachlatta & @andreadeng if someone pm's the contact info for the printer.

**Comment by zachlatta** [comment]
`Tom Morrison <morrisonpro@earthlink.net>` is the printer I've previously used. He's in downtown SF. You'll have to email him directly or google for "Morrison Productions" and call to get in touch with him.

[The file I sent him last time we got shirts printed.](https://files.zenhub.io/559478d927ca35b74f68dc59)

Last time we had the logo 5 1/2 inches wide and with the following location on the shirt (hi @Jarred-Sumner's torso!):

![2015-05-06 16 57 43](https://cloud.githubusercontent.com/assets/992248/8467111/12a4ec14-200f-11e5-8de4-2f3e9daac744.jpg)

On the next batch we do we probably want the logo a bit larger and a little farther down on the shirt. Before confirming anything with them, can you run final details by me?

**Comment by maxwofford** [comment]
@zachlatta, would you please review the copy I send via IRC?

**Comment by Jarred-Sumner** [comment]
oh that's why i got an email about this

**Comment by zachlatta** [comment]
Responded with feedback!

**Comment by Jarred-Sumner** [comment]
💩

**Comment by maxwofford** [comment]
Currently waiting on #150 so we have a logo for the shirts.

**Comment by andreadeng** [comment]
![screenshot 2015-07-23 10 46 54](https://cloud.githubusercontent.com/assets/2925784/8857706/31088f6a-3128-11e5-9e71-7a5d47095e53.png)

shirt idea? @zachlatta @jonleung @MaxWofford

**Comment by zachlatta** [comment]
Love it.

Can you try making the `hackEDU` on the back in Amaranth and bold?

Also, what does it look like if you slightly shift all of the text in the
`HACK` over to the right just a little bit (while keeping the background
mask in the same position).

## 

Zach Latta
Executive Director of hackEDU https://hackedu.us/
http://zachlatta.com
https://github.com/zachlatta
https://twitter.com/zachlatta

**Comment by Jarred-Sumner** [comment]
How does this sound? http://teespring.com/zach-latta

**Comment by zachlatta** [comment]
_oh no_

## 

Zach Latta
Executive Director of hackEDU (https://hackedu.us)
http://zachlatta.com
https://github.com/zachlatta
https://twitter.com/zachlatta

**Comment by Jarred-Sumner** [comment]
lmao

**Comment by maxwofford** [comment]
@andreadeng Would you please add the t-shirt logo as an svg to the logos directory when you are done with them?

**Comment by zachlatta** [comment]
@andreadeng any updates on this?

**Comment by maxwofford** [comment]
Closing because we were too late on this.
