### ISSUE TITLE
Rebase Hack Camp Objectives into PR

### ISSUE THREAD

**Issue by jonleung** [hackedu/hack-camp#138]
Sync with @zachlatta or @MaxWofford  on how @jonleung might incorporate the hack camp objectives into the hack camp repo with rebase.

**Comment by zachlatta** [comment]
Why do you need to rebase? What if you just delete the old branch and make a new one and commit on that?

**Comment by jonleung** [comment]
Closing because @zachlatta addressed this in #123,
