### ISSUE TITLE
Fix date ranges to start on Mondays and end on Fridays

### ISSUE THREAD

**Issue by zachlatta** [hackedu/hack-camp#14]
Haven't checked the other date ranges yet, but I had a parent reach out to me to clarify July 6th - July 20th and whether the camp ends on Friday the 17th or Monday the 20th. I believe the other date ranges have this issues as well.

**Comment by maxwofford** [comment]
They do, though the dates in #13 should be fixed.

**Comment by zachlatta** [comment]
Hmm? It looks like June 15th - June 29th also has this issue.

![tmp](https://cloud.githubusercontent.com/assets/992248/7785246/24eb0260-013c-11e5-9baf-ad9930b7276b.png)

**Comment by maxwofford** [comment]
@zachlatta Ah, thnx. Ignore the #13 for now. I'll update it to work with our sinatra branch.

**Comment by zachlatta** [comment]
Sounds good.

**Comment by maxwofford** [comment]
#13 should be merged; it fixes a different issue. I hadn't realized this issue was about the form dates on the application page. It would be great if that could be clarified.

**Comment by maxwofford** [comment]
#16 fixes this issue
