### ISSUE TITLE
Fix connection issue for certain people's Shout accounts

### ISSUE THREAD

**Issue by jonleung** [hackedu/hack-camp#146]
Students who had Shout accounts that work:
- Selyna (ssun)

Students who had Shout accounts that didn't work:
- Emily (ezhu)
- Matthew
- Sam

Screenshot for what it looks like if it doesn't work:
![](https://s3.amazonaws.com/f.cl.ly/items/0N1t370R1t2h1o1n0j1G/Image%202015-07-02%20at%204.16.00%20PM.png)

**Comment by zachlatta** [comment]
Done! They work now.
