### ISSUE TITLE
Tell Hack Camp applicant whether we want to accept or reject her.

### ISSUE THREAD

**Issue by jonleung** [hackedu/hack-camp#147]
Earlier today, an applicant called me and asked if there were any openings in subsequent cohorts. I told her that I was not in charge of admissions and that the person in charge of admissions would get back to. I'll let @andreadeng make the decision to admit her or not.  She says that either email or phone work for her (I would just text her if you want a faster response)

EDIT: Took out applicant contact info -@maxwofford

**Comment by maxwofford** [comment]
@jonleung Not sure if we want applicant contact info to be public.

EDIT: For now, taking it out of the description and putting it in a pm over IRC to @andreadeng & @jonleung.

**Comment by jonleung** [comment]
:+1:

**Comment by zachlatta** [comment]
Status on this?

**Comment by zachlatta** [comment]
Any updates on this?

**Comment by zachlatta** [comment]
:thumbsup:
