### ISSUE TITLE
Collect end of cohort 2 metrics

### ISSUE THREAD

**Issue by jonleung** [hackedu/hack-camp#148]
We need to make sure that we collect the the end of program metrics. There are 2 forms:
- [ ] the Pre-Program Growth Mindset / Grit Questionnaire [here is a link to the form we have been using for Cohort 1 & Cohort 2](https://docs.google.com/forms/d/1OmBQ3rS6VtMH_5jc4FR01SQ_0Je5NI64q5rNEHOGtlk/edit) (no modification required)
- [ ] Here is the Post Program Questionaire [here is a link to the  form from Cohort 1](https://docs.google.com/forms/d/1QrIG068iOV8-eXCawPtwOHJ0IElAX7QKssI6_oc5DOU/edit)

Note: Estimate that these will take 1 hour to complete so perhaps
- 2:30pm demos
- 3:00pm collect metrics
- 4:00pm wrap up / conclusion / inspiring things / bonding things

**Comment by zachlatta** [comment]
@andreadeng did we ever end up collecting the growth mindset / grit questionnaire?

**Comment by andreadeng** [comment]
GROWTH/GRIT
https://docs.google.com/spreadsheets/d/1ooBimVKiI9ztIQDu8BJ9iRgkN7JCXQH9HtTq2XxS4oA/edit#gid=2028509598
