### ISSUE TITLE
Acquire CodeHS beta content

### ISSUE THREAD

**Issue by jonleung** [hackedu/hack-camp#149]
@zachlatta, as discussed during our one on one on the roof top, can you inquire about CodeHS's beta content ASAP (this could be game changing for our curriculum)? I'm not sure if it is public what they're beta content is so I'll PM you the specific. Thanks!

**Comment by zachlatta** [comment]
Is this still super relevant now that we're not actively using CodeHS?

## 

Zach Latta
Executive Director of hackEDU https://hackedu.us/
http://zachlatta.com
https://github.com/zachlatta
https://twitter.com/zachlatta

**Comment by zachlatta** [comment]
Closing for now due to lack of response.
