### ISSUE TITLE
Hack Camp logo

### ISSUE THREAD

**Issue by zachlatta** [hackedu/hack-camp#150]
What if we created a simple logo for Hack Camp? Would be nice to have something pretty to put into the readme.

Thoughts?

/cc @hackedu/hack-camp @andreadeng

**Comment by maxwofford** [comment]
Should I hold off on shirts for the time being so we can have the Hack Camp logo on them?

**Comment by zachlatta** [comment]
Yeah – hold off right now. @andreadeng what are your thoughts on
creating a logo for Hack Camp?

**Comment by zachlatta** [comment]
As discussed this morning, we're going to go ahead and do this.

**Comment by andreadeng** [comment]
![hack_camp_logo-02](https://cloud.githubusercontent.com/assets/2925784/8660349/4bfa7024-2965-11e5-9dc1-67e1f89fb5ca.jpg)
Final hack camp logo? @zachlatta @jonleung @MaxWofford

**Comment by andreadeng** [comment]
actually idk if the eyes look better like this
![hackcamplogo_dino-02](https://cloud.githubusercontent.com/assets/2925784/8660427/b459140e-2965-11e5-975b-15562b057bac.png)

**Comment by zachlatta** [comment]
I'm personally partial towards the red one without the dino, but I'm good
with most anything.

Thoughts @jonleung and @MaxWofford?

## 

Zach Latta
Executive Director of hackEDU https://hackedu.us/
http://zachlatta.com
https://github.com/zachlatta
https://twitter.com/zachlatta

**Comment by jonleung** [comment]
@andreadeng @zachlatta I'm down with the block letters as well with the red : )

**Comment by zachlatta** [comment]
@MaxWofford thoughts on block letters on red vs. dino?

## 

Zach Latta
Executive Director of hackEDU https://hackedu.us/
http://zachlatta.com
https://github.com/zachlatta
https://twitter.com/zachlatta

**Comment by maxwofford** [comment]
@hackedu/hack-camp I'm good with either dino or red. Could I get a link to the red image?

**Comment by zachlatta** [comment]
@andreadeng?

## 

Zach Latta
Executive Director of hackEDU https://hackedu.us/
http://zachlatta.com
https://github.com/zachlatta
https://twitter.com/zachlatta

**Comment by zachlatta** [comment]
Just discussed with @andreadeng in person and we're going to go ahead with the block letter red logo after she's made some adjustments.

She'll be posting iterations here.

/cc @andreadeng

**Comment by andreadeng** [comment]
![screen shot 2015-07-21 at 4 15 16 pm](https://cloud.githubusercontent.com/assets/2925784/8814651/bef71578-2fc3-11e5-85f5-2743ba4ded17.png)
Font options? for sticker/logo

**Comment by maxwofford** [comment]
@andreadeng I'm partial to the last 3

**Comment by zachlatta** [comment]
I like the last one the most. Any chance we could get the font a bit more bold?

**Comment by zachlatta** [comment]
Moving this to the cohort 4 preparation milestone because if we order the stickers today they won't be here by the end of this cohort.

**Comment by andreadeng** [comment]
![screenshot 2015-07-22 10 38 18](https://cloud.githubusercontent.com/assets/2925784/8832416/d0e46ac0-305d-11e5-908e-335bfc4a702b.png)

top one is bolder and bottom one is EVEN bolder LOL @zachlatta @jonleung @MaxWofford

**Comment by zachlatta** [comment]
What if we went with the first one?

/cc @jonleung @MaxWofford @andreadeng

**Comment by andreadeng** [comment]
![hackcamp_sticker-01](https://cloud.githubusercontent.com/assets/2925784/8854834/d7e7837a-3116-11e5-84ee-f33bd23577b6.png)

**Comment by zachlatta** [comment]
:+1:

## 

Zach Latta
Executive Director of hackEDU https://hackedu.us/
http://zachlatta.com
https://github.com/zachlatta
https://twitter.com/zachlatta

**Comment by maxwofford** [comment]
Can this be closed?

**Comment by zachlatta** [comment]
@andreadeng: can you commit the final version to this repo, perhaps to
`meta/logo.png`?

## 

Zach Latta
Executive Director of hackEDU https://hackedu.us/
http://zachlatta.com
https://github.com/zachlatta
https://twitter.com/zachlatta

**Comment by jonleung** [comment]
:+1:
