### ISSUE TITLE
Order breakfast for cohort 3

### ISSUE THREAD

**Issue by zachlatta** [hackedu/hack-camp#151]

**Comment by zachlatta** [comment]
I guess I'll take this over now that it's the weekend. @andreadeng, what should I buy?

**Comment by maxwofford** [comment]
@zachlatta Quick list of stuff from previous cohorts:
- Bananas
- Peanut butter
- Strawberry preserves
- Cherios
- Milk
- Soy milk
- Variety pack of oatmeal
- Sandwich bread

**Comment by zachlatta** [comment]
Great, thanks so much!

## 

Zach Latta
Executive Director of hackEDU https://hackedu.us
http://zachlatta.com
https://github.com/zachlatta
https://twitter.com/zachlatta

**Comment by zachlatta** [comment]
Went ahead and placed the Instacart order. Delivers later today.
