### ISSUE TITLE
Email hackers to make sure everyone brings their own lunch

### ISSUE THREAD

**Issue by zachlatta** [hackedu/hack-camp#152]

**Comment by maxwofford** [comment]
Restaurants are bad.

**Comment by zachlatta** [comment]
I guess I'll take this over now that it's the weekend.

**Comment by zachlatta** [comment]
Send an email out! https://groups.google.com/d/msg/hack-camp-cohort-3/pMzbz7I1WHg/p_a8hbiegnsJ
