### ISSUE TITLE
Create an SMS bot workshop

### ISSUE THREAD

**Issue by maxwofford** [hackedu/hack-camp#159]
Student deliverable: simple SMS bot (see [hackedu/steward](https://github.com/hackedu/steward)).

Notes:
- More JavaScript fundamentals

**Comment by maxwofford** [comment]
@TheThirdOne @zachlatta Currently blocking on maestro's recieveSms function not working.

**Comment by TheThirdOne** [comment]
Which commit are you on? I would expect some of them to not work.

**Comment by maxwofford** [comment]
Going to hold off on this until after the first workshop (portfolio workshop).

EDIT: This is taken off the cohort 3 milestone because it will need to be fine-tuned for the students after we get feedback on the first workshop.

**Comment by zachlatta** [comment]
Closing in favor of #180.

**Comment by maxwofford** [comment]
@zachlatta :+1:
