### ISSUE TITLE
Create a todo-list workshop

### ISSUE THREAD

**Issue by maxwofford** [hackedu/hack-camp#161]
Student deliverable: Todo List app
Notes:
- User auth (users should have separate tasks)
- Firebase

**Comment by maxwofford** [comment]
Taking this off the [milestone](https://github.com/hackedu/hack-camp/milestones/Prepare%20for%20Cohort%203) because it doesn't need to be completed by Monday.

/cc @zachlatta

**Comment by maxwofford** [comment]
I might want to fork @ssun098's [task-list](https://github.com/ssun098/task-list) app for this.

**Comment by andreadeng** [comment]
i was talking to alyssa today and she said she really wants to make a task/to do iist app!

**Comment by zachlatta** [comment]
Awesome!

## 

Zach Latta
Executive Director of hackEDU https://hackedu.us/
http://zachlatta.com
https://github.com/zachlatta
https://twitter.com/zachlatta

**Comment by selynna** [comment]
@MaxWofford I'm totally fine with you forking the task list, but it's not exactly the most functional...I think some features are still broken.  Is that okay?

**Comment by zachlatta** [comment]
Closed by 696c7fe409c3d7b554733b36e913e414851cec32.

**Comment by jonleung** [comment]
@zachlatta thanks!
