### ISSUE TITLE
Create anonymous misconduct form

### ISSUE THREAD

**Issue by zachlatta** [hackedu/hack-camp#174]

**Comment by jonleung** [comment]
@zachlatta One thing that is important thing is to be able to give feedback to other people without introducing shame. How do you plan for this to be executed?

**Comment by maxwofford** [comment]
@zachlatta Please clarify what would be on this form :-)

**Comment by zachlatta** [comment]
@jonleung give feedback to other participants? Or to the instructors?

@MaxWofford I'll just go ahead and create the form, won't clarify for now. Not entirely sure what I'd like on it yet.

**Comment by jonleung** [comment]
@zachlatta, I just made same changes!

**Comment by maxwofford** [comment]
@zachlatta It will now notify us anytime something is submitted. [here](https://script.google.com/macros/d/MC-xxDXmv0Wz8y6FRxpNgwvDp8aFBtR4M/edit?uiv=2&mid=ACjPJvFRE2UnIg1OeWsnaWWGEgI94sDJ7xC2i5Lw1NJDfPYou5HdW5rU0BCishzAbWrYlWGTGjea4L3IZXsBIG8i_0Jb0ooEw4WY2TpbXxI5qVwJHvi3gnYnYts0Gnfbnpas_9-TxVMoFCc) is the script.

Give me a heads up if we want to change the fields, it might break something.

**Comment by jonleung** [comment]
@maxwofford, also just an FYI:

You can subscribe to notifications through the standard user interface:
https://support.google.com/docs/answer/91588?hl=en

**Comment by maxwofford** [comment]
@jonleung That would be too easy >:-)

**Comment by zachlatta** [comment]
Great. Can I close this?

## 

Zach Latta
Executive Director of hackEDU https://hackedu.us/
http://zachlatta.com
https://github.com/zachlatta
https://twitter.com/zachlatta

**Comment by zachlatta** [comment]
May it make sense for us to subscribe to notifications like this instead?

## 

Zach Latta
Executive Director of hackEDU https://hackedu.us/
http://zachlatta.com
https://github.com/zachlatta
https://twitter.com/zachlatta

**Comment by maxwofford** [comment]
Think so! I'll disable the script if we decide to do that.
