### ISSUE TITLE
Scan Hack Camp waivers

### ISSUE THREAD

**Issue by zachlatta** [hackedu/hack-camp#177]
Can you scan the waivers for the 3rd cohort and put them into our Dropbox under the Hack Camp folder? I've left them on our table (next to all of the post-it notes) in the hackerspace.

Thanks :-).

**Comment by andreadeng** [comment]
Yes I'll get to these!

**Comment by andreadeng** [comment]
Added to the dropbox!

**Comment by zachlatta** [comment]
:thumbsup:

## 

Zach Latta
Executive Director of hackEDU https://hackedu.us/
http://zachlatta.com
https://github.com/zachlatta
https://twitter.com/zachlatta

**Comment by zachlatta** [comment]
Great! Thanks.

## 

Zach Latta
Executive Director of hackEDU https://hackedu.us/
http://zachlatta.com
https://github.com/zachlatta
https://twitter.com/zachlatta
