### ISSUE TITLE
Figure out cohort 4 payment

### ISSUE THREAD

**Issue by jonleung** [hackedu/hack-camp#179]
Because the objective of the fourth cohort is to test to see if we can have another member of the hackEDU team reproduce the experience from the second and third cohorts from a set of materials, we may not be able to deliver the same quality of the hackEDU experience as earlier cohorts.

Also, under the __Who's Mentoring This__ section of the Hack Camp website, it states:

> Who's mentoring this?
> Hack Camp is led by the co-founders of hackEDU, two wonderfully optimistic and energetic guys: Zach Latta and Jonathan Leung. With 15 years of coding experience between them, they are a stellar team. Zach is an accomplished programmer, with multiple applications in the App Store with over 4 million users. Jonathan is an experienced coder and curriculum writer: he grew the now prestigious PennApps hackathon from 80 to 1000 participants and taught at All Star Code so effectively that his students went on to form their own coding non-profit.

This will not be true for Cohort 4. In that case, will we need to (1) Change the payment structure (2) explicitly inform cohort 4 applicants that this change is happening?

**Comment by maxwofford** [comment]
@zachlatta, would you like to take lead on organizing this?

**Comment by zachlatta** [comment]
What if we kept discussion for this here instead of scheduling a meeting?

I'd personally partial towards keeping payment the way it is, but
communicating to the hackers for cohort 4 (when we're accepting them) that
we won't be running this cohort. We could write a similar spiel for
@GemmaBusoni and send them that.

Thoughts?

## 

Zach Latta
Executive Director of hackEDU https://hackedu.us/
http://zachlatta.com
https://github.com/zachlatta
https://twitter.com/zachlatta

**Comment by jonleung** [comment]
@zachlatta writing is good for me. I personally don't care if we change or don't change payment.

**Comment by zachlatta** [comment]
Alright, cool.

I'm partial towards still charging $595 and having @GemmaBusoni lead. I do
think it's important that we communicate to all the hackers (when we're
accepting them) that the next cohort will be run by her, and not us, and
include a bio of her.

Thoughts?

/cc @MaxWofford @andreadeng

## 

Zach Latta
Executive Director of hackEDU https://hackedu.us/
http://zachlatta.com
https://github.com/zachlatta
https://twitter.com/zachlatta

**Comment by maxwofford** [comment]
@zachlatta Think it is def important to tell them it will be run by @gemmabusoni. Think it will help set the mood and break down that teacher/student relationship our other cohorts have had.

**Comment by zachlatta** [comment]
Agreed.

@GemmaBusoni - do you have a short bio anywhere that we could use?

## 

Zach Latta
Executive Director of hackEDU https://hackedu.us/
http://zachlatta.com
https://github.com/zachlatta
https://twitter.com/zachlatta

**Comment by zachlatta** [comment]
Discussed with @andreadeng this morning.

Let's go ahead and have them pay the $595 in full. I'll communicate this to @gemmabusoni.
