### ISSUE TITLE
Create DOM Manipulation Workshop for Friday

### ISSUE THREAD

**Issue by jonleung** [hackedu/hack-camp#180]
As discussed on Wednesday July 16th's evening meeting, Jonathan will be leading Friday and will create a DOM Manipulation workshop and make a PR [here](https://github.com/hackedu/hack-camp/tree/master/cohort_3/curriculum/workshops).

**Comment by jonleung** [comment]
Will be working with @MaxWofford on this!

**Comment by maxwofford** [comment]
@jonleung Kudos for working through this so quickly!

**Comment by zachlatta** [comment]
Yeah – that was some diligent work.

Ship it! :shipit:

## 

Zach Latta
Executive Director of hackEDU https://hackedu.us/
http://zachlatta.com
https://github.com/zachlatta
https://twitter.com/zachlatta
