### ISSUE TITLE
Get in contact with c9.io

### ISSUE THREAD

**Issue by maxwofford** [hackedu/hack-camp#181]
We should open a line of communication with Cloud9 so we can be prepared when we run into blocking issues with their service.

**Comment by zachlatta** [comment]
Agreed. I can take lead on this.

## 

Zach Latta
Executive Director of hackEDU https://hackedu.us/
http://zachlatta.com
https://github.com/zachlatta
https://twitter.com/zachlatta

**Comment by zachlatta** [comment]
Actually, I think it may make sense for us to move this to https://github.com/hackedu/meta.

**Comment by maxwofford** [comment]
@zachlatta :+1:

**Comment by maxwofford** [comment]
:tada:
