### ISSUE TITLE
Connect Zach with Daniel (Pleasanton code camp) via email to setup a time next week for him to visit Hack Camp

### ISSUE THREAD

**Issue by andreadeng** [hackedu/hack-camp#182]

**Comment by zachlatta** [comment]
Looking forward to showing him around the place :-).

## 

Zach Latta
Executive Director of hackEDU https://hackedu.us/
http://zachlatta.com
https://github.com/zachlatta
https://twitter.com/zachlatta

**Comment by zachlatta** [comment]
Replied to the intro!
