### ISSUE TITLE
Create facilitator facing guidelines on how to problem solve

### ISSUE THREAD

**Issue by jonleung** [hackedu/hack-camp#184]
As discussed on cohort 3 day 5 in post-mortem on July 17th

/cc @MaxWofford @zachlatta

**Comment by zachlatta** [comment]
@jonleung want to take lead on this?

**Comment by jonleung** [comment]
@zachlatta sounds good

**Comment by zachlatta** [comment]
I'm going to go ahead and close this for now. We can reopen if we decide it's important or very actionable.

**Comment by zachlatta** [comment]
Also removing from the prepare for cohort 4 milestone.
