### ISSUE TITLE
Refactor Instagram workshop

### ISSUE THREAD

**Issue by jonleung** [hackedu/hack-camp#185]
Iterate on feedback from Jonathan's personal notes

Add after each step, "now go do this in cloud9" yourself

Add more checkpoints and challenges

Add CSS

**Comment by zachlatta** [comment]
Can you include your notes, perhaps in this issue or a file somewhere?

Also, you don't need to refer to yourself in the third person when creating
issues ;-).

On Saturday, July 18, 2015, Jonathan Leung notifications@github.com wrote:

> Iterate on feedback from Jonathan's personal notes
> 
> Add after each step, "now go do this in cloud9" yourself
> 
> Add more checkpoints and challenges
> 
> Add CSS
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/hackedu/hack-camp/issues/185.

## 

## 

Zach Latta
Executive Director of hackEDU https://hackedu.us/
http://zachlatta.com
https://github.com/zachlatta
https://twitter.com/zachlatta

**Comment by jonleung** [comment]
@zachlatta, will add notes later, will need to dig them up

**Comment by zachlatta** [comment]
:+1:

## 

Zach Latta
Executive Director of hackEDU https://hackedu.us/
http://zachlatta.com
https://github.com/zachlatta
https://twitter.com/zachlatta

**Comment by zachlatta** [comment]
Going to go ahead and remove this from the prepare for cohort 4 milestone. We'll only be tackling the first four days of camp, as discussed.

**Comment by maxwofford** [comment]
@hellyeah Why was this closed?

**Comment by zachlatta** [comment]
@MaxWofford: I believe @hellyeah closed this during standups and @jonleung
would have more insight into why this was closed.

On Tue, Aug 18, 2015 at 5:46 PM, Max Wofford notifications@github.com
wrote:

> @hellyeah https://github.com/hellyeah Why was this closed?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/hackedu/hack-camp/issues/185#issuecomment-132404630.

## 

Zach Latta
hackEDU | zach@hackedu.us

**Comment by jonleung** [comment]
@MaxWofford, it will take too long to fix the workshop. If I try to fix the workshop, I will not complete the objectives for the Labs program.

Here is what needs fixing:

We need to shorten the initial preface. There is too much reading before the student gets a chance to write any code.

/cc @zachlatta @hellyeah

**Comment by hellyeah** [comment]
If someone links me to this, I have enough time today to do 1 round of editing for brevity. Beyond that, I don't think we have time to devote to his before bm.

**Comment by jonleung** [comment]
@hellyeah, I vote that we don't work on this now.

**Comment by hellyeah** [comment]
sounds good. not top priority.
