### ISSUE TITLE
Accept cohort 4

### ISSUE THREAD

**Issue by zachlatta** [hackedu/hack-camp#188]
The time has come to accept the hackers for cohort 4.

We'll want the following skill set breakdown:
- 7 with no coding experience
- 4 with some coding experience, but have not finished a project before
- 3 who have finished one or multiple projects

As we accept people for this cohort, make sure we communicate to them that @gemmabusoni will be running this session of the camp.

**Comment by zachlatta** [comment]
I've gone ahead and created #189 to track getting a bio for @gemmabusoni.

**Comment by jonleung** [comment]
@andreadeng @zachlatta as discussed we may try to ask old cohorts to ask their friends to come apply to cohort 4 especially Selena's friend.

We'd really appreciate if you could refer 3 friends.

**Comment by jonleung** [comment]
Closed accidentally, reopening

**Comment by zachlatta** [comment]
We've done this! Glad to have this over.

![](http://img2.wikia.nocookie.net/__cb20140813011251/degrassi/images/b/be/We-Did-It.gif)
