### ISSUE TITLE
Create Gemma bio

### ISSUE THREAD

**Issue by zachlatta** [hackedu/hack-camp#189]
Create a bio for @gemmabusoni to share with hackers that we're accepting.

**Comment by zachlatta** [comment]
Here we are:

The next session of Hack Camp will be led by Gemma Busoni, a wonderfully energetic gal who loves building things. Between creating virtual reality games and working at a research lab at Caltech, she's a prolific attendee and organizer of [hackathons](https://en.wikipedia.org/wiki/Hackathon). She's previously organized [CodeDay LA](https://codeday.org/la) at [will.i.am](http://will.i.am/)'s music studio in Los Angeles and can't wait to help others build things at Hack Camp.

**Comment by maxwofford** [comment]
@zachlatta Are there any website changes that need to be done for this?

**Comment by zachlatta** [comment]
Nope!

## 

Zach Latta
Executive Director of hackEDU https://hackedu.us/
http://zachlatta.com
https://github.com/zachlatta
https://twitter.com/zachlatta
