### ISSUE TITLE
Refactor portfolio workshop

### ISSUE THREAD

**Issue by jonleung** [hackedu/hack-camp#199]
Deliverable: edit the HTML workshop and make a PR into the workshops folder in Cohort 4:

https://github.com/hackedu/hack-camp/tree/master/cohort_3/curriculum/workshops/portfolio

**Comment by zachlatta** [comment]
:+1:

I'll make sure to include a clear place for where to put this in the `cohort_4` directory in #204.

**Comment by jonleung** [comment]
This is currently in progress. I finished what the final version will look like ([link](https://github.com/hackedu/hack-camp/blob/cohort_4-portfolio/cohort_4/playbook/workshops/portfolio/README.md)) and will need to make the tutorial that goes step by step tomorrow!

**Comment by jonleung** [comment]
Made significant headway. [Here's the current progress](https://github.com/hackedu/hack-camp/blob/cohort_4-portfolio/cohort_4/playbook/workshops/portfolio/README.md)

**Comment by maxwofford** [comment]
This has been squashed, and is sitting in #271 waiting for merge. Make sure to submit PRs to cohort_4-portfolio-merge

**Comment by maxwofford** [comment]
@jonleung Why was this assigned to me?

**Comment by maxwofford** [comment]
This was closed by #271.
