### ISSUE TITLE
Add Deadline to Website

### ISSUE THREAD

**Issue by jonleung** [hackedu/hack-camp#2]

**Comment by maxwofford** [comment]
Is this deadline for sign-ups?

**Comment by zachlatta** [comment]
I think so

**Comment by maxwofford** [comment]
I thought we were doing rolling admissions with no sign-up deadline @jonleung @zachlatta

**Comment by zachlatta** [comment]
I think that was the original plan, but we decided to impose a deadline to drive applications now.

What if we did "deadline for June 1st cohort is this Saturday (then put the date)" or something like that?
