### ISSUE TITLE
Create hour-by-hour schedule for first day

### ISSUE THREAD

**Issue by zachlatta** [hackedu/hack-camp#203]
Create an hour-by-hour breakdown of the first day of Hack Camp.

Quick outline from our sprint planning session on 07.27.15:
- _Hackers arrive_
- _Galvanize tour_
- _Energizer_
- _Breakfast_
- _Introduction talk_
- _Workshop_
- _Lunch_
- _Energizer_
- _Creating groups_
- _Brainstorming projects_
- _Project time_
- _I have failed circle_
- _Demos_
- _Feedback form_
- _Hack!_

**Comment by zachlatta** [comment]
Can you fill in the times in `cohort_4/playbook/schedule.md` for this?

**Comment by maxwofford** [comment]
Addressed by #241

**Comment by zachlatta** [comment]
Closed by #241.
