### ISSUE TITLE
Email Galvanize about the AC dripping and broken thermostat in Mission Bay

### ISSUE THREAD

**Issue by zachlatta** [hackedu/hack-camp#206]

**Comment by zachlatta** [comment]
Emailed Kat.

**Comment by maxwofford** [comment]
Do you need an image of the water damaged tables?

**Comment by maxwofford** [comment]
@jonleung Will talk to Kat in person (decided at standups today -jul 31).

**Comment by jonleung** [comment]
@zachlatta I just talked to Kat and told her the tables were getting damaged. She seemed to take it seriously, but there were no actionable outcomes from our conversation. I'd still continue to follow up with her.

**Comment by maxwofford** [comment]
Kat was just in mission bay to inspect the A/C. They are calling someone to come in and inspect it, but it sounds like this could take time.

**Comment by maxwofford** [comment]
@zachlatta I think we can safely close this issue.

**Comment by zachlatta** [comment]
:+1:
