### ISSUE TITLE
Create attendance sheet

### ISSUE THREAD

**Issue by zachlatta** [hackedu/hack-camp#207]
Create a sheet for attendance to be kept track of in.

**Comment by maxwofford** [comment]
EDIT: Blocking on #188

@andreadeng Where can I get the most up-to-date list of accepted hackers?

The attendance sheet will be [here](https://docs.google.com/spreadsheets/d/1Em5tUQdm4dXnthtWr4zY4KR9Q6JZMV_Hl2n6G9Ti9Bg/edit#gid=0).

**Comment by zachlatta** [comment]
Two quick things:
1. Perhaps the attendance sheet could be generic and be ready for @gemmabusoni  and the other leaders to add the hacker names to? Would prevent it from blocking on #188.
2. When you create this, can you link it to the `schedule.md` file we have over in https://github.com/hackedu/hack-camp/blob/2ef860cd82ef9dbe64f5dde2eff60e055aef04c0/cohort_4/playbook/schedule.md? It'd be pretty neat to have everything accessible from our markdown playbook.

**Comment by maxwofford** [comment]
@zachlatta Good point. :+1:

**Comment by maxwofford** [comment]
Addressed by #238

**Comment by maxwofford** [comment]
My bad @zachlatta. Didn't mean to assign you :D.

**Comment by zachlatta** [comment]
Should be closed by #238.

**Comment by maxwofford** [comment]
Closed by https://github.com/hackedu/hack-camp/commit/442fbfe341edb727aa5f091941e77d8ef245280d
