### ISSUE TITLE
Create guidelines for managing hacker arrival on the first day

### ISSUE THREAD

**Issue by zachlatta** [hackedu/hack-camp#208]
Create a set of bullet-point guidelines for managing hacker arrival on the first day of camp.

**Comment by maxwofford** [comment]
@zachlatta Let's put this in playbook/activities.md. Just like how all the spacemacs docs are in a single README, I think it would be cool to have all our activities in one place.

**Comment by zachlatta** [comment]
Agreed!

## 

Zach Latta
Executive Director of hackEDU https://hackedu.us
http://zachlatta.com
https://github.com/zachlatta
https://twitter.com/zachlatta

**Comment by zachlatta** [comment]
Created PR #246 for this.
