### ISSUE TITLE
Order breakfast food

### ISSUE THREAD

**Issue by zachlatta** [hackedu/hack-camp#210]
Order enough food for the first week of Hack Camp. I think we already have some of the stuff we need on the 3rd floor of Galvanize.

**Comment by zachlatta** [comment]
Going to hold off on this until a day or two before camp starts, so the bananas stay fresh.

**Comment by zachlatta** [comment]
So I guess you could say this is blocking on time not passing?

**Comment by maxwofford** [comment]
@zachlatta I think you can schedule deliveries with Instacart.

**Comment by jonleung** [comment]
@zachlatta yup, I have scheduled with Instacart before!

**Comment by zachlatta** [comment]
Order placed, delivery later today.

**Comment by zachlatta** [comment]
We found it!
