### ISSUE TITLE
Create guidelines to facilitate project brainstorming on the first day

### ISSUE THREAD

**Issue by zachlatta** [hackedu/hack-camp#220]

**Comment by zachlatta** [comment]
Wait on #208 to see where to put this work.

**Comment by maxwofford** [comment]
Could I get your feedback on #243 @jonleung?

**Comment by jonleung** [comment]
@MaxWofford can you add a task to add the "how to demo" thing that we put together where the facilitators deliberately makes errors when demoing and asks the class how to correct theM?

Once the other document is added, you can link to it in this one.

**Comment by maxwofford** [comment]
@jonleung Did we do that on the 3rd cohort? I'm not sure if demoing the incorrect way is a good use of time on the first day.

**Comment by zachlatta** [comment]
Closed by #243.
