### ISSUE TITLE
Can you make it clear that we can't provide housing?

### ISSUE THREAD

**Issue by jonleung** [hackedu/hack-camp#23]
Something along the lines of:
- we want to try our best to make hack camp great for anyone who comes
- right now it is not in our ability to provide housing

@MaxWofford @zachlatta

**Comment by zachlatta** [comment]
Want to take lead on this?

**Comment by maxwofford** [comment]
@jonleung I'd love to get feedback on the wording in 4d112c0

**Comment by jonleung** [comment]
We really wish we could accommodate out-of-state students with housing, but
unfortunately won't be able this first year.

?

**Comment by maxwofford** [comment]
@jonleung I'm not sure how to respond to that question. Would you please elaborate?

**Comment by MaxWofford** [comment]
test @jonleung

**Comment by MaxWofford** [comment]
test @jonleung

**Comment by MaxWofford** [comment]
test @jonleung

**Comment by jonleung** [comment]
Yo!

**Comment by jonleung** [comment]
What are your thoughts on this phrasing @MaxWofford "We really wish we could accommodate out-of-state students with housing, but unfortunately won't be able this first year."

**Comment by maxwofford** [comment]
:+1: Thanks @jonleung. Amended
