### ISSUE TITLE
Decide if Andrea will be undercover

### ISSUE THREAD

**Issue by zachlatta** [hackedu/hack-camp#237]
We're thinking about having @andreadeng be an undercover hacker this next cohort to get a better understanding of issues (both curricular and social) that hackers run into and to go through the experience herself. She'd pretend to be a hacker with everyone else and the organizers would have to pretend with her.

@gemmabusoni - thoughts?

**Comment by zachlatta** [comment]
I spoke with @gemmabusoni on IRC and she's all for it.

@andreadeng, you are now officially undercover. Please prepare your identity immediately, and do not, under any circumstances, break your cover.

![](https://raw.githubusercontent.com/hackedu/dinosaurs/179949058c452c095b77a4a83604d96977d71eb1/undercover_dinosaurs.png)

**Comment by maxwofford** [comment]
I'd like to take a step back for a moment and realize I'm part of an organization that has not only just decided to disguise one of its members as a high schooler on an entirely open and public discussion thread... it already has a logo for doing so.
