### ISSUE TITLE
Waivers for Cohorts 1, 2, 3

### ISSUE THREAD

**Issue by jonleung** [hackedu/hack-camp#239]
@andreadeng @zachlatta Are the waivers for cohorts 1, 2, and 3 these stored on our Dropbox somewhere? Do we have a waiver for each student? We need to keep these indefinitely for legal reasons.

**Comment by zachlatta** [comment]
Cohort 3's waivers are in `hack_camp/cohort_3_waivers` in the Dropbox.

**Comment by jonleung** [comment]
@zachlatta are these the filled out and signed waivers? They look like unfilled out waivers right now?

**Comment by zachlatta** [comment]
They're filled out.

**Comment by jonleung** [comment]
@zachlatta do we have the waivers from cohorts 1-2 in the Dropbox?

**Comment by zachlatta** [comment]
Not that I know of.

Status on these @andreadeng?

## 

Zach Latta
Executive Director of hackEDU https://hackedu.us
http://zachlatta.com
https://github.com/zachlatta
https://twitter.com/zachlatta

**Comment by zachlatta** [comment]
Pinging @andreadeng again.

**Comment by jonleung** [comment]
@zachlatta, I am closing this issue because:
1. It does not seem like it is going to get resolved
2. It does not seem like we are going to need the waivers in the future

**Comment by jonleung** [comment]
@zachlatta, please re-open this issue if you think we should still try to complete it.
