### ISSUE TITLE
Questions to add to the form

### ISSUE THREAD

**Issue by jonleung** [hackedu/hack-camp#24]
Something along the lines of: 

If you've coded before, can you briefly (3-5 sentences) talk about a project or anything that you've worked on and how it works? My objective is to get to know their coding ability.

Does your school have AP CS?
Have you taken AP CS at your school?

(Knowing if their school had AP cs lets us say we provided this experience to X number of people who wanted to learn to code but didn't have AP CS)

(Knowing whether they took it lets us quickly where their level is)

**Comment by maxwofford** [comment]
Don't we have their school already? Can't we look up access to CS class by their school?

EDIT: Grammar

**Comment by maxwofford** [comment]
@jonleung Asking people to talk about their past projects might be a scary thing for the ones who don't have any past code experience. Maybe this would be better as a mailmerge to only the ones who said they've coded before?

**Comment by jonleung** [comment]
@MaxWofford perhaps we can make the question pop up ONLY if they've coded before. We can ask "Can you tell us about something you've coded before?"

**Comment by maxwofford** [comment]
:+1: this

**Comment by jonleung** [comment]
@zachlatta @MaxWofford can we have this up for this round of applications? (ie the ones that's open now?)

Rewording: "Can you briefly (3-5 sentences) tell us about something you've coded before and how it worked? Don't necessarily try to sound impressive, our goal is to admit beginners. We just want to know where you are so we can best meet your needs!"

**Comment by jonleung** [comment]
@MaxWofford can we also add the questions: "In 2-3 sentences, why do you want to go to hack camp?"

**Comment by maxwofford** [comment]
@jonleung Do you think it is worth the effort to have these questions? Such a long form may discourage people.

**Comment by jonleung** [comment]
Max, I agree, but I think it will be worth it for admitting students. What if we added a middle stage for the application process where we asked these questions? Seems pretty standard.

1) Round 1: General Information
2) Give us more info
3) Admit

@zachlatta  thoughts as well?

**Comment by maxwofford** [comment]
We can def add this to the payment page @zachlatta

**Comment by maxwofford** [comment]
@jonleung was a conclusion reached on this in-person?

**Comment by zachlatta** [comment]
I think we're just gonna find out this information from calls with applicants or add it to the application form.

**Comment by zachlatta** [comment]
Closed by #28.
