### ISSUE TITLE
Idea: Adding IFTTT's Maker Channel to Maestro

### ISSUE THREAD

**Issue by jonleung** [hackedu/hack-camp#242]
@zachlatta I'm thinking of possibly including the IFTTT maker channel into this workshop. I'd love to talk to you and @TheThirdOne about the possibility of integrating the Maker channel into the Maestro API ([link to API](https://ifttt.com/maker)).

I think this would be particularly cool because it vastly expands the capabilities of what a student could do. In addition to text messages and phone calls and gifs, students would be able to:
- Post to Twitter
- On Facebook they can
  - create a status
  - create a link post
  - upload a photo from URL
- Send an Email
- On Github, they can
  - Create an issue
- iOS reminders
  - Add reminder to list
- Send a slack message
## Triggering Actions

Triggerring the above actions is  pretty easy. I wrote [a script](https://gist.github.com/jonleung/691e757f05d1478479fc) that easily let you trigger arbitrary channels in IFTTT using the maker channel.
## Listening for Triggers

However, for IFTTT callbacks (say IFTTT, make a POST request to me anytime someone adds a new photo on Instagram) students using only client side JavaScript will have a hard time figuring out how to receive these callbacks. However, we could definitely do something with Maestro to make receiving these callbacks easier.

---

Thoughts?

**Comment by TheThirdOne** [comment]
It looks like it would be entirely possible to do this in maestro. Though, I'm not sure IFTTT maker is the best way.

**Comment by zachlatta** [comment]
Err, I'm very hesitant about having this sort of dependency.

## 

Zach Latta
Executive Director of hackEDU https://hackedu.us
http://zachlatta.com
https://github.com/zachlatta
https://twitter.com/zachlatta

On Tue, Jul 28, 2015 at 12:50 PM, Benjamin Landers <notifications@github.com

**Comment by zachlatta** [comment]
Also, shouldn't this issue be in the Maestro repository?

**Comment by zachlatta** [comment]
Closing due to being in wrong repository.

**Comment by maxwofford** [comment]
@jonleung Would you like to migrate this issue over?
I think it'd be good if we only close an issue after it has been migrated.

cc/ @zachlatta @TheThirdOne

**Comment by zachlatta** [comment]
Migrated to hackedu/maestro#21.

**Comment by jonleung** [comment]
@zachlatta thanks!
