### ISSUE TITLE
Create guidelines for running a workshop

### ISSUE THREAD

**Issue by maxwofford** [hackedu/hack-camp#262]
This will go into `playbook/activities.md` under the workshops heading.

**Comment by maxwofford** [comment]
I don't know enough about the way workshops are being run this cohort to complete this task yet.

**Comment by zachlatta** [comment]
Perhaps assign to @jonleung instead?

## 

Zach Latta
Executive Director of hackEDU https://hackedu.us
http://zachlatta.com
https://github.com/zachlatta
https://twitter.com/zachlatta

**Comment by jonleung** [comment]
Moved this back to todo because I want to briefly want to think about the introduction talk topics instead

**Comment by jonleung** [comment]
Closing because I decided not to do it because I think that the guidelines in each individual workshop are sufficient.
