### ISSUE TITLE
Create detailed group-forming guidelines

### ISSUE THREAD

**Issue by maxwofford** [hackedu/hack-camp#279]
This is based off feedback from @gemmabusoni that the group-forming guidelines weren't well explained. This will go in `playbook/activities.md`.

**Comment by zachlatta** [comment]
Could this fall under #328?

**Comment by zachlatta** [comment]
16543bfa0be307f409bf31abbf80caec3e49c721 also adds some more info on hacker pairing. Perhaps that would close this?

**Comment by zachlatta** [comment]
Thoughts @gemmabusoni?

**Comment by jonleung** [comment]
Thoughts @ssun098, I believed that you brought this up initially?

**Comment by zachlatta** [comment]
Did #391 help address this?

On Mon, Aug 10, 2015 at 8:48 AM, Jonathan Leung notifications@github.com
wrote:

> Thoughts @ssun098 https://github.com/ssun098, I believed that you
> brought this up initially?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/hackedu/hack-camp/issues/279#issuecomment-129502493.

## 

Zach Latta
hackEDU | zach@hackedu.us

**Comment by jonleung** [comment]
Closing because
- lack of activity
-  there seem to be much higher leverage issues to fix

**Comment by maxwofford** [comment]
![](https://i.imgur.com/8rJqE6b.png)

Fine with this

**Comment by zachlatta** [comment]
As long as I got my coffee, I'm happy.

FRESH POTS. https://www.youtube.com/watch?v=fhdCslFcKFU

On Tue, Aug 18, 2015 at 4:51 PM, Max Wofford notifications@github.com
wrote:

> https://camo.githubusercontent.com/66af3a1708623dbec0646bd2e04a12d6674e4422/68747470733a2f2f692e696d6775722e636f6d2f38724a714536622e706e67
> 
> Fine with this
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/hackedu/hack-camp/issues/279#issuecomment-132393396.

## 

Zach Latta
hackEDU | zach@hackedu.us
