### ISSUE TITLE
Exploring using Github or other tool that lets people easily contribute as PM system.

### ISSUE THREAD

**Issue by jonleung** [hackedu/hack-camp#30]
Willing to experiment with this current system first @zachlatta it feels a little bit difficult for people who are not the PM at the moment to contribute with the way things are currently lined up. Perhaps Org mode is analogous to my spreadsheets, it's where you do your own work but we need some public place like the spreadsheet where the PM is done. Definitely ask about this on your calls but I don't feel comfortable right now not being able to easily access and find things in a familiar format.

**Comment by zachlatta** [comment]
> Perhaps Org mode is analogous to my spreadsheets, it's where you do
> your own work but we need some public place like the spreadsheet where
> the PM is done.

Agreed. Will need to automate exports/making it easier for others to see
stuff. Going to see how others do it at other companies this week during
the calls.

**Comment by maxwofford** [comment]
@zachlatta Any updates on this?

**Comment by zachlatta** [comment]
I believe we figured this out offline. Closing for now, reopen if any objections.
