### ISSUE TITLE
Improve free-form project guidelines to account for when an odd number of people exists or someone shows up or misses a day

### ISSUE THREAD

**Issue by zachlatta** [hackedu/hack-camp#303]

**Comment by zachlatta** [comment]
Hmm, so I was thinking about this and I think this may warrant a group discussion to decide what we should do in this case, before I went ahead and implemented some guidelines.

Here's the current layout I'm thinking. I'd love to hear everyone's thoughts.
- Odd number of people -> one group has three people
- Someone who wasn't present during brainstorming (and therefore not on a team ) shows up -> placed on existing team
- Someone who was present during brainstorming (and has a partner) misses the following day -> one of the leaders works closely without them throughout the day, nearly being a pseudo partner.

/cc @jonleung @MaxWofford @gemmabusoni @ssun098 @andreadeng

**Comment by zachlatta** [comment]
Blocking on not having external confirmation on this.

**Comment by jonleung** [comment]
Thoughts @jonleung @MaxWofford @gemmabusoni @ssun098 @andreadeng?

**Comment by zachlatta** [comment]
Ping?

**Comment by zachlatta** [comment]
Pinging again...

**Comment by zachlatta** [comment]
@jonleung pinging again...

**Comment by maxwofford** [comment]
@zachlatta I'd say go for it for the time being. We can revise the current model once we start testing it in the Labs.

**Comment by jonleung** [comment]
I agree with @MaxWofford's comment above.

**Comment by selynna** [comment]
Looks good! Sorry I was in class

**Comment by zachlatta** [comment]
Cool! Thanks.

I'll get started on this.

**Comment by zachlatta** [comment]
Whoops, accidentally unassigned myself!

**Comment by zachlatta** [comment]
Alright. After reading through this a bit more and reading through the sections of the playbook on project formation and pairing, I'm thinking it doesn't make sense to include this in the playbook, especially considering that we didn't run Hack Camp with these guidelines. Personally, I'd rather have this playbook be a snapshot of Hack Camp than have as much content as possible.

I'm going to close this for now. Let me know if anyone thinks we should reconsider not doing this – happy to reopen and continue discussing.
