### ISSUE TITLE
Record human knot energizer in the playbook.

### ISSUE THREAD

**Issue by jonleung** [hackedu/hack-camp#317]
We did this energizer on August 4th. @ssun098 came up with it and will record it.

**Comment by zachlatta** [comment]
Is there a reason this needs to be recorded vs. written out?

We haven't had much success with recording in the past.

## 

Zach Latta
hackEDU | zach@hackedu.us

**Comment by selynna** [comment]
Finished, so this issue can be closed when merged.

**Comment by zachlatta** [comment]
Awesome! I'll go ahead and review/merge it.

## 

Zach Latta
hackEDU| zach@hackedu.us
