### ISSUE TITLE
Account for when people are running late

### ISSUE THREAD

**Issue by zachlatta** [hackedu/hack-camp#319]

**Comment by zachlatta** [comment]
Hmm, I'm starting to rethink this issue and wonder if it makes sense to actually do this.

@gemmabusoni do you feel like there's enough room in the playbook to use discretion when dealing with edge cases like this?

**Comment by jonleung** [comment]
Closing because
- lack of activity
-  there seem to be much higher leverage issues to fix

**Comment by maxwofford** [comment]
Sounds good!
![](https://s3.amazonaws.com/giphygifs/media/D7Qzw12q9s8Tu/giphy.gif)

**Comment by zachlatta** [comment]
I love that GIF.

On Tue, Aug 18, 2015 at 4:56 PM, Max Wofford notifications@github.com
wrote:

> Sounds good!
> 
> https://camo.githubusercontent.com/f4ea3960c3781314fe614c4b6a4cb9c0b5b72e23/68747470733a2f2f73332e616d617a6f6e6177732e636f6d2f6769706879676966732f6d656469612f4437517a7731327139733854752f67697068792e676966
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/hackedu/hack-camp/issues/319#issuecomment-132394465.

## 

Zach Latta
hackEDU | zach@hackedu.us
