### ISSUE TITLE
Projector is kill

### ISSUE THREAD

**Issue by zachlatta** [hackedu/hack-camp#329]
Our projector is died. Oh no!

Let's get this fixed.

**Comment by zachlatta** [comment]
I'm going to email Kat and Ryan from Galvanize about this.

**Comment by zachlatta** [comment]
I also just received word from @jonleung on IRC that @MaxWofford is going to bring in a VGA cable tomorrow and @ssun098 is going to bring in a DVI cable.

**Comment by zachlatta** [comment]
Emailed them! Waiting on a response now...

**Comment by selynna** [comment]
@zachlatta projector is working well - we took 2 hdmi cables from galvanize

**Comment by zachlatta** [comment]
Awesome to hear! I'll let Galvanize know.

## 

Zach Latta
http://zachlatta.com
https://github.com/zachlatta
https://twitter.com/zachlatta
