### ISSUE TITLE
 Add energizer for pasta + marshmallow to playbook

### ISSUE THREAD

**Issue by maxwofford** [hackedu/hack-camp#350]
This includes prepping for it & anything it will need to be run

**Comment by zachlatta** [comment]
Has this been done?

**Comment by maxwofford** [comment]
Talking to @ssun098 about this. I can take point on this.

**Comment by selynna** [comment]
@MaxWofford do you still need more information on this?

**Comment by maxwofford** [comment]
@ssun098 Is this descriptive enough? #514

**Comment by selynna** [comment]
Yep!

**Comment by maxwofford** [comment]
This is closed by https://github.com/hackedu/hack-camp/commit/faacf3fa6bfcce582c2ee86cb15931d3131ee3e7
