### ISSUE TITLE
Create pairing guidelines

### ISSUE THREAD

**Issue by maxwofford** [hackedu/hack-camp#358]
Create section in playbook on pairing people. This likely includes:
1. Create spreadsheet
2. Manually pair people of "compatible" skill levels
3. Make sure the pairs are different every time

This is assigned to @ssun098

**Comment by selynna** [comment]
@MaxWofford could you add me to this one too?

**Comment by zachlatta** [comment]
Closed by 16543bfa0be307f409bf31abbf80caec3e49c721.
