### ISSUE TITLE
Update demo guidelines to include mock demos

### ISSUE THREAD

**Issue by maxwofford** [hackedu/hack-camp#361]
@hackedu/hack-camp This is currently unassigned. Can anyone pick this up?

In the demo guidelines a leader should do an example demo of something (actually demo a project). Some demo tips can be found here: https://cl.ly/text/0w370t171I2S

**Comment by zachlatta** [comment]
Can you slot in a time to do this in W1D5's schedule?

**Comment by jonleung** [comment]
@gemmabusoni
