### ISSUE TITLE
Create new activity called Morning Announcements after energizers

### ISSUE THREAD

**Issue by maxwofford** [hackedu/hack-camp#363]
This is assigned to @ssun098

The activity should include any feedback from the previous day we're acting on.

**Comment by selynna** [comment]
@MaxWofford could you assign me to this on the sidebar? It'll help me keep my issues slightly more organized.

**Comment by maxwofford** [comment]
There you go @ssun098!

**Comment by zachlatta** [comment]
:+1:

## 

Zach Latta
hackEDU | zach@hackedu.us

**Comment by zachlatta** [comment]
Closed by df88900432de6005c58eb59f7491393509936693.
