### ISSUE TITLE
C9 Workspace Live Reload Glitch

### ISSUE THREAD

**Issue by saescapa** [hackedu/hack-camp#365]
Some workspaces (2) from C9 have a glitch with live reload. The live reload would load a previous version of a file and displaying wrong content. Steps to reproduce: unsure. Steps to fix, force the file to load a complete different code and then re-replace it with original code. Can be fixed easily by copying code, deleting it, reload page and pasting code back.

**Comment by maxwofford** [comment]
@zachlatta Would you please look into this?

**Comment by zachlatta** [comment]
Certainly!

@saescapa any chance I could get steps to reproduce?

**Comment by saescapa** [comment]
@zachlatta unfortunately I don't know how to reproduce this glitch.

**Comment by zachlatta** [comment]
Alright, I'll take a look at it and see what I can do. It'll be more
difficult for me to fix without instructions to reproduce.

On Thu, Aug 6, 2015 at 10:47 AM, Samuel Escapa notifications@github.com
wrote:

> @zachlatta https://github.com/zachlatta unfortunately I don't know how
> to reproduce this glitch.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/hackedu/hack-camp/issues/365#issuecomment-128456828.

## 

## 

Zach Latta
http://zachlatta.com
https://github.com/zachlatta
https://twitter.com/zachlatta

**Comment by saescapa** [comment]
Sometimes, Live Reload would break and completely stop. When Live Reload stops, the hackers can't see their website, they get an error. (http://i.imgur.com/LDPm5cg.jpg). So the hackers would just click on the "Run" button which would initialize an Apache server. It looks like the Apache server for some reason interacts strangely with Live Reload, that prevents it from reloading the updated files.

**Comment by zachlatta** [comment]
Hmm, gotcha. Yeah, the live reload scripts conflicts with Cloud9's Apache
server.

One option may be to create a Cloud9 custom runner for the live reload
script (see https://docs.c9.io/docs/custom-runners).

On Mon, Aug 10, 2015 at 5:26 PM, Samuel Escapa notifications@github.com
wrote:

> Sometimes, Live Reload would break and completely stop. When Live Reload
> stops, the hackers can't see their website, they get an error. (
> http://i.imgur.com/LDPm5cg.jpg). So the hackers would just click on the
> "Run" button which would initialize an Apache server. It looks like the
> Apache server for some reason interacts strangely with Live Reload, that
> prevents it from reloading the updated files.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/hackedu/hack-camp/issues/365#issuecomment-129656205.

## 

Zach Latta
hackEDU | zach@hackedu.us

**Comment by maxwofford** [comment]
@zachlatta Could this be fixed by #497?

**Comment by zachlatta** [comment]
Going to track the creation of the custom runner in #505. That'll close this.

**Comment by zachlatta** [comment]
Hmm, what are everyone's thoughts on just not using the live reload script entirely and having the hackers just manually refresh the page each time? It seems like it may be more trouble than it's worth at this stage.

Also, for me to effectively create a custom Cloud9 runner for this, I'd need to test it by running through existing workshops, which would take a significant amount of time. We also may need to refactor the workshops to use the custom runner if we did it as well.

**Comment by maxwofford** [comment]
@zachlatta I agree. It seems too early to decide to use C9 in all our curriculum anyways.

**Comment by maxwofford** [comment]
@zachlatta Feel free to add a `wontfix` tag and close this + #505 if you want.

**Comment by zachlatta** [comment]
Alright, I'm just going to go ahead and close this issue and leave the current inclusion of the live reload script in the workshops as-is. Let me know if anyone has any objections!
