### ISSUE TITLE
Create energizers for day 4

### ISSUE THREAD

**Issue by maxwofford** [hackedu/hack-camp#372]

**Comment by maxwofford** [comment]
This includes linking the energizers in the agenda.

**Comment by jonleung** [comment]
@MaxWofford, updates on this? I remember that you said that you didn't want to do tasks from the past that are primarily used as documentation for what we have done. What do you think the next steps are @MaxWofford ?

**Comment by maxwofford** [comment]
@jonleung This is sitting in a PR currently. I think it would be okay to finish this after Hack Camp.

**Comment by zachlatta** [comment]
Can you link the PR?

On Mon, Aug 10, 2015 at 9:21 AM, Max Wofford notifications@github.com
wrote:

> @jonleung https://github.com/jonleung This is sitting in a PR
> currently. It is not worth our time to finish it before end of camp.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/hackedu/hack-camp/issues/372#issuecomment-129516302.

## 

Zach Latta
hackEDU | zach@hackedu.us

**Comment by maxwofford** [comment]
@zachlatta I can't find this currently. Perhaps we should revisit this on Monday?

**Comment by zachlatta** [comment]
Any updates on this @MaxWofford?

On Fri, Aug 14, 2015 at 12:53 AM, Max Wofford notifications@github.com
wrote:

> @zachlatta https://github.com/zachlatta I can't find this currently.
> Perhaps we should revisit this on Monday?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/hackedu/hack-camp/issues/372#issuecomment-131010535.

## 

Zach Latta
hackEDU | zach@hackedu.us

**Comment by jonleung** [comment]
Hey! I unsubscribed from this issue. Please tag me again if you want to ping me with anything. Thanks!

**Comment by maxwofford** [comment]
I haven't been able to find the documentation for this, and noone in Hack Camp seems to remember. I'm closing this for now and marking with `wontfix`

**Comment by zachlatta** [comment]
:+1:

On Tue, Aug 25, 2015 at 4:03 PM, Max Wofford notifications@github.com
wrote:

> I haven't been able to find the documentation for this, and noone in Hack
> Camp seems to remember. I'm closing this for now and marking with wontfix
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/hackedu/hack-camp/issues/372#issuecomment-134765838.

## 

Zach Latta
hackEDU | zach@hackedu.us
