### ISSUE TITLE
Create energizers for day 5

### ISSUE THREAD

**Issue by zachlatta** [hackedu/hack-camp#378]

**Comment by zachlatta** [comment]
Do any of you guys remember which energizers we did on Friday?

/cc @gemmabusoni @ssun098 @saescapa

**Comment by zachlatta** [comment]
Ping?

**Comment by maxwofford** [comment]
`we did the marshmallow thing, telephone, and something else`
-- @ssun098

**Comment by zachlatta** [comment]
@gemmabusoni, do you remember what the other energizer we did on Friday was?

On Tue, Aug 18, 2015 at 8:21 PM, Max Wofford notifications@github.com
wrote:

> we did the marshmellow thing, telephone, and something else
> -- @ssun098 https://github.com/ssun098
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/hackedu/hack-camp/issues/378#issuecomment-132431287.

## 

Zach Latta
hackEDU | zach@hackedu.us

**Comment by maxwofford** [comment]
Closed by https://github.com/hackedu/hack-camp/commit/6695213b0875a6355064f711a4729181f8c7d687
