### ISSUE TITLE
Add playbook section for periodic club leader instigated break activities

### ISSUE THREAD

**Issue by maxwofford** [hackedu/hack-camp#384]

**Comment by jonleung** [comment]
Example: "I'm going to play ping pong now, anyone want to join?"

**Comment by maxwofford** [comment]
@jonleung Is that context, or an example?

**Comment by jonleung** [comment]
@MaxWofford edited my comment based on your comment

**Comment by zachlatta** [comment]
Do we still want to do this?

On Mon, Aug 10, 2015 at 10:44 PM, Jonathan Leung notifications@github.com
wrote:

> @MaxWofford https://github.com/MaxWofford addressed
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/hackedu/hack-camp/issues/384#issuecomment-129712164.

## 

Zach Latta
hackEDU | zach@hackedu.us

**Comment by maxwofford** [comment]
Not high leverage right now, but we may want to revisit this Monday.

**Comment by maxwofford** [comment]
This was never revisited. Closing this for now.
