### ISSUE TITLE
Give speech to hackers about how feedback forms make everyone's lives better

### ISSUE THREAD

**Issue by maxwofford** [hackedu/hack-camp#386]

**Comment by zachlatta** [comment]
Should this be added to the playbook?

**Comment by zachlatta** [comment]
A gentle nudge :-).

On Thu, Aug 6, 2015 at 6:45 PM, Max Wofford notifications@github.com
wrote:

> —
> Reply to this email directly or view it on GitHub
> https://github.com/hackedu/hack-camp/issues/386.

## 

Zach Latta
hackEDU | zach@hackedu.us

**Comment by jonleung** [comment]
Closed because @ssun098 did this last week.
