### ISSUE TITLE
Insurance

### ISSUE THREAD

**Issue by jonleung** [hackedu/hack-camp#39]
We need to talk to these guys ASAP: https://www.insurancefornonprofits.org/ to figure out what kind of insurance we need to get!

**Comment by zachlatta** [comment]
Insurance for our employees? For our participants?

**Comment by maxwofford** [comment]
@jonleung Any updates on this?

**Comment by jonleung** [comment]
No? I thought we needed insurance for the things. I thought you did
research on this and said we didn't @zachlatta?
ᐧ

**Comment by zachlatta** [comment]
We only need insurance for directors and officers, which we can get later.

**Comment by jonleung** [comment]
@zachlatta, when's later?
ᐧ

—
Sent from my mobile–apologies for brevity and any typos!

hackedu.us | 610-761-0083

**Comment by zachlatta** [comment]
Probably once we have a board & officers set up. The only insurance we'd go after is for the directors and officers.
