### ISSUE TITLE
Ask Students for Media Release and Health Forms

### ISSUE THREAD

**Issue by jonleung** [hackedu/hack-camp#40]
http://cl.ly/322v0K23443h
http://cl.ly/2S2v0Q1m1k18
http://cl.ly/413X0q190c1w

**Comment by maxwofford** [comment]
@jonleung @zachlatta If we've received these from our first cohort, let's close this.

**Comment by zachlatta** [comment]
Good call.

**Comment by jonleung** [comment]
@andreadeng (ignore this now, this is for later), can you scan and document
these digitally in the Google Drive in a new folder?
ᐧ

**Comment by zachlatta** [comment]
What if we actually did this in the Hack Camp folder in our Dropbox?
It'd be great if we could keep our Google Drive usage to a minimum
because it doesn't have a Linux client.

**Comment by jonleung** [comment]
ᐧ

**Comment by zachlatta** [comment]
Very insightful reply, @jonleung :-P.

**Comment by jonleung** [comment]
Sounds good.

## 

—
Sent from my mobile–apologies for brevity and any typos!

hackedu.us | 610-761-0083
