### ISSUE TITLE
Buy new milk and cereal

### ISSUE THREAD

**Issue by maxwofford** [hackedu/hack-camp#403]

**Comment by maxwofford** [comment]
Will hold off on this until Sunday so the food stays good.

**Comment by maxwofford** [comment]
It is now Sunday. I will get the food when the store opens...

![](https://raw.githubusercontent.com/hackedu/dinosaurs/master/restaurant_dinosaur.png)

**Comment by zachlatta** [comment]
Where are you headed to? Safeway is 24 hours and relatively cheap.

**Comment by maxwofford** [comment]
@zachlatta Thanks! Looks like I'll be headed there.

**Comment by zachlatta** [comment]
Awesome! Sounds good.

On Sun, Aug 9, 2015 at 1:36 PM, Max Wofford notifications@github.com
wrote:

> @zachlatta https://github.com/zachlatta Thanks! Looks like I'll be
> headed there.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/hackedu/hack-camp/issues/403#issuecomment-129236090.

## 

Zach Latta
hackEDU | zach@hackedu.us

**Comment by maxwofford** [comment]
@zachlatta Did we need almond milk, soy, or dairy?

**Comment by zachlatta** [comment]
Not that I know of. @jonleung?

On Sun, Aug 9, 2015 at 1:40 PM, Max Wofford notifications@github.com
wrote:

> @zachlatta https://github.com/zachlatta Did we need almond milk, soy,
> or dairy?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/hackedu/hack-camp/issues/403#issuecomment-129236278.

## 

Zach Latta
hackEDU | zach@hackedu.us

**Comment by maxwofford** [comment]
Got both soy and dairy.

**Comment by maxwofford** [comment]
I'll close this when I bring them to Galvanize.

**Comment by zachlatta** [comment]
Awesome, sounds good.

On Sun, Aug 9, 2015 at 2:42 PM, Max Wofford notifications@github.com
wrote:

> I'll close this when I bring them to Galvanize.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/hackedu/hack-camp/issues/403#issuecomment-129244030.

## 

Zach Latta
hackEDU | zach@hackedu.us

**Comment by maxwofford** [comment]
I take that back. The issue says `buy`, so I'll close this.
