### ISSUE TITLE
Create 3 new energizers and link schedule for day 6

### ISSUE THREAD

**Issue by maxwofford** [hackedu/hack-camp#404]

**Comment by maxwofford** [comment]
@gemmabusoni What can I do to help this get done?

**Comment by maxwofford** [comment]
Because energizers have already happened in the morning, I vote we close the issue once #421 is closed.

**Comment by zachlatta** [comment]
I'm partial towards adding them to the playbook before closing. I think
it's very important that we document all of our work, since we only have
one shot at cohort 4.

On Mon, Aug 10, 2015 at 12:10 PM, Max Wofford notifications@github.com
wrote:

> Because energizers have already happened in the morning, I vote we close
> the issue once #421 https://github.com/hackedu/hack-camp/pull/421 is
> closed.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/hackedu/hack-camp/issues/404#issuecomment-129569602.

## 

Zach Latta
hackEDU | zach@hackedu.us

**Comment by maxwofford** [comment]
@zachlatta Sounds good. It seems like documentation for the playbook is not part of prepping for the cohort 4 day 6. I'm going to remove it from the milestone for now.

**Comment by zachlatta** [comment]
Sounds good! Apologies for the delay.

On Mon, Aug 10, 2015 at 12:35 PM, Max Wofford notifications@github.com
wrote:

> @zachlatta https://github.com/zachlatta Sounds good. It seems like
> documentation for the playbook is not part of prepping for the cohort 4 day
> 6. I'm going to remove it from the milestone for now.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/hackedu/hack-camp/issues/404#issuecomment-129577711.

## 

Zach Latta
hackEDU | zach@hackedu.us

**Comment by maxwofford** [comment]
@gemmabusoni What energizers did we run this day?

**Comment by maxwofford** [comment]
Chatting with @ssun098 about this right now. I can take point.

**Comment by maxwofford** [comment]
We did musical chairs, and human octopus on this day.

human octopus: partners link arms and touch backs and try to stand

**Comment by jonleung** [comment]
@MaxWofford any updates on this?

**Comment by jonleung** [comment]
Ah I see, this is waiting on a merge from @zachlatta.

**Comment by maxwofford** [comment]
@jonleung If you are available to review/merge the PR, feel free to assign yourself
