### ISSUE TITLE
Add advanced-to-beginner pairing guidelines to playbook

### ISSUE THREAD

**Issue by maxwofford** [hackedu/hack-camp#408]

**Comment by maxwofford** [comment]
Assigning `blocking` tag while awaiting merge

**Comment by zachlatta** [comment]
Left a couple comments. Assigning back to you...

On Sun, Aug 9, 2015 at 4:58 AM, Max Wofford notifications@github.com
wrote:

> Assigning blocking tag while awaiting merge
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/hackedu/hack-camp/issues/408#issuecomment-129171024.

## 

Zach Latta
hackEDU | zach@hackedu.us

**Comment by zachlatta** [comment]
The pull request, that is.

On Sun, Aug 9, 2015 at 1:17 PM, Zach Latta zach@hackedu.us wrote:

> Left a couple comments. Assigning back to you...
> 
> On Sun, Aug 9, 2015 at 4:58 AM, Max Wofford notifications@github.com
> wrote:
> 
> > Assigning blocking tag while awaiting merge
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/hackedu/hack-camp/issues/408#issuecomment-129171024.
> 
> ## 
> 
> Zach Latta
> hackEDU | zach@hackedu.us

## 

Zach Latta
hackEDU | zach@hackedu.us

**Comment by maxwofford** [comment]
@zachlatta Made the changes to #411
