### ISSUE TITLE
Talk with Gisela

### ISSUE THREAD

**Issue by selynna** [hackedu/hack-camp#413]
Getting insight as to how she teaches beginners

**Comment by selynna** [comment]
Wait uh how do i assign multiple people

**Comment by zachlatta** [comment]
You can't. Only one assignee per issue on GitHub :-).

On Sun, Aug 9, 2015 at 1:53 PM, Selynna Sun notifications@github.com
wrote:

> Wait uh how do i assign multiple people
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/hackedu/hack-camp/issues/413#issuecomment-129239316.

## 

Zach Latta
hackEDU | zach@hackedu.us

**Comment by saescapa** [comment]
So who is assigned to this? All of us?

**Comment by selynna** [comment]
@gemmabusoni

**Comment by gemmabusoni** [comment]
Taking place after lunch today.

**Comment by zachlatta** [comment]
Did this happen?

**Comment by saescapa** [comment]
Yes, we forgot to close it.

**Comment by saescapa** [comment]
Gemma has talked to Gisela. Closed.

**Comment by zachlatta** [comment]
Any insights @gemmabusoni?

On Tue, Aug 11, 2015 at 11:58 AM, Samuel Escapa notifications@github.com
wrote:

> Closed #413 https://github.com/hackedu/hack-camp/issues/413.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/hackedu/hack-camp/issues/413#event-379521932.

## 

Zach Latta
hackEDU | zach@hackedu.us
