### ISSUE TITLE
Link to brainstorming section is broken

### ISSUE THREAD

**Issue by zachlatta** [hackedu/hack-camp#416]
The link to the brainstorming section in https://github.com/hackedu/hack-camp/blob/schedule-for-cohort-4-day-6/cohort_4/playbook/ACTIVITIES.md#freeform-projects is broken.

**Comment by maxwofford** [comment]
Just tested the link. There is no `brainstorming` heading anywhere in the document anymore.

**Comment by zachlatta** [comment]
Yeah. I think the new one is #project-formation or something along those
lines.

On Sun, Aug 9, 2015 at 7:32 PM, Max Wofford notifications@github.com
wrote:

> Just tested the link. There is no brainstorming heading anywhere in the
> document anymore.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/hackedu/hack-camp/issues/416#issuecomment-129283331.

## 

Zach Latta
hackEDU | zach@hackedu.us
