### ISSUE TITLE
Send all Hack Camp applicants an email updating them

### ISSUE THREAD

**Issue by zachlatta** [hackedu/hack-camp#418]
We've yet to update all of the Hack Camp applicants. We need to write and send an email to all of them letting them know we've accepted all cohorts and that if we didn't accept them this year, we encourage them to apply to join hackEDU at our website and hopefully will see them next Hack Camp (or something along those lines).

**Comment by jonleung** [comment]
@zachlatta do you want to take this task?

**Comment by zachlatta** [comment]
Done!

Sent it out. If you have access to our email transparency Google Group, here's a link to it https://groups.google.com/forum/#!topic/hackedu-emails/SyTC0lILetc.
