### ISSUE TITLE
Send nightly diffs of the playbook to leaders

### ISSUE THREAD

**Issue by zachlatta** [hackedu/hack-camp#424]
@MaxWofford want to work together and set up a cron job of sorts for this?

**Comment by zachlatta** [comment]
Or we could manually write out changelogs each night and email them.

**Comment by maxwofford** [comment]
I'll take point on sending these out.

**Comment by zachlatta** [comment]
Can we close this?

**Comment by maxwofford** [comment]
Yep! Don't think this is needed anymore.
