### ISSUE TITLE
Decide on 3 energizers 

### ISSUE THREAD

**Issue by maxwofford** [hackedu/hack-camp#426]
I think the actionable thing here is for @gemmabusoni to write a comment that includes the 3 energizers being run tomorrow.

**Comment by gemmabusoni** [comment]
2 Truths and a Lie http://www.icebreakers.ws/small-group/two-truths-and-a-lie.html

Duck, Duck, Goose

Card on Your Head - One hacker is given a card (realistically, a sticky note) with a noun written on it (duck, cat, Kung Fury, Zach Latta, etc.); said hacker cannot read the card and must stick it to their forehead. The other hackers must then do their best to describe the noun, while the hacker with the card on their head guesses at what's written on it. In case of big groups, divide the hackers into two groups.

**Comment by maxwofford** [comment]
@gemmabusoni Thanks for this!
