### ISSUE TITLE
Messenger workshop finalization

### ISSUE THREAD

**Issue by maxwofford** [hackedu/hack-camp#427]
The final step to this is merging #420

**Comment by jonleung** [comment]
Done https://github.com/hackedu/hack-camp/tree/squashed_messenger

**Comment by maxwofford** [comment]
@jonleung Shouldn't #420 be merged first?  Reopening for the time being.

EDIT: meant #432

**Comment by jonleung** [comment]
@MaxWofford, do you mean #432 ?

**Comment by maxwofford** [comment]
@jonleung Yep! My bad. Just edited the comment.

**Comment by maxwofford** [comment]
This was closed by #432. Thanks @jonleung!
