### ISSUE TITLE
Send out email with changelog

### ISSUE THREAD

**Issue by maxwofford** [hackedu/hack-camp#429]

**Comment by maxwofford** [comment]
This will have to be done after all the other issues are closed.

**Comment by maxwofford** [comment]
My bad^ 

Thought I was in another issue

**Comment by maxwofford** [comment]
We did it!

**Comment by zachlatta** [comment]
go team!

:shipit:

On Tue, Aug 11, 2015 at 3:52 AM, Max Wofford notifications@github.com
wrote:

> We did it!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/hackedu/hack-camp/issues/429#issuecomment-129834392.

## 

Zach Latta
hackEDU | zach@hackedu.us
