### ISSUE TITLE
Schedule a call with Schoozilla guy for metrics

### ISSUE THREAD

**Issue by jonleung** [hackedu/hack-camp#44]

**Comment by zachlatta** [comment]
With whom?

**Comment by zachlatta** [comment]
As in with whom from the team?

**Comment by zachlatta** [comment]
Is this still relevant?

**Comment by zachlatta** [comment]
Closing for now due to lack of responses.

**Comment by jonleung** [comment]
I don't know, you told me to make an issue to ask him about how to do metrics!

**Comment by maxwofford** [comment]
@jonleung @zachlatta Let's leave this closed until there is an actionable objective to the issue. We'll still get notifications of comments on closed issues.

**Comment by zachlatta** [comment]
@jonleung who should the call with him be with? You? Me? Max? Andrea?
