### ISSUE TITLE
Student Onboarding

### ISSUE THREAD

**Issue by jonleung** [hackedu/hack-camp#45]
These are things to communicate with parents and students.

Make sure they both know this information (i.e. perhaps email them)
- [x] **Forms** SUNDAY
  - [x] Waiver
  - [x] Health Form
    - [x] Make sure this asks for allergies / food restrictions
  - [x] Media Release Form
- [x] **Send Information to Students**
      - [x] *_Link Pre-Program Questionnaire_ - ask @andreadeng
  - [x] **Times**
    - [x] Start time 9:20am, please arrive on time
    - [x] End time 4:30
    - [x] You are encouraged to stay afterwards to Hack
  - [x] **Food**
    - [x] Breakfast will be provided
    - [x] We're encouraging you to pack lunch because there will be very limited time during class.
- [x] **Things to Bring**
  - [ ] Laptop
  - [x] Charger
  - [ ] Writing Implement
  - [x] Notebook
  - [x] Lunch
- [ ] **Timing**
  - [x] Remind people that it starts at 9:20am - 4:20pm
- [x] **First Day**
  - [x] Meet at Galvanize, 44 Tehama Street
  - [ ] Just drop off the kids

**Comment by zachlatta** [comment]
Sent acceptance email with all this.

**Comment by zachlatta** [comment]
Hmm, GitHub is having trouble checking off the checkboxes. Don't worry that they're not all checked off.
![recorded](https://cloud.githubusercontent.com/assets/992248/7901668/a9a9dc3a-0748-11e5-9b4c-4ddf1ae8c6af.gif)
