### ISSUE TITLE
Decide on 3 energizers for cohort 4 day 8

### ISSUE THREAD

**Issue by maxwofford** [hackedu/hack-camp#455]
I think the actionable thing here is for @ssun098  to write a comment that includes the 3 energizers being run tomorrow.

**Comment by selynna** [comment]
Duck duck goose (originally for 8/11 but we didn't do it)

Can it! - Have participants sit in a circle with their feet extended. Place a can on the foot of one of the participants. The object is to move the can around the circle without touching the can with your hands or having it fall. The can must be on at least one foot of each participant. We could also do this as a competition between 2 groups.

Systems game: walking around a designated space (room, field, lot), everyone secretly chooses two people, and try to remain exactly in between both of them.

**Comment by maxwofford** [comment]
Thanks @ssun098 !
