### ISSUE TITLE
Make sure orbit demo is shown

### ISSUE THREAD

**Issue by maxwofford** [hackedu/hack-camp#458]
@ssun098 Feel free to pint @jonleung if this is not clear.

**Comment by selynna** [comment]
@MaxWofford can i close this?

**Comment by maxwofford** [comment]
@ssun098 Go right ahead!

**Comment by zachlatta** [comment]
Should we add this to the playbook?

On Wed, Aug 12, 2015 at 9:59 PM, Selynna Sun notifications@github.com
wrote:

> Closed #458 https://github.com/hackedu/hack-camp/issues/458.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/hackedu/hack-camp/issues/458#event-381069184.

## 

Zach Latta
hackEDU | zach@hackedu.us

**Comment by selynna** [comment]
Sure, that would be a good idea.  ALthough stress that it doesn't
necessarily have to be the orbit demo if you're referencing that
specifically.
