### ISSUE TITLE
Send An email acknowledging that we got someone's application immediately after they apply.

### ISSUE THREAD

**Issue by jonleung** [hackedu/hack-camp#46]
Whenever someone applies, automatically send them an email that's like, "Hey, we got your application, we're doing admissions on a rolling basis. We'll get back to you by at least 2 weeks before the cohort starts, let us know if you need to know earlier.

Please feel free to reach out for questions.

If it's helpful, it's easy to write a script in Google Scripts so that when you receive a form, it can make a post request somewhere (but it's probably jsut eaiser to do this in AJAX on a e.onClick event and don't prevent callback.

**Comment by maxwofford** [comment]
This seems to work when I tested it on my own form:

``` js
function onFormSubmit(e) {
    var apiKey = 'YOUR API KEY';
    var mailgunServer = 'YOUR MAILGUN SERVER';
    var to = findResponse('First and last name') + ' <' + findResponse('Email') + '>';
    var from = 'Hack Camp Team <summer@hackedu.us>';
    var subject = 'Hack Camp applicaiton received - ' + findResponse('First and last name');
    var message = 'Hey ' + findResponse('First and last name') + ', your application to Hack Camp has just been received. We\'ll get back to you within x days';
    var url = 'https://api.mailgun.net/v3/' + mailgunServer + '/messages';
    var payload = {
        'from': from,
        'to': to,
        'subject': subject,
        'text': message
    };
    var headers = {
        'Authorization': 'Basic ' + Utilities.base64Encode(apiKey)
    }
    var options = {
        'method': 'POST',
        'headers': headers,
        'payload': payload,
        'muteHttpExceptions': false
    };
    var response = UrlFetchApp.fetch(url, options);
}

function findResponse (namedValue) {
    var formResponses = FormApp.getActiveForm().getResponses();
    var formResponse = formResponses[formResponses.length-1];
    var itemResponses = formResponse.getItemResponses();
    for (var j = 0; j < itemResponses.length; j++) {
        var itemResponse = itemResponses[j];
        if (itemResponse.getItem().getTitle() === namedValue)
            return itemResponse.getResponse();
    }
}
```

@andreadeng @jonleung What message would be good to send them?

**Comment by jonleung** [comment]
ᐧ
@andreadeng, I'll defer to you!

**Comment by andreadeng** [comment]
Hi [Name of applicant],

We have received your application and will look over it carefully. We are doing admissions on a rolling basis and will get back to you by at least 2 weeks before the cohort starts. Let us know if you need to be notified earlier. Please feel free to reach out to us with questions!

Best,
[Sender Name]

**Comment by andreadeng** [comment]
Hi Hacker,

We have received your application and will look over it carefully. We are doing admissions on a rolling basis and will get back to you by at least 2 weeks before the cohort starts. Let us know if you need to be notified earlier. Please feel free to reach out to us with questions!

Best,
hackEDU Team

**Comment by maxwofford** [comment]
We're live:
![screenshot 2015-07-09 at 3 28 47 pm](https://cloud.githubusercontent.com/assets/5891442/8608387/514dfa0a-264f-11e5-875b-68e45ab3da1b.png)

**Comment by zachlatta** [comment]
I'll send a few small wording changes in a bit.

**Comment by maxwofford** [comment]
@zachlatta You can make changes [here](https://script.google.com/macros/d/MdzQ1ey8oJtgIX6iWbbnHsPDp8aFBtR4M/edit?uiv=2&mid=ACjPJvFcI2Q9PdeiSYdsRn2SICrDyWmrTlEs9-LB7ZARB6_cUIV4ThC8biTAELAzO39IXDCrpr6H1jH_6PHli2KIa2qSLh0gPYbk6PnPE3MozInVO7_mrKXRLR1AxneF0c70BsLAsEBxo4U)

**Comment by zachlatta** [comment]
Awesome! Went ahead and changed the text around a bit.
