### ISSUE TITLE
Write a section in the Playbook that explains about how one might address hacker disruptiveness

### ISSUE THREAD

**Issue by jonleung** [hackedu/hack-camp#463]
Send this guide to @gemmabusoni @ssun098, and @saescapa to read over and give feedback.

Make sure to add this into the schedule as well.

**Comment by maxwofford** [comment]
This is addressed by #463

@jonleung Said he was going to bed right now, so I will remove this from the milestone.

**Comment by zachlatta** [comment]
@MaxWofford did you mean to link to this issue?

**Comment by maxwofford** [comment]
well... closing #463 would certainly address the issue brought up by #463

**Comment by maxwofford** [comment]
@zachlatta I think I meant to put #419

**Comment by zachlatta** [comment]
Update: during today's standups @jonleung said he had the work for this
done and just needs to submit a pull request.

On Tue, Aug 18, 2015 at 4:25 PM, Max Wofford notifications@github.com
wrote:

> @zachlatta https://github.com/zachlatta I think I meant to put #419
> https://github.com/hackedu/hack-camp/pull/419
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/hackedu/hack-camp/issues/463#issuecomment-132389638.

## 

Zach Latta
hackEDU | zach@hackedu.us

**Comment by jonleung** [comment]
@zachlatta @MaxWofford, I've made the appropriate edits and squashed my commits in #441 and assigned @zachlatta to the PR.
