### ISSUE TITLE
Send out summary email for cohort 4 day 8

### ISSUE THREAD

**Issue by maxwofford** [hackedu/hack-camp#465]
This should include [schedule](https://github.com/hackedu/hack-camp/issues/453), the section on [hacker disruption](https://github.com/hackedu/hack-camp/issues/463), and the [feedback form](https://github.com/hackedu/hack-camp/issues/464).

EDIT: grammar

**Comment by maxwofford** [comment]
This is blocking on the https://github.com/hackedu/hack-camp/milestones/Cohort%204%20Day%208

**Comment by maxwofford** [comment]
I'm headed to bed, and will send out the email right now.

**Comment by maxwofford** [comment]
This email has been sent out.

**Comment by zachlatta** [comment]
Alright, I failed at getting the feedback form in.

Will do it ASAP.
