### ISSUE TITLE
Update post-mordem guidelines in playbook

### ISSUE THREAD

**Issue by maxwofford** [hackedu/hack-camp#466]
This includes adding how discussion times work and that whoever is taking point on the meeting must take point on recording issues on GitHub.

**Comment by maxwofford** [comment]
Closing this issue because post-mordem guidelines won't be used after Hack Camp. @jonleung Objections?

**Comment by zachlatta** [comment]
I'd actually be partial towards doing this for the sake of recording as
much as possible. I'm happy to take point on this.

Is the flow of the meeting as follows? Please correct any mistakes.
1. Go through each item in the schedule and if anyone has anything they
   want done for the following day, they bring it up. This is only for
   discussing actionables. If someone wants to discuss something, they should
   bring up that they want to discuss it and the person leading the meeting
   should table that topic to discuss at the end of the meeting.
2. Once all items in the schedule have been gone through, review the entire
   task list with the team and have team members volunteer themselves for each
   task.
3. Once all the tasks have been assigned and everyone's happy with the
   list, go through each discussion topic brought up and discuss it until an
   outcome is reached or it's decided to table the discussion for another time.

On Mon, Aug 17, 2015 at 5:15 PM, Max Wofford notifications@github.com
wrote:

> Closed #466 https://github.com/hackedu/hack-camp/issues/466.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/hackedu/hack-camp/issues/466#event-384816982.

## 

Zach Latta
hackEDU | zach@hackedu.us

**Comment by maxwofford** [comment]
@zachlatta Small detail:
Play upbeat music very quietly (instrumental/tropical house is best).

**Comment by zachlatta** [comment]
Was that part of the meeting flow? I personally found it kind of
distracting when you did that.

On Mon, Aug 17, 2015 at 6:35 PM, Max Wofford notifications@github.com
wrote:

> @zachlatta https://github.com/zachlatta Small detail:
> Play upbeat music very quietly (instrumental/tropical house is best).
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/hackedu/hack-camp/issues/466#issuecomment-132022974.

## 

Zach Latta
hackEDU | zach@hackedu.us

**Comment by maxwofford** [comment]
The feedback I got from @gemmabusoni was the music was distracting when I turned it on mid-meeting. When the meeting started with the music on, it helped keep people energized.

EDIT: Sorry if you found it distracting! I'll be aware of that next time.

**Comment by zachlatta** [comment]
Alright, in that case I'm fine with moving forward.

I still personally found it distracting.

On Mon, Aug 24, 2015 at 12:36 AM, Max Wofford notifications@github.com
wrote:

> The feedback I got from @gemmabusoni https://github.com/gemmabusoni was
> the music was distracting when I turned it on mid-meeting. When the meeting
> started with the music on, it helped keep people energized.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/hackedu/hack-camp/issues/466#issuecomment-134073212.

## 

Zach Latta
hackEDU | zach@hackedu.us
