### ISSUE TITLE
Document 3 energizers for cohort 4 day 9

### ISSUE THREAD

**Issue by maxwofford** [hackedu/hack-camp#469]
@ssun098 Feel free to comment with the energizers here!

**Comment by selynna** [comment]
Systems game: walking around a designated space (room, field, lot), everyone secretly chooses two people, and try to remain exactly in between both of them.

Pulse Race: in two lines, holding hands. Everyone has eyes closed except leader of each line. A beach ball or other object is placed at opposite end of lines from leaders. Facilitator stands by leaders and flips a coin. If tails, do nothing. If heads, leaders start pulse race by squeezing hand of person next to them, which sets off chain reaction. When last person in line feels hand squeezed, he/she may open eyes and grab for beach ball. Whichever team gets ball first each round gets a point. After each round, leader goes to end of line.

Telephone (if somehow we don't have enough- we've been doing 2 energizers a day for the past 2-3 days)

**Comment by selynna** [comment]
apparently we're doing mafia after lunch

Source: http://www.wikihow.com/Play-Mafia
