### ISSUE TITLE
Automatically set up LiveReload with Cloud9

### ISSUE THREAD

**Issue by zachlatta** [hackedu/hack-camp#47]
Create a script that sets up LiveReload with Cloud9.

**Comment by maxwofford** [comment]
Cloud9 can generate a workspace based on a github repo. Maybe have a script that adds itself to .bashrc on its first run, and pulls from github. That way we can include whatever we want in a repo and have students computers auto-update whenever they reload them.

**Comment by maxwofford** [comment]
@zachlatta is this finished?

**Comment by zachlatta** [comment]
Still gotta add it to the repo, has some issues...

**Comment by zachlatta** [comment]
(minor changes I need to make before adding it here)

**Comment by maxwofford** [comment]
@zachlatta Updates on this?

**Comment by jonleung** [comment]
@zachlatta updates on this?

**Comment by zachlatta** [comment]
Just need to get to working on this, I'm a bit backlogged right now (ohgodemailswhy).

**Comment by zachlatta** [comment]
Alright, it works!

The commit that closed this issue has the script itself. Here's a one-liner for installing and running the script (specifically from that commit, the script won't get the latest version):

```
$ curl -sL https://git.io/vtbp6 > /tmp/live_reload && chmod +x /tmp/live_reload && /tmp/live_reload
```
