### ISSUE TITLE
Review todo workshop and submit fixes

### ISSUE THREAD

**Issue by maxwofford** [hackedu/hack-camp#471]
@gemmabusoni You can find the workshop in https://github.com/hackedu/hack-camp/tree/master/cohort_4/playbook/workshops/todo

**Comment by zachlatta** [comment]
What's the status on this?

On Wed, Aug 12, 2015 at 6:12 PM, Max Wofford notifications@github.com
wrote:

> @gemmabusoni https://github.com/gemmabusoni You can find the workshop
> in
> https://github.com/hackedu/hack-camp/tree/master/cohort_4/playbook/workshops/todo
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/hackedu/hack-camp/issues/471.

## 

Zach Latta
hackEDU | zach@hackedu.us

**Comment by zachlatta** [comment]
Going to close this due to lack of progress.
