### ISSUE TITLE
Accept 6 applicants for cohort 2

### ISSUE THREAD

**Issue by zachlatta** [hackedu/hack-camp#48]
- 4 beginners, no coding experience
- 2 some experience, not finished a project

**Comment by maxwofford** [comment]
Oops, wrong button :V

**Comment by maxwofford** [comment]
@zachlatta Can we close this?

**Comment by zachlatta** [comment]
Not yet - need to confirm that all is done for this.

**Comment by zachlatta** [comment]
Okay three are paid, two we are yet to confirm, need to call and accept one more.

**Comment by zachlatta** [comment]
Called and accepted one more. Deadline is noon tomorrow for the others.

**Comment by zachlatta** [comment]
Gotta tell people who didn't confirm yet that they lost their spots and then send an email accepting Sam.

**Comment by zachlatta** [comment]
Ended up only accepting 5.
