### ISSUE TITLE
Add day 8 and 9 energizers to playbook

### ISSUE THREAD

**Issue by zachlatta** [hackedu/hack-camp#481]
- https://github.com/hackedu/hack-camp/issues/455
- https://github.com/hackedu/hack-camp/issues/469

**Comment by maxwofford** [comment]
@zachlatta Any updates on documenting this?

**Comment by zachlatta** [comment]
Still need to get to this, I'm going to order the ZenHub so it reflects my
queue.

On Mon, Aug 17, 2015 at 4:59 PM, Max Wofford notifications@github.com
wrote:

> @zachlatta https://github.com/zachlatta Any updates on documenting this?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/hackedu/hack-camp/issues/481#issuecomment-131998515.

## 

Zach Latta
hackEDU | zach@hackedu.us

**Comment by maxwofford** [comment]
This didn't close for some reason. It was addressed by 98b4e11e9a7cb8dfc5da7e3c487a9c1d3749cf06

**Comment by zachlatta** [comment]
I don't believe the branch https://github.com/hackedu/hack-camp/commit/98b4e11e9a7cb8dfc5da7e3c487a9c1d3749cf06 is on made it to master, which would prevent it from closing this issue. Still waiting on the PR to be closed.

**Comment by maxwofford** [comment]
@zachlatta Ah, my bad
