### ISSUE TITLE
Cohort 4 day 10 energizers

### ISSUE THREAD

**Issue by maxwofford** [hackedu/hack-camp#483]
/cc @gemmabusoni @ssun098

**Comment by maxwofford** [comment]
@ssun098 What energizers did we run on the last day?

**Comment by selynna** [comment]
@MaxWofford mafia both times

**Comment by maxwofford** [comment]
@ssun098 Thanks!

**Comment by maxwofford** [comment]
Closed by https://github.com/hackedu/hack-camp/commit/8b044bde84ca129893759d7d5693dbed5f80bc0e
