### ISSUE TITLE
Acquire ice cream

### ISSUE THREAD

**Issue by maxwofford** [hackedu/hack-camp#488]
![](http://www.littlebabysicecream.com/wp-content/uploads/2014/06/Little-Babys-Ice-Cream-This-Is-A-Special-Time-Video-Still.jpg)

**Comment by selynna** [comment]
![dino ice cream](https://cloud.githubusercontent.com/assets/7741746/9267675/96787550-4207-11e5-9ee8-43e3bbc25abe.png)

**Comment by maxwofford** [comment]
This was aquired
