### ISSUE TITLE
Add feedback form in every workshop

### ISSUE THREAD

**Issue by maxwofford** [hackedu/hack-camp#493]

**Comment by jonleung** [comment]
Closing because I am choosing not to do this until we have finalized the workshops.

**Comment by maxwofford** [comment]
@jonleung Won't we need to do this for the Labs program? Would putting it in the icebox work for the time being?

**Comment by jonleung** [comment]
@MaxWofford, putting this issue in the icebox is a good idea! I've went ahead and put this issue in the icebox and reopened the issue.

**Comment by jonleung** [comment]
I transferred this issue to the hackedu repo because this task needs to be done for the club playbook and not the hack camp playbook.

See: https://github.com/hackedu/hackedu/issues/80
