### ISSUE TITLE
Obtain testimonials from Hack Camp organizers

### ISSUE THREAD

**Issue by jonleung** [hackedu/hack-camp#494]
Hack Camp organizers seemed to have an awesome time. Getting and sharing their testimonials will probably be very impactful for donors and would be a great marketing resource to convince future Hack Camp organizers (and perhaps club leaders) to apply.

Here are the steps that I foresee:
- [ ] Write the questions
- [ ] Send the questions to @gemmabusoni @ssun098 @saescapa 
- [ ] Each organizer then answers the questions
  - [ ] @gemmabusoni 
  - [ ] @ssun098 
  - [ ] @saescapa

**Comment by zachlatta** [comment]
Want to take point on this?

**Comment by maxwofford** [comment]
This seems like it might take time away from setting up the Labs program. What if we set up a follow-up-then for this?

**Comment by jonleung** [comment]
@MaxWofford, I'll see if I can quickly do this.

**Comment by jonleung** [comment]
@zachlatta I took point.

**Comment by maxwofford** [comment]
@jonleung Updates on this? If it still has to be done, what if we sent a followupthen for this?

**Comment by jonleung** [comment]
@MaxWofford I agree this may take time away from setting up for the labs program. I, however, think it is still important. The longer we wait to do this, the more organizers will forget their experience. So, my thoughts are to leave it in backlog, and if we get to it, we'll get to it.

**Comment by maxwofford** [comment]
@jonleung Have we been consistent with following up on issues in our backlog?

Sending a followupthen is something that will trigger us to revisit it at a relevant time.

**Comment by jonleung** [comment]
@MaxWofford, feel free to send a Follow Up Then. I have also made a note in my own personal task management system. I also think that we should leave this issue in the backlog. But, if you feel strongly about it, feel free to close it or perform any action you think is appropriate. Thanks!

**Comment by zachlatta** [comment]
I'm happy to take lead on asking @gemmabusoni, @ssun098, and @saescapa
these. @jonleung if you send me a list of questions, I can get on a call
with them and ask them. @hellyeah may also be a good person to do this.

If you feel strongly that this is important, I don't mind dedicated about
an hour of our time to get this done.

On Thu, Aug 20, 2015 at 8:59 AM, Jonathan Leung notifications@github.com
wrote:

> @MaxWofford https://github.com/MaxWofford, feel free to send a Follow
> Up Then. I have also made a note in my own personal task management system.
> I also think that we should leave this issue in the backlog. But, if you
> feel strongly about it, feel free to close it or perform any action you
> think is appropriate. Thanks!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/hackedu/hack-camp/issues/494#issuecomment-133060087.

## 

Zach Latta
hackEDU | zach@hackedu.us

**Comment by hellyeah** [comment]
I think it would only make sense for me to do this, if we're going to get them to write their testimonials on the Medium publication. I'm very down for that though. Let me know.

**Comment by jonleung** [comment]
@hellyeah, I would be totally down you to take lead on this!

Not sure if it's helpful but [here are a list of questions](https://docs.google.com/forms/d/1k6c83s5m1EMEkoKI-VeIhSkwjq_GqHoM91MKkCg6JKQ/viewform) I made to prompt Hack Camp organizers for testimonials.

/cc @zachlatta

**Comment by zachlatta** [comment]
Down with having @hellyeah take this!

**Comment by hellyeah** [comment]
I'm not sure what timeline makes sense here, but it does seem time-sensitive in that we want them to reflect on this now.

Would next week be too late to hop on calls with all of them about writing these posts?

**Comment by zachlatta** [comment]
I don't think it'd be too late, but we should get it on the calendar now.

On Thu, Aug 20, 2015 at 2:48 PM, David Fontenot notifications@github.com
wrote:

> cool. i'm not sure what timeline makes sense here, but it does seem
> time-sensitive in that we want them to reflect on this now.
> 
> would next week be too late to hop on calls with all of them about writing
> these posts?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/hackedu/hack-camp/issues/494#issuecomment-133187822.

## 

Zach Latta
hackEDU | zach@hackedu.us

**Comment by zachlatta** [comment]
I'm happy to take point on this.

On Thu, Aug 20, 2015 at 3:07 PM, Zach Latta <zach@hackedu.us> wrote:

> I don't think it'd be too late, but we should get it on the calendar now.
>
> On Thu, Aug 20, 2015 at 2:48 PM, David Fontenot <notifications@github.com>
> wrote:
>
>> cool. i'm not sure what timeline makes sense here, but it does seem
>> time-sensitive in that we want them to reflect on this now.
>>
>> would next week be too late to hop on calls with all of them about
>> writing these posts?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/hackedu/hack-camp/issues/494#issuecomment-133187822>.
>>
>
>
>
> --
> Zach Latta
> hackEDU | zach@hackedu.us
>



-- 
Zach Latta
hackEDU | zach@hackedu.us

**Comment by maxwofford** [comment]
@zachlatta @hellyeah I don't see these calls on the calendar. Is this still actively planned? If not, is it still an effective use of time?

**Comment by zachlatta** [comment]
I just reached out to @gemmabusoni, @saescapa, and @ssun098 about
scheduling a time tomorrow for this.

On Sat, Aug 22, 2015 at 10:39 AM, Max Wofford notifications@github.com
wrote:

> @zachlatta https://github.com/zachlatta @hellyeah
> https://github.com/hellyeah I don't see these calls on the calendar. Is
> this still actively planned? If not, is it still an effective use of time?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/hackedu/hack-camp/issues/494#issuecomment-133730796.

## 

Zach Latta
hackEDU | zach@hackedu.us

**Comment by jonleung** [comment]
:+1:

**Comment by zachlatta** [comment]
Alright, I'm taking calls with the following people:
- [x] @ssun098 
- [x] @gemmabusoni 
- [x] @saescapa 

(checked box means I had a call with them)

**Comment by jonleung** [comment]
:+1:

**Comment by zachlatta** [comment]
Was briefly on the phone @gemmabusoni last night. She's going to write up responses and then send them my way.

**Comment by zachlatta** [comment]
I pinged @gemmabusoni, @ssun098, and @saescapa on IRC and Messenger to see if it'd be okay if I shared their testimonials in this repo anonymously.

**Comment by zachlatta** [comment]
Alright, they're all cool with it. Going to create a PR to add this.
