### ISSUE TITLE
Get hacker projects on to shipped.hackedu.us

### ISSUE THREAD

**Issue by jonleung** [hackedu/hack-camp#495]
Currently http://shipped.hackedu.us/
- does not have that many projects listed
- does not contain projects that are reflective of what beginner hackers could do.

I've had people tell me they actually visit this page so I think it would be valuable to have more projects on there (because we tell people we have 1,300 hackers). It would also be nice if they are representative of what a beginner could do.

I would like to propose the following:
- [ ] email each hacker asking them to add their project
- [ ] posting in each facebook group and tagging each hacker to submit their project

**Comment by maxwofford** [comment]
@jonleung Could I get your feedback on this for a fb post?

---

Hey everyone! Now that Hack Camp is over it would be awesome for you to show off your projects. We've built a site to let you display your projects and would really appreciate it if you could add your projects.
https://shipped.hackedu.us/

**Comment by jonleung** [comment]
@MaxWofford It sounds like you're asking them to do a favor for us and that it won't be beneficial for them. One thing that I've found helpful to convince someone to do something is to is make clear the value for that person.

**Comment by maxwofford** [comment]
@jonleung How's this:

---

Hey everyone! The best part of my first hackathon was finishing it. After working on [Shibay](https://dogelabs.github.io/shibay/) for so long, I got to show it off by putting it online. Even though my project didn't work, putting it somewhere 'out in the world' was really rewarding. I'd like to invite you to do the same by showing off your projects from Hack Camp at https://shipped.hackedu.us/.

**Comment by selynna** [comment]
@MaxWofford @jonleung wouldn't it still be better to say that we'd appreciate them doing so, in addition to the other stuff? I think we should be stressing that it is valuable for both them and us, and not just them.

**Comment by zachlatta** [comment]
What if we messaged them individually to get them to do this? I feel like this may be more effective in a one-on-one context.

**Comment by maxwofford** [comment]
I agree @zachlatta, I'll get on this today.

**Comment by selynna** [comment]
@MaxWofford would you like me to help out with doing so?

**Comment by maxwofford** [comment]
@ssun098 That would be awesome! Who would you like to reach out to?

**Comment by maxwofford** [comment]
Messaging everyone individually for cohort 4 right now.
EDIT: Doing the same for cohort 2 right now.
EDIT: Now cohort 1
EDIT: Going to cohort 3 now.

**Comment by MaxWofford** [comment]
Doing the same for cohort 2 right now.

**Comment by maxwofford** [comment]
@ssun098: You're a hacker too! Feel free to upload any of your projects at https://shipped.hackedu.us

**Comment by maxwofford** [comment]
Just contacted all the cohorts. 

![](http://cdn.meme.am/instances/57298678.jpg)

**Comment by jonleung** [comment]
@MaxWofford :+1:

**Comment by zachlatta** [comment]
Sweet, thanks @MaxWofford!

Can we close this?

On Wed, Aug 19, 2015 at 7:27 PM, Jonathan Leung notifications@github.com
wrote:

> @MaxWofford https://github.com/MaxWofford [image: :+1:]
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/hackedu/hack-camp/issues/495#issuecomment-132857371.

## 

Zach Latta
hackEDU | zach@hackedu.us

**Comment by maxwofford** [comment]
@zachlatta I closed this because the actionable task (reaching out to all the hackers) was finished.

**Comment by zachlatta** [comment]
👍

## 

Zach Latta
hackEDU| zach@hackedu.us
