### ISSUE TITLE
Send reminders to team about post program surveys for Hack Camp

### ISSUE THREAD

**Issue by jonleung** [hackedu/hack-camp#496]
One of the things that All Star Code did was continue to follow up with hackers after their summer program ended. This allowed them to know what lasting effect the program had on the hackers.

Here are some potential things we could measure in the hackers
- number of hackathons attended
- number of projects shipped
- something softer that asks if they've been coding
- what are you currently doing because you attended Hack Camp?

We may consider capturing this data at these time intervals:
- 1 month from now (aligns with our Logan grant update)
- 6 months from now
- and 1 year from now

EDIT by @maxwofford: The actionable of this issue has become to send a follow up email to ourselves at each of the time intervals.

**Comment by maxwofford** [comment]
Perhaps the actionable things for this are to send reminders to ourselves 1 month, 6 months, and 12 months in the future?

**Comment by zachlatta** [comment]
If our #1 objective for this next semester is to run the labs program and
get the club playbook to the point where we're confident starting new clubs
with it, I'm not sure if it makes sense to do this as well.

I agree that it'd certainly be nice to do this sort of follow up with our
hackers from the summer, but I'm worried that our time could be better
spent elsewhere. Thoughts @hellyeah?

On Mon, Aug 17, 2015 at 4:58 PM, Max Wofford notifications@github.com
wrote:

> Perhaps the actionable things for this are to send reminders to ourselves
> 1 month, 6 months, and 12 months in the future?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/hackedu/hack-camp/issues/496#issuecomment-131998364.

## 

Zach Latta
hackEDU | zach@hackedu.us

**Comment by maxwofford** [comment]
@jonleung Perhaps the actionable thing right now that gives us the most free bandwidth this week is to send 3 follow-up-thens: in 1 month, 6 months, and 12 months in the future.

**Comment by jonleung** [comment]
@MaxWofford this sounds good! Do you want to take lead on this?

**Comment by maxwofford** [comment]
@jonleung Sending the email right now. They will go to jonathan@hackedu.us

**Comment by maxwofford** [comment]
These reminders were sent.

**Comment by zachlatta** [comment]
@MaxWofford, @gemmabusoni: has everyone filled out the post-program
questionnaires yet?

On Tue, Aug 18, 2015 at 5:54 PM, Max Wofford notifications@github.com
wrote:

> Closed #496 https://github.com/hackedu/hack-camp/issues/496.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/hackedu/hack-camp/issues/496#event-385989128.

## 

Zach Latta
hackEDU | zach@hackedu.us

**Comment by zachlatta** [comment]
Ignore my previous comment... misread the issue.
