### ISSUE TITLE
Add a line to kill apache before running livereload script

### ISSUE THREAD

**Issue by jonleung** [hackedu/hack-camp#497]
Before trying to start the live_reload server

We can run this code first which pre-emptively kills any apache processes: https://gist.github.com/gmmorris/796400

before trying to start he live_reload.

Killing the apache server is important because it will block the live_reload from running on the right port otherwise if it is running.

**Comment by maxwofford** [comment]
@zachlatta Thoughts?

**Comment by zachlatta** [comment]
This sounds dangerous.

What if we make a custom Cloud9 runner for the live reload script (so they
can start the live reload script by clicking the green run button) instead?

On Mon, Aug 17, 2015 at 4:56 PM, Max Wofford notifications@github.com
wrote:

> @zachlatta https://github.com/zachlatta Thoughts?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/hackedu/hack-camp/issues/497#issuecomment-131998205.

## 

Zach Latta
hackEDU | zach@hackedu.us

**Comment by maxwofford** [comment]
@zachlatta Just curious, can this be done by the end of this week?

**Comment by maxwofford** [comment]
@zachlatta Also, if killing apache is bad, it's probably okay to close this issue.

**Comment by zachlatta** [comment]
I think I can finish this by the end of this week, if I work hard. I'll
close this issue for now and focus on the runner. Tracking that in #505.

On Mon, Aug 17, 2015 at 5:28 PM, Max Wofford notifications@github.com
wrote:

> @zachlatta https://github.com/zachlatta Also, if killing apache is bad,
> it's probably okay to close this issue.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/hackedu/hack-camp/issues/497#issuecomment-132004089.

## 

Zach Latta
hackEDU | zach@hackedu.us
