### ISSUE TITLE
todo list allows arbitrary html in task

### ISSUE THREAD

**Issue by ad510** [hackedu/hack-camp#517]
The todo workshop's main.js has this line in it:

```
span.innerHTML = description;
```

Did you really want to let the user add arbitrary HTML in the todo list? If you want the task input to be plain text, you can do this instead:

```
span.appendChild(document.createTextNode(description));
```

**Comment by jonleung** [comment]
Thanks @ad510! Thanks for bringing it up! This seems like a serious security vulnerability!

I think that this might be a bit complex for beginners. Perhaps we could add a note at the end of the workshop. If you would like to add a note at the end of the workshop, that could be really helpful!

Would you like to submit a pull request?

**Comment by zachlatta** [comment]
So this is an interesting topic. This is an XSS vulnerability. Are we okay
teaching people to create XSS vulnerabilities on their site?

On Sat, Aug 22, 2015 at 11:00 AM, Jonathan Leung notifications@github.com
wrote:

> Thanks @ad510 https://github.com/ad510! Thanks for bringing it up! This
> seems like a serious security vulnerability!
> 
> I think that this might be a bit complex for beginners. Perhaps we could
> add a note at the end of the workshop. If you would like to add a note at
> the end of the workshop, that could be really helpful!
> 
> Would you like to submit a pull request?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/hackedu/hack-camp/issues/517#issuecomment-133736016.

## 

Zach Latta
hackEDU | zach@hackedu.us

**Comment by ad510** [comment]
I can either change how it sets the task description throughout the entire workshop (at 27 places, which isn't hard), or add a note explaining what XSS is and how to fix it. I'd imagine it's better to just fix the code so we don't have to explain XSS vulnerabilities, right?

If the line is too complex, it's easy to split up into 2 lines like this:

```
var spanText = document.createTextNode(description);
span.appendChild(spanText);
```

Do you prefer the 1 line or 2 line version?

**Comment by jonleung** [comment]
@ad510, the two line version sounds good!

Also, could you add a short explanation of why this step is necessary the first time it is used?

**Comment by ad510** [comment]
Hmm, I already submitted a pull request with the 1 line version.

I don't think this is a matter of having an extra step or not, since that is the only place in the todo workshop that uses innerHTML. The first time this is introduced, it looks like this:

```
//=======================================
// Making the <span> tag

var span = document.createElement("span");
//         ^ this function will output us a <span></span> element

// which we need to set the text of to the TASK NAME
span.appendChild(document.createTextNode("TASK NAME"));
// which means that the <span> will now look like this:
// <span>TASK NAME</span>

li.appendChild(span);
/* The <li> tag now looks like this:
    <li>
        <span>TASK NAME</span>
    </li>

    And so the <ul> tag that the <li> tag is in now looks like this:
      <ul id="todo-list">
        <li>
          <span>TASK NAME</span>
        </li>
      </ul>
*/
```

Does that work for you?

Though I'm now noticing that the instagram and messenger workshops have the same problem. I'll update the pull request to fix that and use the 2 line version there.

**Comment by jonleung** [comment]
@ad510, I think a beginner would view

``` js
span.appendChild(document.createTextNode("TASK NAME"));
```

as confusing.

Any chance you could break it up into two lines and briefly explain what each of those lines are doing?

Thanks!

**Comment by zachlatta** [comment]
I'd personally opt for `document.innerHTML=""` and point out the XSS issue.

On Sat, Aug 22, 2015 at 4:14 PM, Jonathan Leung notifications@github.com
wrote:

> @ad510 https://github.com/ad510, I think a beginner would view
> 
> span.appendChild(document.createTextNode("TASK NAME"));
> 
> as confusing.
> 
> Any chance you could break it up into two lines and briefly explain what
> each of those lines are doing?
> 
> Thanks!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/hackedu/hack-camp/issues/517#issuecomment-133763676.

## 

Zach Latta
hackEDU | zach@hackedu.us

**Comment by ad510** [comment]
Sorry for the unresponsiveness. I was using this as a way to procrastinate on doing job applications, which I really should be focusing on for the next few days. I should have time to finish this later this week.

**Comment by zachlatta** [comment]
No worries! Good luck on the applications!

On Mon, Aug 24, 2015 at 10:59 PM, Andrew Downing notifications@github.com
wrote:

> Sorry for the unresponsiveness. I was using this as a way to procrastinate
> on doing job applications, which I really should be focusing on for the
> next few days. I should have time to finish this later this week.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/hackedu/hack-camp/issues/517#issuecomment-134489612.

## 

Zach Latta
hackEDU | zach@hackedu.us

**Comment by jonleung** [comment]
@ad510, no rush! Good luck!

**Comment by maxwofford** [comment]
Actually @jonleung Considering I'm taking point on #498 and packing for BM, timing is important for this.

**Comment by jonleung** [comment]
@MaxWofford, we don't need to fix this issue now. It's ok if it's done later. Let's not put pressure on @ad510 because we won't be using the fixes for quite a while.
