### ISSUE TITLE
Clear out food in 3rd floor kitchen of Galvanize

### ISSUE THREAD

**Issue by zachlatta** [hackedu/hack-camp#520]

**Comment by jonleung** [comment]
@zachlatta, they're hackEDU's snacks. I eat the oatmeal every other day. Thoughts on throwing out the food that is bad and keeping the ones that are good for snacks?

**Comment by jonleung** [comment]
I will move forward by removing all food that cannot be kept as snacks.

**Comment by jonleung** [comment]
This is essentially done. I left some snacks in the cabinet.

**Comment by maxwofford** [comment]
Awesome! Thanks @jonleung

**Comment by zachlatta** [comment]
Did you remove the sign from the 5th floor?

On Wed, Aug 26, 2015 at 8:15 PM, Max Wofford notifications@github.com
wrote:

> Awesome! Thanks @jonleung https://github.com/jonleung
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/hackedu/hack-camp/issues/520#issuecomment-135270984.

## 

Zach Latta
hackEDU | zach@hackedu.us

**Comment by maxwofford** [comment]
Just checked- there was no sign.

**Comment by zachlatta** [comment]
Awesome.

On Thu, Aug 27, 2015 at 9:31 AM, Max Wofford notifications@github.com
wrote:

> Just checked- there was no sign.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/hackedu/hack-camp/issues/520#issuecomment-135485964.

## 

Zach Latta
hackEDU | zach@hackedu.us
