### ISSUE TITLE
Remove hackEDU food from 5th floor kitchen in Galvanize

### ISSUE THREAD

**Issue by zachlatta** [hackedu/hack-camp#521]
To the right of the leftmost fridge on the 5th floor we have a label for hackEDU food. I don't think it's currently use.

**Comment by jonleung** [comment]
**EDIT**: Ignore this comment:

> @zachlatta, they're hackEDU's snacks. I eat the oatmeal every other day. Thoughts on throwing out the food that is bad and keeping the ones that are good for snacks?

**Comment by jonleung** [comment]
@zachlatta, oops, I misread! I'll take care of the 5th floor food area!

**Comment by jonleung** [comment]
I've completed this issue.
