### ISSUE TITLE
Figure out staffing and financials for 2016

### ISSUE THREAD

**Issue by zachlatta** [hackedu/hack-camp#540]
Who is going to run the camp? Will we pay them? How much? How much money do we need to make to pay our staff? How much do we need to charge attendees?

We should figure out good answers to all of these and then launch our website.

**Comment by maxwofford** [comment]
@zachlatta Where does this need to be documented for us to close this?

**Comment by zachlatta** [comment]
I'll create a sheet in the main Hack Camp spreadsheet with the staffing
info once I have stuff finalized. Currently waiting on @gemmabusoni and
@hardmath123 to get back to me with whether they're interested and their
availability.

On Wed, Apr 27, 2016 at 9:05 AM, Max Wofford notifications@github.com
wrote:

> @zachlatta https://github.com/zachlatta Where does this need to be
> documented for us to close this?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/hackclub/hackcamp/issues/540#issuecomment-215132516

## 

Zach Latta
https://zachlatta.com http://zachlatta.com

**Comment by maxwofford** [comment]
@zachlatta I'm going to assign myself to this. I'll move the spreadsheet we worked on in our call today into the Hack Club drive and ping you on updates from @gemmabusoni and @hardmath123 in the Sunday Hack Camp call.

**Comment by maxwofford** [comment]
Just added financials to the Hack Club drive in https://docs.google.com/spreadsheets/d/1H8yp8XIfT6K2cBCMSQqU_j2FEhEFpOR-DVMraI9OziE/edit#gid=2099788275.

**Comment by zachlatta** [comment]
Max, you're the best.
