### ISSUE TITLE
Landing page for 2016

### ISSUE THREAD

**Issue by zachlatta** [hackedu/hack-camp#541]
Create a website to market 2016. Here's our website for 2015:

![screencapture-camp-hackclub-com-1461099855929](https://cloud.githubusercontent.com/assets/992248/14655544/a0571d02-0637-11e6-953a-1fc58c835f4c.png)

Any ideas for what we should do for 2016?

/cc @jkwok91 @MaxWofford @ssun098

**Comment by maxwofford** [comment]
@hackclub/staff What problems were there with the 2015 website? (Not saying we should keep it, I'd just like to start thinking about how to do better this time)

**Comment by zachlatta** [comment]
I thought last year's website was great, no major complaints. We're going
to be charging more for the camp this time around, so we'll want to make it
look a bit more "professional" (spend more time on getting the copy right,
maybe have less colors like orange).

I did not like Unrejector though. I thought that was a huge pain to manage
and would love to use some sort of alternative solution this time around.

On Tue, Apr 19, 2016 at 8:26 PM, Max Wofford notifications@github.com
wrote:

> @hackclub/staff https://github.com/orgs/hackclub/teams/staff What
> problems were there with the 2015 website? (Not saying we should keep it,
> I'd just like to start thinking about how to do better this time)
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/hackclub/hack-camp/issues/541#issuecomment-212237127

## 

Zach Latta
https://zachlatta.com http://zachlatta.com

**Comment by maxwofford** [comment]
> I did not like Unrejector though.

![that is a very good point](https://media.giphy.com/media/xzMs8O1KQh17i/giphy.gif)

How about we use a database this year.

**Comment by zachlatta** [comment]
You have no idea how much you made me laugh.

I'll get back to you on this.

On Wed, Apr 20, 2016 at 11:25 AM, Max Wofford notifications@github.com
wrote:

> I did not like Unrejector though.
> 
> [image: that is a very good point]
> https://camo.githubusercontent.com/58cb5b77738e2285bc39991ee44b3c6cee386d6b/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f787a4d73384f314b51683137692f67697068792e676966
> 
> How about we use a database this year.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/hackclub/hack-camp/issues/541#issuecomment-212545551

## 

Zach Latta
https://zachlatta.com http://zachlatta.com

**Comment by zachlatta** [comment]
Yeah, let's use a database this year. Or something like Wufoo.

Re: website, do you think you could get started on this, Max? Would be
great to launch and start marketing next week.

On Thu, Apr 21, 2016 at 6:10 PM, Zach Latta zach@zachlatta.com wrote:

> You have no idea how much you made me laugh.
> 
> I'll get back to you on this.
> 
> On Wed, Apr 20, 2016 at 11:25 AM, Max Wofford notifications@github.com
> wrote:
> 
> > I did not like Unrejector though.
> > 
> > [image: that is a very good point]
> > https://camo.githubusercontent.com/58cb5b77738e2285bc39991ee44b3c6cee386d6b/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f787a4d73384f314b51683137692f67697068792e676966
> > 
> > How about we use a database this year.
> > 
> > —
> > You are receiving this because you authored the thread.
> > Reply to this email directly or view it on GitHub
> > https://github.com/hackclub/hack-camp/issues/541#issuecomment-212545551
> 
> ## 
> 
> Zach Latta
> https://zachlatta.com http://zachlatta.com

## 

Zach Latta
https://zachlatta.com http://zachlatta.com

**Comment by maxwofford** [comment]
Happy to. Will update when I get a draft done.

**Comment by zachlatta** [comment]
:raised_hands:

On Fri, Apr 22, 2016 at 4:05 AM, Max Wofford notifications@github.com
wrote:

> Happy to. Will update when I get a draft done.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/hackclub/hack-camp/issues/541#issuecomment-213381379

## 

Zach Latta
https://zachlatta.com http://zachlatta.com

**Comment by maxwofford** [comment]
@hackclub/staff I've just set up a branch for the new site in #542. Any comments or feedback is much appreciated.

Here's a screencap of the current version (as of this post):
![shot-20160423-19139-1afxrqi](https://cloud.githubusercontent.com/assets/5891442/14763833/68df4e76-0970-11e6-9939-f4d2a5250d2d.png)

**Comment by maxwofford** [comment]
@hackclub/staff I have to get to work on a few other things (school) for the rest of today. Will finish this site up based on your comments and converted to something with a backend on Sunday (earliest).

**Comment by zachlatta** [comment]
I like where you're going with this. Some comments:
- The header needs more contrast. It's really difficult to read.
- We need wording to indicate that we're running four two-week cohorts
- I'm confused by the red boxes near the bottom
- We should highlight feedback, projects (maybe), and testimonials from
  last year
- More photos!
- Location information – we should make it clear that it's gonna happen in
  San Francisco

I'll hand it over to @jkwok91 to give much more detailed feedback.

On Sat, Apr 23, 2016 at 1:47 PM, Max Wofford notifications@github.com
wrote:

> @hackclub/staff https://github.com/orgs/hackclub/teams/staff I have to
> get to work on a few other things (school) for the rest of today. Will
> finish this site up based on your comments and converted to something with
> a backend on Sunday (earliest).
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/hackclub/hackcamp/issues/541#issuecomment-213829572

## 

Zach Latta
https://zachlatta.com http://zachlatta.com

**Comment by maxwofford** [comment]
Going to add a new issue for the application page and payment processing. This issue is now just to track the landing page.

**Comment by maxwofford** [comment]
Application page and payment processing is tracked by https://github.com/hackclub/hackcamp/issues/543.

**Comment by maxwofford** [comment]
(I'm doing this because the landing page can be sent out early with info on it without blocking on the application page)

**Comment by zachlatta** [comment]
Sounds great, when can we get the landing page out by? I'd like to start
marketing ASAP.

On Mon, Apr 25, 2016 at 7:21 PM, Max Wofford notifications@github.com
wrote:

> (I'm doing this because the landing page can be sent out early with info
> on it without blocking on the application page)
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/hackclub/hackcamp/issues/541#issuecomment-214587283

## 

Zach Latta
https://zachlatta.com http://zachlatta.com

**Comment by zachlatta** [comment]
Sounds fantastic.

On Mon, Apr 25, 2016 at 7:20 PM, Max Wofford notifications@github.com
wrote:

> Going to add a new issue for the application page and payment processing.
> This issue is now just to track the landing page.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/hackclub/hackcamp/issues/541#issuecomment-214587105

## 

Zach Latta
https://zachlatta.com http://zachlatta.com

**Comment by maxwofford** [comment]
@zachlatta current ETA is by eod

**Comment by KrishMunot** [comment]
Hey @MaxWofford! I would love to look at the website. Also, it would be really cool if you did make the website every year opensource and part of the hackclub repos.

**Comment by maxwofford** [comment]
@KrishMunot Thanks! There's a screenshot of the current version of the site [over here](https://github.com/hackclub/hackcamp/issues/541#issuecomment-213825678). You can find the code for the 2016 website in #542. The previous website is in the [gh-pages branch](https://github.com/hackclub/hackcamp/tree/gh-pages).

**Comment by maxwofford** [comment]
We're live! https://camp.hackclub.com

**Comment by maxwofford** [comment]
![to the moon](https://cloud.githubusercontent.com/assets/5891442/14898072/e821370e-0d52-11e6-89d6-5f34132af557.gif)
