### ISSUE TITLE
Application for 2016 camp

### ISSUE THREAD

**Issue by maxwofford** [hackedu/hack-camp#543]

**Comment by zachlatta** [comment]
This is done, right? I remember you sending a link on the Slack.

On Mon, Apr 25, 2016 at 7:20 PM, Max Wofford notifications@github.com
wrote:

> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/hackclub/hackcamp/issues/543

## 

Zach Latta
Hack Club | zach@hackclub.com

**Comment by maxwofford** [comment]
The Google form is done, but it still needs an html form in front of it

**Comment by maxwofford** [comment]
This is finished. I'll close the issue once #541 is live

**Comment by zachlatta** [comment]
:ok_hand:

On Wed, Apr 27, 2016 at 8:54 AM, Max Wofford notifications@github.com
wrote:

> This is finished. I'll close the issue once #541
> https://github.com/hackclub/hackcamp/issues/541 is live
> 
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> https://github.com/hackclub/hackcamp/issues/543#issuecomment-215128971

## 

Zach Latta
https://zachlatta.com http://zachlatta.com

**Comment by maxwofford** [comment]
We're live! https://camp.hackclub.com/application.html

**Comment by maxwofford** [comment]
![yes](https://media.giphy.com/media/aWRWTF27ilPzy/giphy.gif)
