### ISSUE TITLE
Secure a venue

### ISSUE THREAD

**Issue by zachlatta** [hackedu/hack-camp#544]
Just what it sounds like.

**Comment by zachlatta** [comment]
Current goal:
- [ ] ~~Reach out to 5 venues by the end of Tuesday, April 26th (ideally with warm intros)~~
- [ ] ~~Get 5 venues to the "in talks" stage in [the spreadsheet](https://docs.google.com/spreadsheets/d/1HCh5YtN_Y3JXbIMoiUdv-FgYiPZZD1kGg5QnfbsxiCw/edit#gid=0) by the end of this Sunday, May 1st.~~

_Updated by @MaxWofford. See next comment._

**Comment by maxwofford** [comment]
Goal updates from our [call](https://gist.github.com/MaxWofford/d84f2950c9f011373fabca8d94c97660):
- [x] Reach out to 10 venues by Tuesday, May 3rd (@zachlatta)
- [x] 15 potential venues added to [the list](https://docs.google.com/spreadsheets/d/1HCh5YtN_Y3JXbIMoiUdv-FgYiPZZD1kGg5QnfbsxiCw) (@MaxWofford)

**Comment by maxwofford** [comment]
@zachlatta I've just added 15 locations to the list with the criteria that they look big enough to support an extra ~25 people  for Hack Camp. If you want more locations or a stricter selection filter, just tell me!

**Comment by KrishMunot** [comment]
@MaxWofford: Do we need to track the progress of this issue or has it been resolved?

**Comment by zachlatta** [comment]
We still have a good amount of work to do. I'll be keeping this issue updated.

**Comment by zachlatta** [comment]
Venue goal for this week is tracked in #610.

**Comment by maxwofford** [comment]
We have Teespring's warehouse confirmed for first cohort!

**Comment by maxwofford** [comment]
Thanks @zachlatta!
