### ISSUE TITLE
Lock in a time for weekly staff meetings

### ISSUE THREAD

**Issue by zachlatta** [hackedu/hack-camp#547]
We're going to have weekly meetings between all staff members to keep people updated and continuously set objectives for camp preparation.

This issue is to track the creation of that call.

**Comment by maxwofford** [comment]
The calls will be on Sunday at 1pm PST.

A calendar invite went out to anyone who voiced interest in slack.

**Comment by zachlatta** [comment]
:ok_hand:

On Wed, Apr 27, 2016 at 8:59 AM, Max Wofford notifications@github.com
wrote:

> The calls will be on Sunday at 1pm PST.
> 
> A calendar invite went out to anyone who voiced interest in slack.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/hackclub/hackcamp/issues/547#issuecomment-215130413

## 

Zach Latta
https://zachlatta.com http://zachlatta.com
