### ISSUE TITLE
Drive 15 applications by 05.01.16

### ISSUE THREAD

**Issue by zachlatta** [hackedu/hack-camp#548]
Immediately after we launch (#546), we're going to want to do a heavy push to drive applications. We want to hit 15 by 05.01.16 (this Sunday).

**Comment by KrishMunot** [comment]
@zachlatta Please update the status of this issue. Are we on target?

**Comment by maxwofford** [comment]
@KrishMunot We're currently at 10 signups.

**Comment by maxwofford** [comment]
Closing because the deadline was yesterday.

**Comment by maxwofford** [comment]
The new goal is https://github.com/hackclub/hackcamp/issues/575
