### ISSUE TITLE
hack.camp

### ISSUE THREAD

**Issue by maxwofford** [hackedu/hack-camp#549]
We should get hack.camp as our domain.

**Comment by zachlatta** [comment]
Taken :-(.

On Wed, Apr 27, 2016 at 7:38 PM, Max Wofford notifications@github.com
wrote:

> We should get hack.camp as our domain.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/hackclub/hackcamp/issues/549

## 

Zach Latta
Hack Club | zach@hackclub.com

**Comment by maxwofford** [comment]
:(

**Comment by KrishMunot** [comment]
Can we ask Mike Swift to give us the domain maybe?

**Comment by zachlatta** [comment]
Oh, that's interesting. You're right, @KrishMunot. It's actually
@theycallmeswift that owns the domain. Small world.

On Tue, May 3, 2016 at 6:05 AM, Krish Munot notifications@github.com
wrote:

> Can we ask Mike Swift to give us the domain maybe?
> 
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> https://github.com/hackclub/hackcamp/issues/549#issuecomment-216520489

## 

Zach Latta
https://zachlatta.com http://zachlatta.com

**Comment by maxwofford** [comment]
Wait, that's amazing

**Comment by theycallmeswift** [comment]
I do own Hack.camp haha.  Sadly I do already have plans for it though :(
