### ISSUE TITLE
Send Hack Club email to SFUSD

### ISSUE THREAD

**Issue by maxwofford** [hackedu/hack-camp#550]
I'll be emailing a contact at SFUSD to see if we can get a message on their bulletin.

**Comment by maxwofford** [comment]
Update! Just reached out to Ellen Reller to see if she can add us to their bulletin

**Comment by maxwofford** [comment]
We're on the bulletin.

 ![](https://media.giphy.com/media/IWGw3C8b6HGQo/giphy.gif)

**Comment by zachlatta** [comment]
Wow, this GIF is amazing.

On Tue, May 3, 2016 at 6:45 PM, Max Wofford notifications@github.com
wrote:

> Closed #550 https://github.com/hackclub/hackcamp/issues/550.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/hackclub/hackcamp/issues/550#event-649635058

## 

Zach Latta
Hack Club | zach@hackclub.com
