### ISSUE TITLE
Send email to community about Hack Camp

### ISSUE THREAD

**Issue by maxwofford** [hackedu/hack-camp#551]
@zachlatta Would you be interested in taking point on this?

**Comment by zachlatta** [comment]
Most certainly.

On Thu, Apr 28, 2016 at 2:05 PM, Max Wofford notifications@github.com
wrote:

> @zachlatta https://github.com/zachlatta Would you be interested in
> taking point on this?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/hackclub/hackcamp/issues/551

## 

Zach Latta
https://zachlatta.com http://zachlatta.com

**Comment by maxwofford** [comment]
@zachlatta This probably has some overlap with https://github.com/hackclub/blog/issues/24. Down to sync up on slack before working on it?

**Comment by zachlatta** [comment]
Sure thing. @jkwok91 and I are about to run a workshop at a school, but I'll be free later tonight

**Comment by maxwofford** [comment]
Looks like this was sent out. @zachlatta: is there anything else left to the issue?

**Comment by zachlatta** [comment]
We're good to close!

**Comment by maxwofford** [comment]
@zachlatta I didn't see an email to our mailchimp mailing list. Was this issue just for emailing club leaders?
