### ISSUE TITLE
Promoting Hack Camp on Facebook/Twitter

### ISSUE THREAD

**Issue by selynna** [hackedu/hack-camp#552]
Sub issue for #546 
- [x] Post on Facebook
  - [x] Hack Club Facebook
  - [x] Other Facebook groups (HS Hackers, HH, etc)
  - [x] Hackathon Facebook groups (Los Altos Hacks, etc)
- [x] Post on Twitter

**Comment by selynna** [comment]
Done!

**Comment by maxwofford** [comment]
![screenshot_2015-11-05_093014](https://cloud.githubusercontent.com/assets/5891442/14907310/e0626532-0d94-11e6-858e-97baf6ca8fca.png)

Thanks @ssun098 !
