### ISSUE TITLE
Create MOU with Galvanize for venue

### ISSUE THREAD

**Issue by zachlatta** [hackedu/hack-camp#56]
Create a memo-of-understand with Galvanize and get both parties to sign it to confirm the venue in writing.

**Comment by zachlatta** [comment]
@jonleung I need you to send me a list of everything they've agreed to give us (with dates).

**Comment by jonleung** [comment]
@zachlatta, see #124
- G4E space.

Other than that, I don't think anything else is too relevant?

**Comment by zachlatta** [comment]
Still waiting on you to send me a list of everything they've agreed to give us with dates. These include the basement classroom area, key-fobs for everyone on the team, etc. #124 refers to how we need to ask them for more things. This issue is about creating an MOU for our current agreement.

If we're able to get more things from them for #124, then we can amend the MOU with any new agreements.

**Comment by jonleung** [comment]
Currently it's only the new classroom space to fit more people
& Our desk space at galvanize

**Comment by zachlatta** [comment]
Going to go ahead and assign you to this because I'm waiting on you to respond.

**Comment by jonleung** [comment]
@zachlatta I anticipate that this is just going to keep getting pushed back further and further and can only be done after you talk with Ryan about the new space
