### ISSUE TITLE
Send out email on BPN

### ISSUE THREAD

**Issue by maxwofford** [hackedu/hack-camp#577]
Currently working with Sooz to get this posted

**Comment by zachlatta** [comment]
:ok_hand:

On Mon, May 2, 2016 at 4:59 PM, Max Wofford notifications@github.com
wrote:

> Currently working with Sooz to get this posted
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/hackclub/hackcamp/issues/577

## 

Zach Latta
Hack Club | zach@hackclub.com

**Comment by zachlatta** [comment]
Any updates on this?

**Comment by maxwofford** [comment]
Sooz is unresponsive, @gemmabusoni may have a way to get a blurb posted.

**Comment by zachlatta** [comment]
Okay, cool. Thanks for the update.

Gemma, any idea if your mom has acted to the Berkeley Parent Network?

**Comment by maxwofford** [comment]
Going to close this for now. Haven't heard a response.
