### ISSUE TITLE
Associate Hack Camp with Hack Club

### ISSUE THREAD

**Issue by maxwofford** [hackedu/hack-camp#578]
Right now https://camp.hackclub.com doesn't include many references to Hack Club beyond a single paragraph in the summary section. It would be cool to also add Hack Club to the footer (and maybe include a tax-id).

**Comment by zachlatta** [comment]
I like the way we included it in the header last year – maybe we could do
something similar?

On Mon, May 2, 2016 at 6:56 PM, Max Wofford notifications@github.com
wrote:

> Right now camp.hackclub.com doesn't include many references to Hack Club
> beyond a single paragraph in the summary section. It would be cool to also
> add Hack Club to the footer (and maybe include a tax-id).
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/hackclub/hackcamp/issues/578

## 

Zach Latta
Hack Club | zach@hackclub.com

**Comment by maxwofford** [comment]
I'll play with the design later today

**Comment by zachlatta** [comment]
:raised_hands:

Looking forward to seeing it.

On Thu, May 5, 2016 at 9:08 AM, Max Wofford notifications@github.com
wrote:

> I'll play with the design later today
> 
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> https://github.com/hackclub/hackcamp/issues/578#issuecomment-217196886

## 

Zach Latta
https://zachlatta.com http://zachlatta.com

**Comment by maxwofford** [comment]
Hmmm... Having trouble covering this with my other tasks.

@KrishMunot Would you be interested in this?

**Comment by zachlatta** [comment]
Ping @KrishMunot.

**Comment by KrishMunot** [comment]
I am on it fam

**Comment by zachlatta** [comment]
Any updates on this @KrishMunot?

**Comment by maxwofford** [comment]
Closing this along with https://github.com/hackclub/hackcamp/pull/622.
