### ISSUE TITLE
Hack Camp stickers

### ISSUE THREAD

**Issue by maxwofford** [hackedu/hack-camp#580]
These would be amazing!

**Comment by zachlatta** [comment]
@jkwok91

On Tue, May 3, 2016 at 4:51 AM, Max Wofford notifications@github.com
wrote:

> These would be amazing!
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/hackclub/hackcamp/issues/580

## 

Zach Latta
Hack Club | zach@hackclub.com

**Comment by jkwok91** [comment]
drafts will be posted here

**Comment by selynna** [comment]
@jkwok91 can we get updates posted here? :)

**Comment by maxwofford** [comment]
Closing this so we can track it in #638.
