### ISSUE TITLE
Hack Camp swag

### ISSUE THREAD

**Issue by KrishMunot** [hackedu/hack-camp#581]
- [ ] Hack Camp t-shirts (#583)
- [ ] Hack Camp stickers (#580)

**Comment by maxwofford** [comment]
This probably includes #580. @KrishMunot What other things were you thinking?

**Comment by KrishMunot** [comment]
I was thinking of hack camp tees for campers or volunteers. Also if the budget suffices, we can have something more fancy.

**Comment by maxwofford** [comment]
Would you be interested in this @jkwok91?

**Comment by maxwofford** [comment]
@KrishMunot I'll add those to the description

**Comment by maxwofford** [comment]
Closing this so we can track it in #638.
