### ISSUE TITLE
Make 'coding experience' form question required

### ISSUE THREAD

**Issue by maxwofford** [hackedu/hack-camp#582]

**Comment by maxwofford** [comment]
@zachlatta Just tested this. The field is already required on the website, but somehow an application got through without this info. Thoughts?

**Comment by maxwofford** [comment]
Until this can be replicated, going to close this.

**Comment by zachlatta** [comment]
They probably had JavaScript disabled (or something along those lines).

On Thu, May 5, 2016 at 9:07 AM, Max Wofford notifications@github.com
wrote:

> Until this can be replicated, going to close this.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/hackclub/hackcamp/issues/582#issuecomment-217196490

## 

Zach Latta
https://zachlatta.com http://zachlatta.com
