### ISSUE TITLE
Hack Camp t-shirts

### ISSUE THREAD

**Issue by maxwofford** [hackedu/hack-camp#583]

**Comment by zachlatta** [comment]
:raised_hands:

On Thu, May 5, 2016 at 8:03 AM, Max Wofford notifications@github.com
wrote:

> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/hackclub/hackcamp/issues/583

## 

Zach Latta
Hack Club | zach@hackclub.com

**Comment by maxwofford** [comment]
Closing this so we can track it in #638.
