### ISSUE TITLE
Draft volunteer information blurb

### ISSUE THREAD

**Issue by maxwofford** [hackedu/hack-camp#585]

**Comment by zachlatta** [comment]
Have we already figured out how we want to handle volunteers?

On Thu, May 5, 2016 at 8:37 AM, Max Wofford notifications@github.com
wrote:

> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/hackclub/hackcamp/issues/585

## 

Zach Latta
Hack Club | zach@hackclub.com

**Comment by maxwofford** [comment]
@zachlatta Not yet. I'll be working on figuring that out tomorrow.

**Comment by zachlatta** [comment]
Any updates on this?

**Comment by maxwofford** [comment]
Going to go ahead and close this. I'll just be contacting the volunteers directly.
