### ISSUE TITLE
Set up Facebook ads for Hack Camp

### ISSUE THREAD

**Issue by maxwofford** [hackedu/hack-camp#591]

**Comment by maxwofford** [comment]
The ad has been set up. Last step is to add fb pixel to the site (#592)

**Comment by zachlatta** [comment]
:raised_hands:

On Fri, May 6, 2016 at 7:14 AM, Max Wofford notifications@github.com
wrote:

> The ad has been set up. Last step is to add fb pixel to the site (#592
> https://github.com/hackclub/hackcamp/pull/592)
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/hackclub/hackcamp/issues/591#issuecomment-217451536

## 

Zach Latta
Hack Club | zach@hackclub.com

**Comment by maxwofford** [comment]
Now that we're using Segment for an analytics proxy, the FB side of this has been finished. Going to close this and open a new issue for setting up Segment.
