### ISSUE TITLE
Reach out to SFUSD CS teachers

### ISSUE THREAD

**Issue by maxwofford** [hackedu/hack-camp#596]
Contacting SFUSD principals (#589) seems to have been rather effective. Let's try contacting computer science teachers at the remaining 7 schools.

**Comment by zachlatta** [comment]
Sounds fantastic. Can I help out with this at all?

On Fri, May 6, 2016 at 8:06 PM, Max Wofford notifications@github.com
wrote:

> Contacting SFUSD principals (#589
> https://github.com/hackclub/hackcamp/issues/589) seems to have been
> rather effective. Let's try contacting cs teachers at the remaining 7
> schools.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/hackclub/hackcamp/issues/596

## 

Zach Latta
Hack Club | zach@hackclub.com

**Comment by maxwofford** [comment]
@zachlatta would you please send the list of emails from Dariana to both @ssun098 and I?

**Comment by zachlatta** [comment]
Done!

**Comment by maxwofford** [comment]
The next step in this issue to to call the following schools and ask for CS teacher emails:

Academy of Arts and Sciences
Asawa San Francisco School Of The Arts (SOTA)
Balboa High School
Burton, Phillip and Sala High School
Downtown High School
Galileo High School
Independence High School
International Studies Academy
Jordan, June High School
Marshall, Thurgood High School
Mission High School
O'Connell, John High School
S.F. International High School
Wallenberg, Raoul High School
Washington, George High School
Wells, Ida B. High School

**Comment by zachlatta** [comment]
No need to call, let's email the contacts of the principals we have.

On Thu, May 12, 2016 at 6:19 PM, Max Wofford notifications@github.com
wrote:

> The next step in this issue to to call the following schools and ask for
> CS teacher emails:
> 
> Academy of Arts and Sciences
> Asawa San Francisco School Of The Arts (SOTA)
> Balboa High School
> Burton, Phillip and Sala High School
> Downtown High School
> Galileo High School
> Independence High School
> International Studies Academy
> Jordan, June High School
> Marshall, Thurgood High School
> Mission High School
> O'Connell, John High School
> S.F. International High School
> Wallenberg, Raoul High School
> Washington, George High School
> Wells, Ida B. High School
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/hackclub/hackcamp/issues/596#issuecomment-218929035

## 

Zach Latta
https://zachlatta.com http://zachlatta.com

**Comment by zachlatta** [comment]
Basically, we want to get the highest return for our investment. Calling
will be super time intensive.

On Thu, May 12, 2016 at 8:56 PM, Zach Latta zach@zachlatta.com wrote:

> No need to call, let's email the contacts of the principals we have.
> 
> On Thu, May 12, 2016 at 6:19 PM, Max Wofford notifications@github.com
> wrote:
> 
> > The next step in this issue to to call the following schools and ask for
> > CS teacher emails:
> > 
> > Academy of Arts and Sciences
> > Asawa San Francisco School Of The Arts (SOTA)
> > Balboa High School
> > Burton, Phillip and Sala High School
> > Downtown High School
> > Galileo High School
> > Independence High School
> > International Studies Academy
> > Jordan, June High School
> > Marshall, Thurgood High School
> > Mission High School
> > O'Connell, John High School
> > S.F. International High School
> > Wallenberg, Raoul High School
> > Washington, George High School
> > Wells, Ida B. High School
> > 
> > —
> > You are receiving this because you were mentioned.
> > Reply to this email directly or view it on GitHub
> > https://github.com/hackclub/hackcamp/issues/596#issuecomment-218929035
> 
> ## 
> 
> Zach Latta
> https://zachlatta.com http://zachlatta.com

## 

Zach Latta
https://zachlatta.com http://zachlatta.com
