### ISSUE TITLE
Chat with staff members who haven't been in a check-in call

### ISSUE THREAD

**Issue by maxwofford** [hackedu/hack-camp#598]
I'll be setting up calls with anyone looking to be a staff member but was not at the first check-in call.

**Comment by zachlatta** [comment]
How's this going? Would it make sense to deprioritize this, since there's so many other things to do?

**Comment by maxwofford** [comment]
@zachlatta Yep. Going to keep the issue open, but drop it from this week's deadline.

**Comment by maxwofford** [comment]
Just had a chat with @gemmabusoni. Going to close this now.
