### ISSUE TITLE
Create list of tasks to build curriculum for Cohort 2

### ISSUE THREAD

**Issue by jonleung** [hackedu/hack-camp#60]
Go through feedback/reflect on cohort 1 and create a list of tasks to do this week to build the curriculum for our second cohort.

Will need to work with @MaxWofford and @andreadeng synchronously doing.

**Comment by maxwofford** [comment]
@jonleung Doesn't this already exist? https://github.com/hackedu/hack-camp/issues/57

**Comment by maxwofford** [comment]
@jonleung Can I close this?

**Comment by maxwofford** [comment]
These were added as issues for each person it involved.
