### ISSUE TITLE
Add future deadlines to Hack Camp organization issue

### ISSUE THREAD

**Issue by maxwofford** [hackedu/hack-camp#600]
We'll be recording goals and tasks for future weeks in #597. I need to add them.

**Comment by maxwofford** [comment]
Also need to add a checklist on the issue of everything that needs to get done by the first day of Hack Camp "e.g., slides for intro presentation"

**Comment by maxwofford** [comment]
I've just ordered goals and tasks for future weeks, as well as added a 'first day checklist' section

**Comment by zachlatta** [comment]
👏
