### ISSUE TITLE
Create Hack Camp promo codes

### ISSUE THREAD

**Issue by maxwofford** [hackedu/hack-camp#608]
This issue entails creating an optional field on the form that records promo code

**Comment by maxwofford** [comment]
UPDATE: I've just created a textbox on the google form for applicants to add  a promo code. It's name is `entry.2053418849`.

**Comment by zachlatta** [comment]
@KrishMunot: want to add a field to the application on the website for a promo code? (and, as a result, take point on this issue)

**Comment by KrishMunot** [comment]
@zachlatta: Sure! I will take care of this.
