### ISSUE TITLE
Get three venues to "in talks" by this Friday (05.13.16)

### ISSUE THREAD

**Issue by zachlatta** [hackedu/hack-camp#610]
Per our goals for this week in #597, I'm responsible for getting three potential venues to the "in talks" stage by the end of this week. Currently I'm on track to complete this.

For Hack Club/Camp staff, this is tracked in https://docs.google.com/spreadsheets/d/1HCh5YtN_Y3JXbIMoiUdv-FgYiPZZD1kGg5QnfbsxiCw/edit#gid=0 (unfortunately we can't make this public, because that same spreadsheet has student info in it).

**Comment by zachlatta** [comment]
Did this.

**Comment by maxwofford** [comment]
Nice! ![](http://cultofthepartyparrot.com/parrots/parrotdad.gif)

**Comment by zachlatta** [comment]
Did you make that parrot? It is horrifying.

On Mon, May 16, 2016 at 5:14 PM, Max Wofford notifications@github.com
wrote:

> Nice!
> https://camo.githubusercontent.com/704e70115c5e79f0825037e6f5a2eacef567c505/687474703a2f2f63756c746f667468657061727479706172726f742e636f6d2f706172726f74732f706172726f746461642e676966
> 
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub
> https://github.com/hackclub/hackcamp/issues/610#issuecomment-219585518

## 

Zach Latta
https://zachlatta.com http://zachlatta.com

**Comment by zachlatta** [comment]
(in the best kind of way)

On Mon, May 16, 2016 at 5:16 PM, Zach Latta zach@zachlatta.com wrote:

> Did you make that parrot? It is horrifying.
> 
> On Mon, May 16, 2016 at 5:14 PM, Max Wofford notifications@github.com
> wrote:
> 
> > Nice!
> > https://camo.githubusercontent.com/704e70115c5e79f0825037e6f5a2eacef567c505/687474703a2f2f63756c746f667468657061727479706172726f742e636f6d2f706172726f74732f706172726f746461642e676966
> > 
> > —
> > You are receiving this because you modified the open/close state.
> > Reply to this email directly or view it on GitHub
> > https://github.com/hackclub/hackcamp/issues/610#issuecomment-219585518
> 
> ## 
> 
> Zach Latta
> https://zachlatta.com http://zachlatta.com

## 

Zach Latta
https://zachlatta.com http://zachlatta.com

**Comment by maxwofford** [comment]
Nope! but here's the source: http://cultofthepartyparrot.com/ (https://i.imgur.com/USC90yq.gif)

**Comment by zachlatta** [comment]
I mean, did you make that specific GIF of the parrot?

On Mon, May 16, 2016 at 5:17 PM, Max Wofford notifications@github.com
wrote:

> Nope! but here's the source: http://cultofthepartyparrot.com/ (
> https://i.imgur.com/USC90yq.gif)
> 
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub
> https://github.com/hackclub/hackcamp/issues/610#issuecomment-219586069

## 

Zach Latta
https://zachlatta.com http://zachlatta.com
