### ISSUE TITLE
Reach out to SF libraries for venue

### ISSUE THREAD

**Issue by selynna** [hackedu/hack-camp#617]

**Comment by zachlatta** [comment]
:raised_hands:

On Thu, May 12, 2016 at 8:51 PM, Selynna Sun notifications@github.com
wrote:

> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/hackclub/hackcamp/issues/617

## 

Zach Latta
Hack Club | zach@hackclub.com

**Comment by maxwofford** [comment]
@ssun098 Is this a goal for this week or next? (asking so I can update #597)

**Comment by selynna** [comment]
@MaxWofford sorry for late reply! Yeah, this is a goal for next week.

**Comment by maxwofford** [comment]
@ssun098 Are we still doing this?

**Comment by zachlatta** [comment]
Let's close, we're good on venue (at least for the first cohort).
