### ISSUE TITLE
Reach out to Bay Area hackathon organizers

### ISSUE THREAD

**Issue by selynna** [hackedu/hack-camp#619]
Giving small talks about Hack Camp at opening ceremony
- [x] CodeDay Bay Area
- [x] BASEHacks
- [x] CUHacks

**Comment by selynna** [comment]
Update: BASEHacks is down for a 2-3 minute slot at opening ceremony, + a table. CUHacks we'll be going for the opening ceremony and leaving right after (so I don't get locked in) 

@zachlatta

**Comment by zachlatta** [comment]
:raised_hands:

Sounds awesome – what's the date for it again and what time do we have to
get there?

On Tue, May 31, 2016 at 1:29 PM, Selynna Sun notifications@github.com
wrote:

> Update: BASEHacks is down for a 2-3 minute slot at opening ceremony, + a
> table. CUHacks we'll be going for the opening ceremony and leaving right
> after (so I don't get locked in)
> 
> @zachlatta https://github.com/zachlatta
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/hackclub/hackcamp/issues/619#issuecomment-222810139,
> or mute the thread
> https://github.com/notifications/unsubscribe/AA8j-DflnLYwb4oR2VoG_D6T8vfuUnJGks5qHJoMgaJpZM4IeRNd
> .

## 

Zach Latta
https://zachlatta.com http://zachlatta.com

**Comment by selynna** [comment]
Both are on June 11th, and I still have to confirm opening ceremony time.
We might have to split between the hackathons.

**Comment by zachlatta** [comment]
Oh sweet, awesome. How much do you think we'll get out of being at both for
the entire hackathons?

What if we just did opening ceremonies, handed out tons of stickers, then
called it from there?

On Tue, May 31, 2016 at 3:16 PM, Selynna Sun notifications@github.com
wrote:

> Both are on June 11th, and I still have to confirm opening ceremony time.
> We might have to split between the hackathons.
> 
> On Tue, May 31, 2016 at 3:11 PM Zach Latta notifications@github.com
> wrote:
> 
> > :raised_hands:
> > 
> > Sounds awesome – what's the date for it again and what time do we have to
> > get there?
> > 
> > On Tue, May 31, 2016 at 1:29 PM, Selynna Sun notifications@github.com
> > wrote:
> > 
> > > Update: BASEHacks is down for a 2-3 minute slot at opening ceremony, +
> > > a
> > > table. CUHacks we'll be going for the opening ceremony and leaving
> > > right
> > > after (so I don't get locked in)
> > > 
> > > @zachlatta https://github.com/zachlatta
> > > 
> > > —
> > > You are receiving this because you were mentioned.
> > > Reply to this email directly, view it on GitHub
> > > <
> > > https://github.com/hackclub/hackcamp/issues/619#issuecomment-222810139
> > > ,
> > > or mute the thread
> > > <
> > 
> > https://github.com/notifications/unsubscribe/AA8j-DflnLYwb4oR2VoG_D6T8vfuUnJGks5qHJoMgaJpZM4IeRNd
> > 
> > > .
> > 
> > ## 
> > 
> > Zach Latta
> > https://zachlatta.com http://zachlatta.com
> > 
> > —
> > You are receiving this because you were assigned.
> > Reply to this email directly, view it on GitHub
> > <https://github.com/hackclub/hackcamp/issues/619#issuecomment-222836866
> > ,
> > or mute the thread
> > <
> > https://github.com/notifications/unsubscribe/AHYhMp7nTh_-5MInSoUjfDwjppgbV4Xqks5qHLIAgaJpZM4IeRNd
> > 
> > .
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/hackclub/hackcamp/issues/619#issuecomment-222837991,
> or mute the thread
> https://github.com/notifications/unsubscribe/AA8j-ATEnwlOntLhhU3rJqvZIxKg4aLAks5qHLMxgaJpZM4IeRNd
> .

## 

Zach Latta
https://zachlatta.com http://zachlatta.com

**Comment by selynna** [comment]
I think BASEHacks might be worth staying for, but CUHacks I was thinking we
just do opening and hand out a crap ton of stickers

**Comment by zachlatta** [comment]
Cool, let's plan on it. Can you put this on the team calendar?

On Tue, May 31, 2016 at 6:08 PM, Selynna Sun notifications@github.com
wrote:

> I think BASEHacks might be worth staying for, but CUHacks I was thinking we
> just do opening and hand out a crap ton of stickers
> 
> On Tue, May 31, 2016 at 3:19 PM Zach Latta notifications@github.com
> wrote:
> 
> > Oh sweet, awesome. How much do you think we'll get out of being at both
> > for
> > the entire hackathons?
> > 
> > What if we just did opening ceremonies, handed out tons of stickers, then
> > called it from there?
> > 
> > On Tue, May 31, 2016 at 3:16 PM, Selynna Sun notifications@github.com
> > wrote:
> > 
> > > Both are on June 11th, and I still have to confirm opening ceremony
> > > time.
> > > We might have to split between the hackathons.
> > > 
> > > On Tue, May 31, 2016 at 3:11 PM Zach Latta notifications@github.com
> > > wrote:
> > > 
> > > > :raised_hands:
> > > > 
> > > > Sounds awesome – what's the date for it again and what time do we
> > > > have
> > > > to
> > > > get there?
> > > > 
> > > > On Tue, May 31, 2016 at 1:29 PM, Selynna Sun <
> > > > notifications@github.com
> > > > 
> > > > wrote:
> > > > 
> > > > > Update: BASEHacks is down for a 2-3 minute slot at opening
> > > > > ceremony,
> > > > > +
> > > > > a
> > > > > table. CUHacks we'll be going for the opening ceremony and leaving
> > > > > right
> > > > > after (so I don't get locked in)
> > > > > 
> > > > > @zachlatta https://github.com/zachlatta
> > > > > 
> > > > > —
> > > > > You are receiving this because you were mentioned.
> > > > > Reply to this email directly, view it on GitHub
> > > > > <
> > > > > https://github.com/hackclub/hackcamp/issues/619#issuecomment-222810139
> > > > > ,
> > > > > or mute the thread
> > > > > <
> > 
> > https://github.com/notifications/unsubscribe/AA8j-DflnLYwb4oR2VoG_D6T8vfuUnJGks5qHJoMgaJpZM4IeRNd
> > 
> > > > > .
> > > > 
> > > > ## 
> > > > 
> > > > Zach Latta
> > > > https://zachlatta.com http://zachlatta.com
> > > > 
> > > > —
> > > > You are receiving this because you were assigned.
> > > > Reply to this email directly, view it on GitHub
> > > > <
> > > > https://github.com/hackclub/hackcamp/issues/619#issuecomment-222836866
> > > > ,
> > > > or mute the thread
> > > > <
> > 
> > https://github.com/notifications/unsubscribe/AHYhMp7nTh_-5MInSoUjfDwjppgbV4Xqks5qHLIAgaJpZM4IeRNd
> > 
> > > > .
> > > 
> > > —
> > > You are receiving this because you were mentioned.
> > > Reply to this email directly, view it on GitHub
> > > <
> > > https://github.com/hackclub/hackcamp/issues/619#issuecomment-222837991
> > > ,
> > > or mute the thread
> > > <
> > 
> > https://github.com/notifications/unsubscribe/AA8j-ATEnwlOntLhhU3rJqvZIxKg4aLAks5qHLMxgaJpZM4IeRNd
> > 
> > > .
> > 
> > ## 
> > 
> > Zach Latta
> > https://zachlatta.com http://zachlatta.com
> > 
> > —
> > You are receiving this because you were assigned.
> > Reply to this email directly, view it on GitHub
> > <https://github.com/hackclub/hackcamp/issues/619#issuecomment-222838712
> > ,
> > or mute the thread
> > <
> > https://github.com/notifications/unsubscribe/AHYhMrTmlJKhDU1vjndGQv_7j_YrPUjqks5qHLP5gaJpZM4IeRNd
> > 
> > .
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/hackclub/hackcamp/issues/619#issuecomment-222865959,
> or mute the thread
> https://github.com/notifications/unsubscribe/AA8j-DWJrOwbErVt5ulXSMjYKcAtqN9oks5qHNuFgaJpZM4IeRNd
> .

## 

Zach Latta
https://zachlatta.com http://zachlatta.com

**Comment by selynna** [comment]
On the calendar :)

**Comment by selynna** [comment]
Just FYI - we have to be at BASEHacks by 10am, and CUHacks by 5pm.

@zachlatta @MaxWofford

**Comment by zachlatta** [comment]
:thumbsup:

On Fri, Jun 10, 2016 at 4:26 PM, Selynna Sun notifications@github.com
wrote:

> Just FYI - we have to be at BASEHacks by 10am, and CUHacks by 5pm.
> 
> @zachlatta https://github.com/zachlatta @MaxWofford
> https://github.com/MaxWofford
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/hackclub/hackcamp/issues/619#issuecomment-225318879,
> or mute the thread
> https://github.com/notifications/unsubscribe/AA8j-D-MfT-qSbtiPs-6N8QS98rAbAjwks5qKfLCgaJpZM4IeRNd
> .

## 

Zach Latta
https://zachlatta.com http://zachlatta.com

**Comment by selynna** [comment]
Gonna close this since we're basically done at this point
