### ISSUE TITLE
Email Cohort 2 students about July 3rd (friday) being federal holiday and that we're running a third week

### ISSUE THREAD

**Issue by andreadeng** [hackedu/hack-camp#62]
Ask students if they can make the day.

**Comment by maxwofford** [comment]
Ask participants over email if they can show up that day.

**Comment by jonleung** [comment]
@zachlatta Is there a signup or some way for them to acknowledge that they are coming or not?

**Comment by zachlatta** [comment]
@jonleung we can make a Google Form asking if they can't make it (so we'll only collect info from people who can't) or something along those lines.

**Comment by zachlatta** [comment]
@jonleung ping for #102.

**Comment by jonleung** [comment]
@zachlatta, @andreadeng can help with this. Thoughts?

**Comment by jonleung** [comment]
@andreadeng already made a survey for this

**Comment by jonleung** [comment]
@zachlatta  @andreadeng  what are the actionable things we need to do for this?

**Comment by zachlatta** [comment]
I'd say that the issue's title is pretty actionable. Still waiting on you to respond to my question in #102.

**Comment by jonleung** [comment]
@andreadeng can you sync up with @zachlatta on this (as discussed at standups)

**Comment by zachlatta** [comment]
Assigning to @andreadeng while I wait for her to get back to me.

**Comment by zachlatta** [comment]
Whoops, sorry @amandadoan!

**Comment by jonleung** [comment]
Closing this issue because we asked who would be interested in a 3rd week and 2 students said they could make some and 1 person said they could make all. The task at hand is not to email them about the 3rd week but rather to decide whether we want to even run a 3rd week in this scenario. @zachlatta thoughts on specificity?
