### ISSUE TITLE
Create applicant confirmation/payment form

### ISSUE THREAD

**Issue by maxwofford** [hackedu/hack-camp#630]
Create payment form for applicants using stripe.

**Comment by zachlatta** [comment]
So, just to clarify, this is what we'll send accepted applicants to collect
their tuition payments, yes?

On Mon, May 23, 2016 at 11:46 AM, Max Wofford notifications@github.com
wrote:

> Create payment form for applicants using stripe.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/hackclub/hackcamp/issues/630

## 

Zach Latta
Hack Club | zach@hackclub.com

**Comment by maxwofford** [comment]
Yes

**Comment by zachlatta** [comment]
Created a Wufoo form for this :raised_hands:. Link: https://hackclub.wufoo.com/forms/z1x0dwtm11iqd30/

**Comment by maxwofford** [comment]
Thanks @zachlatta!

![53yhutg](https://cloud.githubusercontent.com/assets/5891442/15594780/bc69665a-236d-11e6-9d86-d54f61e79d33.png)

**Comment by zachlatta** [comment]
This is the most amazing Orpheus.

On Thu, May 26, 2016 at 6:14 PM, Max Wofford notifications@github.com
wrote:

> Thanks @zachlatta https://github.com/zachlatta!
> 
> [image: 53yhutg]
> https://cloud.githubusercontent.com/assets/5891442/15594780/bc69665a-236d-11e6-9d86-d54f61e79d33.png
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/hackclub/hackcamp/issues/630#issuecomment-222036963,
> or mute the thread
> https://github.com/notifications/unsubscribe/AA8j-OabWNQhZsSCYQdYT6CDkWkgG1ouks5qFkWRgaJpZM4Ikv3U
> .

## 

Zach Latta
https://zachlatta.com http://zachlatta.com
