### ISSUE TITLE
Update "When are applications due" for next session on the website

### ISSUE THREAD

**Issue by saescapa** [hackedu/hack-camp#636]
Title
Also, is there a way for applicants to apply for specific sessions?

**Comment by selynna** [comment]
@saescapa there isn't a way for them to apply to specific sessions, though we'll get into contact with them later about that

**Comment by maxwofford** [comment]
@saescapa: we're currently planning on putting up a deadline for the next session this Saturday, after the first session sign up ends.

**Comment by saescapa** [comment]
@MaxWofford hasn't the first session sign up ended? it says May 16th on website

**Comment by maxwofford** [comment]
@saescapa: thanks for catching that!

**Comment by maxwofford** [comment]
Just closed by #637
