### ISSUE TITLE
First day of Hack Camp

### ISSUE THREAD

**Issue by maxwofford** [hackedu/hack-camp#638]
/cc @hackclub/hack-camp

Here's what we need to have a kickass first day of Hack Camp 2016:
- [ ] Set up venue
  - [x] Go to venue and add new tasks to this list
  - [ ] Distribute keys to staff (x5) @MaxWofford
  - [x] Clean up venue @MaxWofford
  - [x] Power @MaxWofford
  - [x] Internet (repeater) @MaxWofford
  - [x] Tables (x4) @gemmabusoni
  - [x] Chairs (x25) @gemmabusoni
  - [ ] ~~Ethernet connections~~ (Bringing Chromebook for any hacker without wifi)
  - [x] Projector @MaxWofford
  - [x] Adapter for projector @MaxWofford
  - [x] Toilet paper/napkins @prophetorpheus
  - [ ] Games @MaxWofford
- [ ] Breakfast
  - [x] Food (fruit, nature valley bars) @ssun098
  - [x] Utensils & plates @ssun098
  - [x] Trashbins @MaxWofford
- [ ] Content
  - [ ] 15-20 hackers confirmed and paid
  - [x] Have minimum 2 staff confirmed for first day
  - [x] Schedule for first day @ssun098
  - [x] Do run-through of first day with staff @MaxWofford
  - [ ] ~~Slide deck for introduction to Hack Camp~~ (Decided on verbal intro talk)
  - [x] Workshop to be run on first day @ssun098
  - [x] Hacker feedback task added to Howdy.ai @MaxWofford
  - [x] Energizers @ssun098
  - [x] Spotify playlist set up @MaxWofford
  - [ ] Stickers ordered @MaxWofford
  - [ ] ~~T-shirts ordered~~ (Canceled because they won't arrive in time for first session)
- [ ] Broadcasts
  - [x] Get liability forms signed from parents @zachlatta
  - [x] Liability forms sent to Teespring @zachlatta
  - [x] Get signed media releases for hackers @zachlatta
  - [x] Send out reminder email with contact info and reminder about lunch and map to location to hackers and parents @zachlatta
  - [x] Confirm that hackers have working laptops with wifi @zachlatta
  - [x] Notify hackers about reduced session size and higher mentor-student ratio @zachlatta

**Comment by maxwofford** [comment]
Closing because we ran the first day :100:

**Comment by zachlatta** [comment]
👏👏👏
