### ISSUE TITLE
Create personal notes folder for next cohort

### ISSUE THREAD

**Issue by maxwofford** [hackedu/hack-camp#64]
A folder where we can put our personal notes and observations from cohort 2.

**Comment by maxwofford** [comment]
@jonleung @andreadeng @zachlatta Notes can now be added on the `notes` branch of hack-camp

**Comment by zachlatta** [comment]
Does it make sense to have these in a branch and not in a directory?

**Comment by maxwofford** [comment]
@zachlatta fixed in #90

**Comment by zachlatta** [comment]
Closed by #90.
