### ISSUE TITLE
Ask available dates in Hack Camp application form

### ISSUE THREAD

**Issue by maxwofford** [hackedu/hack-camp#640]
Something like the following with checkboxes:

1) Which dates are you available for?
- [ ] June 6th - June 17th
- [ ] June 27th - July 8th
- [ ] July 18th - July 29th
- [ ] August 8th - August 19th

**Comment by zachlatta** [comment]
+1

On Fri, May 27, 2016 at 11:30 PM, Max Wofford notifications@github.com
wrote:

> Something like the following with checkboxes:
> 
> 1) Which dates are you available for?
> - June 6th - June 17th
> - June 27th - July 8th
> - July 18th - July 29th
> - August 8th - August 19th
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> https://github.com/hackclub/hackcamp/issues/640, or mute the thread
> https://github.com/notifications/unsubscribe/AA8j-MW36DVDVG9T8bh4GIo45sHyjq48ks5qF-EFgaJpZM4IpAnU
> .

## 

Zach Latta
Hack Club | zach@hackclub.com
