### ISSUE TITLE
Fix coding experience radio buttons on mobile 

### ISSUE THREAD

**Issue by zachlatta** [hackedu/hack-camp#648]
_From @MaxWofford on May 20, 2016 21:47_

http://peek.usertesting.com/result/14941866645557?autoplay=true

At the 2:30 mark, the radio buttons are on different lines to their labels 

_Copied from original issue: hackclub/hackclub#831_

**Comment by maxwofford** [comment]
Thanks for moving this @zachlatta!

![](https://media.giphy.com/media/vndqDYjLFzry0/giphy.gif)

**Comment by zachlatta** [comment]
Going to go ahead and close this because we're not focused on maintaining Hack Camp's site anymore.
