### ISSUE TITLE
Test out camera and recording location in classroom

### ISSUE THREAD

**Issue by andreadeng** [hackedu/hack-camp#65]

**Comment by jonleung** [comment]
Just ordered the proper batteries to get the camera to work properly, waiting for it to arrive tomorrow evening.

**Comment by zachlatta** [comment]
Status on this?

**Comment by jonleung** [comment]
@zachlatta I moved this to the ice box because it is no longer that relevant to record things from this cohort because our focus is more on creating great curriculum, not about documenting it.

**Comment by zachlatta** [comment]
Does it make sense to do this task? Perhaps we could close it and reopen it later if we find it makes sense to do it?

**Comment by zachlatta** [comment]
Closing for now due to lack of responses.
