### ISSUE TITLE
Add labels onto keys

### ISSUE THREAD

**Issue by selynna** [hackedu/hack-camp#656]
Sub-spreadsheet already created in Hack Camp 2016

**Comment by maxwofford** [comment]
I've got new copies from Cliffs, will take them in for labeling tomorrow

**Comment by maxwofford** [comment]
I've distributed the keys to staff. Is it cool if I close?

**Comment by zachlatta** [comment]
Go for it

**Comment by zachlatta** [comment]
Reopening because it turns out labels still need to be added to the keys. @MaxWofford can you handle this?

**Comment by maxwofford** [comment]
Yep! Just added the labels and recorded them in https://docs.google.com/spreadsheets/d/1HCh5YtN_Y3JXbIMoiUdv-FgYiPZZD1kGg5QnfbsxiCw/edit#gid=1683930002
