### ISSUE TITLE
Bring games to venue

### ISSUE THREAD

**Issue by maxwofford** [hackedu/hack-camp#660]
Board games, card games, etc.

**Comment by zachlatta** [comment]
good games, lame games, meme games, etc

On Tue, Jun 7, 2016 at 9:32 PM, Max Wofford notifications@github.com
wrote:

> Board games, card games, etc.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> https://github.com/hackclub/hackcamp/issues/660, or mute the thread
> https://github.com/notifications/unsubscribe/AA8j-C7g00ut6Qa5kSQykNwwbdBZPPg_ks5qJkXlgaJpZM4Iwlek
> .

## 

Zach Latta
Hack Club | zach@hackclub.com

**Comment by maxwofford** [comment]
![github_reactions](https://cloud.githubusercontent.com/assets/5891442/15904574/611c30fe-2d66-11e6-8087-3dbaade8e2ce.png)

**Comment by maxwofford** [comment]
@ssun098 Could we keep the cards you brought in at the venue so we can close this?

**Comment by maxwofford** [comment]
We've got cards, so I'll close this issue.

**Comment by selynna** [comment]
I bring my cards everywhere so it shouldn't be too much of a struggle

**Comment by zachlatta** [comment]
I maintain that we need Hack Club cards.

**Comment by selynna** [comment]
I would buy so many tbh

**Comment by zachlatta** [comment]
We could have the sweet gradient on the back of the cards.

**Comment by maxwofford** [comment]
With dinosaurs on each of the face cards

**Comment by zachlatta** [comment]
Prophet Orpheus could bend his/her body into the shapes of the different numbers and suits.

**Comment by selynna** [comment]
![image](https://cloud.githubusercontent.com/assets/7741746/16174734/f1427f4a-3585-11e6-9d20-f5cd9149c1e4.png)
send help i can't do this

**Comment by selynna** [comment]
i make myself cringe 

![image](https://cloud.githubusercontent.com/assets/7741746/16174748/9e7c1e1e-3586-11e6-95b7-df8571dc626d.png)
