### ISSUE TITLE
Bring scooters to venue

### ISSUE THREAD

**Issue by maxwofford** [hackedu/hack-camp#662]

**Comment by zachlatta** [comment]
For fun? Or practical purposes?

On Wed, Jun 8, 2016 at 3:12 PM, Max Wofford notifications@github.com
wrote:

> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> https://github.com/hackclub/hackcamp/issues/662, or mute the thread
> https://github.com/notifications/unsubscribe/AA8j-ITBGqmIhyC1tG5vQo0H2iJJ3N8Eks5qJz4xgaJpZM4IxdKl
> .

## 

Zach Latta
Hack Club | zach@hackclub.com

**Comment by selynna** [comment]
For fun

**Comment by zachlatta** [comment]
I am okay with this.
