### ISSUE TITLE
Bring marshmallows and spaghetti

### ISSUE THREAD

**Issue by selynna** [hackedu/hack-camp#676]

**Comment by maxwofford** [comment]
I've got spaghetti

**Comment by selynna** [comment]
I'll get marshmallows

**Comment by maxwofford** [comment]
Just talked about this with @ssun098 in person. I'll take point on marshmallows.

**Comment by maxwofford** [comment]
Assigning @ssun098 for a test

**Comment by maxwofford** [comment]
Finished!
