### ISSUE TITLE
Create a system to remember to videotape throughout camp

### ISSUE THREAD

**Issue by andreadeng** [hackedu/hack-camp#68]
- [ ] Make sure you are prepared to record all the energizers
- [ ] Make sure you are prepared to record all the video lectures.

**Comment by maxwofford** [comment]
Where system is a reoccurring email, daily schedule, etc.

**Comment by zachlatta** [comment]
Is this still needed?

**Comment by zachlatta** [comment]
Closing due to cohort 2 being over.
