### ISSUE TITLE
Second session folder

### ISSUE THREAD

**Issue by maxwofford** [hackedu/hack-camp#687]

**Comment by zachlatta** [comment]
Do we want to organize the documents per session line we did last year?

I actually think it'd be beneficial to just continue to improve the docs we make as we go, session by session.

**Comment by maxwofford** [comment]
@ssun098 do you have thoughts on this?

**Comment by selynna** [comment]
I think either way is fine, but I feel like the folders would make it
better for tracking stuff between sessions, otherwise you'd have to
constantly look through commit history to see what was in the previous

**Comment by zachlatta** [comment]
@MaxWofford: any preference?

If both of you prefer separate folders, I'm down with this. But I also don't see harm in just using git history to see past work (after all, that's what it's for).

**Comment by jkwok91** [comment]
For the second session it seems like we're making a very experimental(?) set of changes, which we might want a separate folder for.

**Comment by zachlatta** [comment]
Okay, I'm totally cool with it in that case. Proceed as planned.

On Mon, Jun 20, 2016 at 6:50 AM, JESSICA notifications@github.com wrote:

> For the second session it seems like we're making a very experimental(?)
> set of changes, which we might want a separate folder for.
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> https://github.com/hackclub/hackcamp/issues/687#issuecomment-227147636,
> or mute the thread
> https://github.com/notifications/unsubscribe/AA8j-CBLQrVSP4I1_ldYJOyEDAx-vG2Jks5qNprCgaJpZM4I5Rta
> .

## 

Zach Latta
https://zachlatta.com http://zachlatta.com
