### ISSUE TITLE
Create document that has schedule for technical curriculum

### ISSUE THREAD

**Issue by jonleung** [hackedu/hack-camp#69]
- [ ] First, outline all of the things that needs to be covered, the requirements!

Outline flow of new technical curriculum such that every day has...
- an objective
- a vehicle
- concepts covered
- what is shipped at the end of each day
  - presentation?
  - github website?

Strategy: focus on breadth, not depth!

w1d1
- shout
- mention coldcalling
- github

w2d1
- A letter to yourself

**Comment by jonleung** [comment]
We realized that we don't have enough time to write the detailed schedule for every day (we will do the day to day just in time). Tuesday (tomorrow) has been planned, wednesday will be started soon (a little bit will be started tonight) and Thursday and subsequent days will be done later. Here is the [potential plan](https://docs.google.com/spreadsheets/d/1x_3Bh3LqjKSpDTQb8sr2alhsORp-su2oKxS9zKEPQWU/edit#gid=1956850792)

**Comment by zachlatta** [comment]
@MaxWofford – is this level of detail good for your needs? If not, we
can work together as a team to make sure everyone's needs are met.
