### ISSUE TITLE
Get 3-5 confirmed volunteer mentors for second session

### ISSUE THREAD

**Issue by maxwofford** [hackedu/hack-camp#690]

**Comment by zachlatta** [comment]
How involved does a mentor need to be?

On Mon, Jun 20, 2016 at 9:17 AM, Max Wofford notifications@github.com
wrote:

> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> https://github.com/hackclub/hackcamp/issues/690, or mute the thread
> https://github.com/notifications/unsubscribe/AA8j-FHveNS8Uu_unsoTGhpgif1orENJks5qNr0RgaJpZM4I53ov
> .

## 

Zach Latta
Hack Club | zach@hackclub.com

**Comment by maxwofford** [comment]
We're looking for people who can volunteer for the 9-5:30 the camp is running for. That being said, we might have part-time mentors on a case-by-case basis.

**Comment by zachlatta** [comment]
Gotcha. I think getting full-time mentors will be extremely difficult –
most people will probably be working then.

What if we shot to have 3-5 part-time mentors?

On Mon, Jun 20, 2016 at 10:12 AM, Max Wofford notifications@github.com
wrote:

> We're looking for people who can volunteer for the 9-5:30 the camp is
> running for. That being said, we might have part-time mentors on a
> case-by-case basis.
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> https://github.com/hackclub/hackcamp/issues/690#issuecomment-227206689,
> or mute the thread
> https://github.com/notifications/unsubscribe/AA8j-NhaQctTDw3ddExJ8gqpyY8FdTvwks5qNsnugaJpZM4I53ov
> .

## 

Zach Latta
https://zachlatta.com http://zachlatta.com

**Comment by maxwofford** [comment]
Yeah, I'm down for that.

**Comment by maxwofford** [comment]
Confirmed! We've got 3 confirmed mentors for the rest of the session
