### ISSUE TITLE
Facilitator run through of chat workshop

### ISSUE THREAD

**Issue by maxwofford** [hackedu/hack-camp#691]
https://workshops.hackclub.com/chat

**Comment by zachlatta** [comment]
What does this entail?

On Mon, Jun 20, 2016 at 9:18 AM, Max Wofford notifications@github.com
wrote:

> workshops.hackclub.com/chat
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> https://github.com/hackclub/hackcamp/issues/691, or mute the thread
> https://github.com/notifications/unsubscribe/AA8j-AtldddNWrd1h5IiLAt2lR1rWowLks5qNr1agaJpZM4I53uJ
> .

## 

Zach Latta
Hack Club | zach@hackclub.com

**Comment by maxwofford** [comment]
@ssun098 and I will run through the chat workshop ourselves to make sure we are ready to run it during the second session.

**Comment by maxwofford** [comment]
![screenshot_2016-06-20_18 08 02](https://cloud.githubusercontent.com/assets/5891442/16214956/6994db72-3712-11e6-84c0-e80869b1e910.png)

![happy dance](https://media.giphy.com/media/mHolTJoRuxPiw/giphy.gif)
