### ISSUE TITLE
Get enough tables and chairs for everyone in second session

### ISSUE THREAD

**Issue by maxwofford** [hackedu/hack-camp#695]
We can close this once all the hackers and volunteers have a chair and table space.

**Comment by selynna** [comment]
Will bring all the tables and chairs up to SF on Saturday

**Comment by selynna** [comment]
Done!
![img_6779](https://cloud.githubusercontent.com/assets/7741746/16359745/3d39f25a-3af6-11e6-8a61-24b4f927a493.JPG)
