### ISSUE TITLE
Record feedback from Howdy's task

### ISSUE THREAD

**Issue by maxwofford** [hackedu/hack-camp#705]
Dariana needs access to Howdy's feedback notes so she can record hacker feedback in the Hack Camp spreadsheet. This issue can be closed once
1. [x] Dariana has access to Howdy's feedback notes
2. [x] Dariana has been sent a guide on how to record notes from Howdy

**Comment by maxwofford** [comment]
@ssun098 can you take this?

**Comment by selynna** [comment]
@MaxWofford rip sorry I missed this notification, yeah I'll take point on it

**Comment by maxwofford** [comment]
I said I'd take point on this in-person.

**Comment by maxwofford** [comment]
I've just emailed Dariana about this.

**Comment by maxwofford** [comment]
I'll close this once all the info is in the spreadsheet at https://docs.google.com/spreadsheets/d/1HCh5YtN_Y3JXbIMoiUdv-FgYiPZZD1kGg5QnfbsxiCw/edit#gid=1669794560.

**Comment by zachlatta** [comment]
:raised_hands:

On Wed, Jul 13, 2016 at 9:34 AM, Max Wofford notifications@github.com
wrote:

> I'll close this once all the info is in the spreadsheet at
> https://docs.google.com/spreadsheets/d/1HCh5YtN_Y3JXbIMoiUdv-FgYiPZZD1kGg5QnfbsxiCw/edit#gid=1669794560
> .
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> https://github.com/hackclub/hackcamp/issues/705#issuecomment-232411886,
> or mute the thread
> https://github.com/notifications/unsubscribe/AA8j-NjOX7kzWNER_MzdBcHH_Knc153Fks5qVROLgaJpZM4I_zIR
> .

## 

Zach Latta
Hack Club | zach@hackclub.com

**Comment by maxwofford** [comment]
Adding blocking label because I'm just waiting for Dariana to do this.
