### ISSUE TITLE
Get extension cable

### ISSUE THREAD

**Issue by maxwofford** [hackedu/hack-camp#706]
The tables we're using at Hack Camp are long enough that hackers on the far sides of the table have trouble plugging their laptops into the surge protectors at the center of the table. We need to put an extension cable between two of the surge protectors so they can be spread out.

This issue can be closed once power outlets are accessible over any part of the table.

Extra power outlets and surge protectors can be found in the 1st floor of the venue.

**Comment by ssun098** [comment]
@MaxWofford can we close this?

**Comment by maxwofford** [comment]
I've got a surge protector with a long power cable in my backpack. We can use it as an extension cord.

**Comment by maxwofford** [comment]
![image](https://cloud.githubusercontent.com/assets/5891442/16456208/03630cc8-3dcc-11e6-9e07-77c6f809d2bc.jpeg)
