### ISSUE TITLE
Add Hack Cheer to the daily schedule

### ISSUE THREAD

**Issue by maxwofford** [hackedu/hack-camp#709]
At the end of the day, we circle up with hackers and on three yell "Hack!". This was [documented last year](https://github.com/hackclub/hackcamp/blob/c768bc6b6d235ea71fee30a0020ad3df933fb6ae/2015/cohort_4/playbook/ACTIVITIES.md#finishing-off-the-day) and needs to be added to this year's schedule.

This issue can be closed once the Hack Cheer is added to [ACTIVITIES.md](https://github.com/hackclub/hackcamp/blob/master/2016/playbook/ACTIVITIES.md) and added to every day in the [schedule](https://github.com/hackclub/hackcamp/blob/master/2016/playbook/session_2/SCHEDULE.md) with a table of activities in it – schedule it right after feedback forms.

To add it to the schedule, add a new row in the day's table and fill it with a link to the Hack Cheer activity in [ACTIVITIES.md](https://github.com/hackclub/hackcamp/blob/master/2016/playbook/ACTIVITIES.md).

**Comment by selynna** [comment]
Can we close? https://github.com/hackclub/hackcamp/pull/712

**Comment by maxwofford** [comment]
Go for it @ssun098 

![](https://media3.giphy.com/media/GVMhZwYv8U5NK/200.gif)

**Comment by selynna** [comment]
yay
