### ISSUE TITLE
Food for Hack Camp session 2 week 2

### ISSUE THREAD

**Issue by maxwofford** [hackedu/hack-camp#720]
This can be closed once the food is either scheduled to be delivered to the venue or already at the venue.
- [x] Chips
- [ ] Chocolate (This was requested, not sure how much we should get)
- [x] Water
- [x] Cheez-It®
- [x] Pop-Tarts®

**Comment by maxwofford** [comment]
@ssun098 anything else we should get?

**Comment by selynna** [comment]
Refills of cheese its and poptarts i guess?

**Comment by maxwofford** [comment]
Added to the list

**Comment by selynna** [comment]
@MaxWofford can you take point on the food? I can't get to the venue in time, so it doesn't make sense for me to get it

**Comment by maxwofford** [comment]
Will do!

**Comment by selynna** [comment]
@MaxWofford can we close this? I think we're fine on food

**Comment by maxwofford** [comment]
Sounds good!
