### ISSUE TITLE
Get 2 mentors onboarded by EOD Sunday (7/3)

### ISSUE THREAD

**Issue by maxwofford** [hackedu/hack-camp#722]
We need 2 more mentors confirmed on on-boarded by the end of the week.

This issue can be closed once they've confirmed their spots for the second week and have completed the tasks for their on-boarding (on-boarding protocol is in-progress https://github.com/hackclub/hackcamp/issues/721).

**Comment by selynna** [comment]
@MaxWofford can this be closed? date already passed and I don't think we're going to get too much extra help for this week

**Comment by maxwofford** [comment]
Yep, going to close.
