### ISSUE TITLE
Learn a new card game

### ISSUE THREAD

**Issue by selynna** [hackedu/hack-camp#730]

**Comment by zachlatta** [comment]
Hearts? Spades? Texas hold 'em?

_werewolf_

On Wed, Jul 6, 2016 at 5:28 PM, Selynna Sun notifications@github.com
wrote:

> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> https://github.com/hackclub/hackcamp/issues/730, or mute the thread
> https://github.com/notifications/unsubscribe/AA8j-DTSlKO-xzaGw32Blm-qlgOhKn1-ks5qTEghgaJpZM4JGoW9
> .

## 

Zach Latta
Hack Club | zach@hackclub.com

**Comment by selynna** [comment]
Oh dang I totally forgot about hearts - will do that one. Thanks!
