### ISSUE TITLE
Write a "thank you" letter to @johndbritton

### ISSUE THREAD

**Issue by maxwofford** [hackedu/hack-camp#731]
The GitHub tour was fantastic – let's send John Britton a "thank you" letter.

**Comment by maxwofford** [comment]
@ssun098 What if we turn this issue into a "Thank You" note and tag him on it?

**Comment by LordDarkMelon** [comment]
Thanks for the hoodies John, they're awesome

ps: remember: the "octogon"

**Comment by strik0za** [comment]
Thank you so much for the Github tour! It was really cool seeing a tiny bit of the culture behind Github, plus the hoodies/stickers are fantastic.

**Comment by iando407** [comment]
Thanks John for the great tour. 7 out of 9 of us are still wearing the github hoodie so thank you for that as well.

**Comment by anntheknee** [comment]
Thanks for the github tour John. The food and office was amazing. Also thanks for the hoodie :)

**Comment by fqfernando** [comment]
Thank you so much for everything!!! . The lunch was amazing !! loved the pool table!

**Comment by brandon65438** [comment]
Thank you John. I appreciate the hoodies you gave us for free and the tour of github.

**Comment by ginabrin** [comment]
THANKS JOHN!! Thanks for taking time out of your day to show us around GitHub! Your library was super cool, unfortunately it would take too long to read every book i wanted :P. Thanks for the hoodies and for the tour!

**Comment by maxwofford** [comment]
cc @johndbritton

**Comment by johndbritton** [comment]
You're welcome! Thanks for coming by.

:octocat: :heart: 🎓
