### ISSUE TITLE
Secure venue for 3rd session

### ISSUE THREAD

**Issue by maxwofford** [hackedu/hack-camp#734]
@zachlatta Can you take point on this?

**Comment by zachlatta** [comment]
Fo' sure.

On Fri, Jul 8, 2016 at 9:54 AM, Max Wofford notifications@github.com
wrote:

> @zachlatta https://github.com/zachlatta Can you take point on this?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/hackclub/hackcamp/issues/734, or mute the thread
> https://github.com/notifications/unsubscribe/AA8j-HDCfQcPjaNA6j9QTsQ3d5AQMC_iks5qToDMgaJpZM4JINW4
> .

## 

Zach Latta
https://zachlatta.com http://zachlatta.com

**Comment by zachlatta** [comment]
Going to reduce scope of this issue to just venue for third session.

**Comment by zachlatta** [comment]
Waiting on a response from a contact who said they might be able to do it.

**Comment by selynna** [comment]
Waiting on responses from 2 potential venues

**Comment by zachlatta** [comment]
Okay, I have a tentative yes for 448 Bryant to re-host. They're gonna finalize tomorrow AM with me.

Let's move forward assuming they're a yes and we'll just deal with it if we need to find an alternative. I have a couple good leads and the spot in San Mateo is a yes.

**Comment by zachlatta** [comment]
Going to unblock the issues that are blocking on this.

**Comment by zachlatta** [comment]
This is now blocking on their response, so leaving blocking label on.

**Comment by zachlatta** [comment]
Alright, so 448 Bryant is not down, but Torch Communications in FiDi is down to host. Closing now that we have a venue.
