### ISSUE TITLE
Packets signed for 2016 session 3 hackers

### ISSUE THREAD

**Issue by maxwofford** [hackedu/hack-camp#735]

**Comment by maxwofford** [comment]
Here's the packet: [composite.pdf](https://github.com/hackclub/hackcamp/files/362142/composite.pdf)

**Comment by ssun098** [comment]
Blocking on updated packet

**Comment by selynna** [comment]
Blocking until we resolve #734 

EDIT: sending this packet out with all the updated info for Hack Camp, but no venue yet

**Comment by zachlatta** [comment]
Unblocking because of latest progress with #734.

**Comment by selynna** [comment]
Packets sent out!

**Comment by selynna** [comment]
@zachlatta waiting on 2 hackers, do you think you could reach out to them?

**Comment by maxwofford** [comment]
@ssun098 If you DM me the names on Slack, I'm happy to reach out.

**Comment by selynna** [comment]
All signed
