### ISSUE TITLE
Set up 2016 session 3 venue

### ISSUE THREAD

**Issue by maxwofford** [hackedu/hack-camp#738]
Ensure the following are all ready for camp:
    - [ ] Breakfast
    - [ ] Tables
    - [ ] Chairs
    - [ ] Internet

**Comment by maxwofford** [comment]
Blocking on #734

**Comment by zachlatta** [comment]
Going to let this continue blocking on #734 despite latest progress until tomorrow AM gives us a resolution.

**Comment by zachlatta** [comment]
Unblocking because we now have a venue.

**Comment by maxwofford** [comment]
Going to close this because we've just run the first day.
