### ISSUE TITLE
Secure venue for 4th session

### ISSUE THREAD

**Issue by zachlatta** [hackedu/hack-camp#739]
Hopefully #734 will also get us this, but I'm moving this to a separate issue just in case the venue for third session doesn't want to host us for the fourth.

**Comment by maxwofford** [comment]
Keeping the title consistent with https://github.com/hackclub/camp/issues/734

**Comment by selynna** [comment]
Reached out to 2 potential venues about 3rd and 4th, just fyi here

**Comment by zachlatta** [comment]
Giving this to @ssun098 to take over.

**Comment by selynna** [comment]
@zachlatta unassigning you as I assume you meant to do so in standups yetserday

**Comment by maxwofford** [comment]
Going to close this because no longer planning on running a 4th session.
