### ISSUE TITLE
Create and write descriptions Cohort 2  tasks generated in the brainstorming session

### ISSUE THREAD

**Issue by jonleung** [hackedu/hack-camp#75]
For the below tasks

https://gist.github.com/jonleung/e79e1de50a0724bf3337

1) Make sure that they're not already tasks in the Kanban
2) If they are not already a task, create the task and make the description human readable such that anyone in the organizaiton would be able to complete it.

**Comment by zachlatta** [comment]
Closing for now for @MaxWofford.
