### ISSUE TITLE
Create CSS examples for cohort 2

### ISSUE THREAD

**Issue by jonleung** [hackedu/hack-camp#77]
1.  [ ] Figure out what main phaser-like examples should be (note this is not necessarily to create them but they can be found as well). Each example should be very small and only focus on a very specific concept and one and only one concept. Also, there should be many examples to illustrate a wide variety of concepts. For CSS for example:
   a. w3 school examples
   b. css tricks
2.  [ ] Outline the examples you are planning on making and review your potential examples with team (**do this earlier rather than later**)
3.  [ ] Create the examples 
4. [ ] Publish the examples so that they are in a JS Bin like place (note that examples that focus on javascript should not be in JS bin because the debugger cannot be properly used.

Note: As an example, in phaser, they have an example for merely how to (1) add a sprite, (2) add an image, (3) add multiple sprites, (4) make the sprite do just 1 thing, (5) make the sprite do just this other thing. [Link](http://phaser.io/examples/v2/category/sprites).

**Comment by zachlatta** [comment]
@MaxWofford can you say which repo this was moved to and close it?

**Comment by maxwofford** [comment]
issue transfered to hackedu/cohort-2-curriculum
