### ISSUE TITLE
Files with colons in their name break Windows

### ISSUE THREAD

**Issue by anntheknee** [hackedu/hack-camp#779]
Screenshots of errors are attached below

![gitstatuserror2](https://cloud.githubusercontent.com/assets/15256269/17075844/8976efb4-5055-11e6-9c07-d812a0cc2e8b.png)
![gitstatuserror](https://cloud.githubusercontent.com/assets/15256269/17075845/8979f916-5055-11e6-9843-804f814b4478.png)

**Comment by maxwofford** [comment]
Apparently our docs aren't supported  on windows.

![](https://media.giphy.com/media/83QtfwKWdmSEo/giphy.gif)

**Comment by zachlatta** [comment]
Can you clarify what you mean by this? Do our workshops not work on Windows?

**Comment by maxwofford** [comment]
Filenames on Windows can't have `:` in them. Some images in our repo had `:`s in the file name.

**Comment by zachlatta** [comment]
Closed by #780.
