### ISSUE TITLE
Maestro bootstrap template

### ISSUE THREAD

**Issue by jonleung** [hackedu/hack-camp#82]
starting point for maestro projects

**Comment by maxwofford** [comment]
Max correspond with @zachlatta

**Comment by zachlatta** [comment]
Is this still needed?

**Comment by maxwofford** [comment]
Web bootstrap is only relevant to hackers (in Hack Camp) on a case-by-case basis.

Maestro web bootstrap is at https://github.com/MaxWofford/maestro-bootstrap for cloning into c9.io

**Comment by maxwofford** [comment]
My bad, clicked close on accident.
