### ISSUE TITLE
Phaser bootstrap template

### ISSUE THREAD

**Issue by jonleung** [hackedu/hack-camp#83]
starting point for phaser projects
- See Zed Shaw's python template.

**Comment by jonleung** [comment]
@zachlatta, hit me up before you start working on this so we can talk requirements so that the template is something we actually use. Thanks!

**Comment by zachlatta** [comment]
Is this still needed?

**Comment by jonleung** [comment]
@zachlatta no, it is not, I we've decided not to do phaser this cohort
