### ISSUE TITLE
Plan brainstorming session for what needs to happen to set up labs program

### ISSUE THREAD

**Issue by andreadeng** [hackedu/hack-camp#84]

**Comment by zachlatta** [comment]
Went ahead and set a time on the 13th for this (check your emails for invites). I invited @jonleung and @MaxWofford. @andreadeng do you want to be in this as well?

**Comment by zachlatta** [comment]
Alright, people are confirmed.

**Comment by jonleung** [comment]
@zachlatta, I'll be remote so can I join via http://partytime.hackedu.us (can
you add this to the calendar event)?
ᐧ

—
Sent from my mobile–apologies for brevity and any typos!

hackedu.us | 610-761-0083
