### ISSUE TITLE
Plan brainstorming session for what needs to happen to get generic "club things" in box

### ISSUE THREAD

**Issue by andreadeng** [hackedu/hack-camp#85]
There are many things that _any_ successful club needs to do, like have good recruitment and fundraising, that we're not currently accounting for at all in the club-in-a-box.

Plan a brainstorming session to brainstorm what things we need to include to account for these generic "club things". Perhaps bring existing club leaders and leaders of successful clubs (even if not coding) into the discussion.

**Comment by jonleung** [comment]
When is the latest that we can do this such that it is still actionable?

**Comment by zachlatta** [comment]
I've gone ahead and set a time on the 15th and been inviting select club leaders to it. Trying to go for people with a fair amount of experience.

Will move this to done once I have everyone confirmed.

**Comment by zachlatta** [comment]
Alright, people are confirmed.

Looking forward to seeing ya'll in it.

/cc @raphaelrk @amysorto @infinitebattery7 @jonleung

**Comment by jonleung** [comment]
@zachlatta, is there a calendar event for this?
ᐧ

—
Sent from my mobile–apologies for brevity and any typos!

hackedu.us | 610-761-0083

**Comment by zachlatta** [comment]
Yup, check your email for an invite.
