### ISSUE TITLE
Accept applicants for cohort 3

### ISSUE THREAD

**Issue by zachlatta** [hackedu/hack-camp#88]
Third cohort will be taking place from July 13th - July 24th.

@jonleung how many people should we accept for this?

**Comment by jonleung** [comment]
@zachlatta lets discuss at meeting today!

**Comment by zachlatta** [comment]
Can you make sure to schedule this? I don't see anything on my calendar.

**Comment by jonleung** [comment]
Closing because it is a duplicate of the active task #91
