### ISSUE TITLE
Explicit about Transportation

### ISSUE THREAD

**Issue by jonleung** [hackedu/hack-camp#9]
We should add something like "Transportation: Students are responsible for their own transportation to and from our San Francisco venue and to special field trips."

@zachlatta Please reword for unknown location.

**Comment by zachlatta** [comment]
Have we been getting questions about this? Agreed we should probably add.

**Comment by maxwofford** [comment]
Do we have any field-trips explicitly planned, or should I keep this vague?

**Comment by zachlatta** [comment]
Not explicitly yet. @jonleung---can you provide input here? You have a
much better idea of curriculum than I.

**Comment by maxwofford** [comment]
Resolved inperson with @jonleung. Fieldtrips are cut.
