### ISSUE TITLE
Accept people for cohort 3

### ISSUE THREAD

**Issue by zachlatta** [hackedu/hack-camp#91]
The time to accept cohort 3 has come!

Acceptance process:
1. Identify people to accept (@jonleung needs to provide criteria/hacker breakdown he wants)
2. Give every accepted person a call letting them know that we'd like to accept them to Hack Camp and telling them that we'll send an email with more information. Don't worry about asking them about financial aid, we already know who needs it and we'll account for it during the next step on a case-by-case basis.
3. Talk to me and have me add every called and accepted person to our payment portal for tuition. Anyone who requested financial aid will be accounted for now.
4. Send email to every accepted and called applicant with more information and a link to pay their tuition (talk to me for the email template, I already have one written up)
5. Once paid, send email with acceptance packet (talk to me for template email and acceptance packet). The packet includes liability waivers.

**Comment by andreadeng** [comment]
@jonleung can you comment with types of people you want to accept for cohort 3?

**Comment by zachlatta** [comment]
@jonleung ping, would be great to move on this ASAP!

**Comment by jonleung** [comment]
@zachlatta @andreadeng  https://docs.google.com/spreadsheets/d/1HrEIzm76U9RaQvVpNvSPocfmbbC22nxQnYSWsTs4zrw/edit#gid=0

**Comment by jonleung** [comment]
As discussed in standups @andreadeng is currently blocking on @zachlatta for
- [x] Links for payments for each of the 10 students
- [ ] An updated acceptance packet

**Comment by jonleung** [comment]
As discussed during standups, the next step is to identify who has already paid for @zachlatta to respond to @andreadeng's questions?

If people who did not respond, try calling them again.

**Comment by zachlatta** [comment]
Can you clarify what you mean by "identify who has already paid for @zachlatta to respond to @andreadeng's questions?"

**Comment by jonleung** [comment]
Updates from Standups:
- 6 paid
