### ISSUE TITLE
Create student facing outline for the entirety of Hack Camp

### ISSUE THREAD

**Issue by jonleung** [hackedu/hack-camp#98]

**Comment by jonleung** [comment]
https://docs.google.com/spreadsheets/d/1x_3Bh3LqjKSpDTQb8sr2alhsORp-su2oKxS9zKEPQWU/edit#gid=1956850792

**Comment by zachlatta** [comment]
What's the status on this?

**Comment by jonleung** [comment]
@zachlatta, This probably won't be finished in time for cohort 2. Moving as a task for cohort 3 in icebox

**Comment by zachlatta** [comment]
Does it make sense to do this task for cohort 3?

**Comment by zachlatta** [comment]
Closing due to using a different format for this upcoming cohort. See 0bc45c5a215fdd23a2d2e6933be20f54422577d5 for our notes from the planning session this morning.
