### ISSUE TITLE
Create Teacher Cheat Sheet 

### ISSUE THREAD

**Issue by jonleung** [hackedu/hack-camp#99]
This is reinforced based on the conversation with the MB teacher as well.
## v2
- [ ] video demos of each concept

Examples:

Teacher Pro Tips
- Predicting timing
- Any synchronous things:
  - Build things from the perspective from the student
  - If you hit concepts that need to be reinforced, cold call on the person to tell you what the concept is
  - Cold calling during this process to keep engaging
    - If they don't know the answer, you can google it together let's google it together
  - Must be contained to 15 minutes in a given instance. You must stop yourself
    - Ideally this would be planned ahead of time to fit in that time, but you may take longer.

**Comment by zachlatta** [comment]
Can you include a few more details in this issue?

**Comment by jonleung** [comment]
@zachlatta, added some more details

**Comment by zachlatta** [comment]
Who's "the MB teacher"?

I still don't quite understand what this issue is about.

**Comment by zachlatta** [comment]
Ping.

**Comment by zachlatta** [comment]
Closing due to cohort 2 being over.
